### PR TITLE
Add support for Arexx Multilogger

### PR DESCRIPTION
**Pull request by zuckschwerdt**
Adds support for Arexx Multilogger IP-HA90, IP-TH78EXT, TSN-70E.

See also #2388 and #2482.

### CODE REVIEW

**Comment by zuckschwerdt** [comment]
I still need to add the MCP9808 decoding for the IP-HA90.

We need to know if the Arexx TSN-70E is compatible to that.
And @MacH-21  did you test your "Arexx IP-TH78EXT"(?) yet?

**Comment by inonoob** [comment]
Dear all, 

I've compiled the version with the support and tracked the following messages: 

I have 6 sensor just next to me: 

time      : 2023-04-20 21:17:44
model     : Arexx-ML     ID        : 40b9
Humidity  : 0655         Integrity : CRC
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2023-04-20 21:17:50
model     : Arexx-ML     ID        : 4e2a
Temperature: 1701        Integrity : CRC
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2023-04-20 21:17:50
model     : Arexx-ML     ID        : 4f86
Temperature: 1748        Integrity : CRC
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2023-04-20 21:18:05
model     : Arexx-ML     ID        : 4e2b
Humidity  : 0665         Integrity : CRC
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2023-04-20 21:18:27
model     : Arexx-ML     ID        : 4e2a
Temperature: 1700        Integrity : CRC
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2023-04-20 21:18:38
model     : Arexx-ML     ID        : 4f87
Humidity  : 066e         Integrity : CRC
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2023-04-20 21:18:40
model     : Arexx-ML     ID        : 40b8
Temperature: 175c        Integrity : CRC
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2023-04-20 21:18:55
model     : Arexx-ML     ID        : 4dea
Temperature: 169c        Integrity : CRC
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2023-04-20 21:19:06
model     : Arexx-ML     ID        : 4e2b
Humidity  : 0678         Integrity : CRC
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2023-04-20 21:19:12
model     : Arexx-ML     ID        : 40b9
Humidity  : 0658         Integrity : CRC
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2023-04-20 21:19:16
model     : Arexx-ML     ID        : 4f86
Temperature: 1751        Integrity : CRC
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2023-04-20 21:19:31
model     : Arexx-ML     ID        : 4e2a
Temperature: 171b        Integrity : CRC
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2023-04-20 21:19:34
model     : Arexx-ML     ID        : 4da6
Temperature: 16cf        Integrity : CRC
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2023-04-20 21:19:35
model     : Arexx-ML     ID        : 4f87
Humidity  : 0669         Integrity : CRC
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2023-04-20 21:19:48
model     : Arexx-ML     ID        : 4e84
Temperature: 16b3        Integrity : CRC
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2023-04-20 21:19:52
model     : Arexx-ML     ID        : 4deb
Humidity  : 0684         Integrity : CRC
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2023-04-20 21:19:58
model     : Arexx-ML     ID        : 40b8
Temperature: 176a        Integrity : CRC
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2023-04-20 21:20:08
model     : Arexx-ML     ID        : 4da7
Humidity  : 0721         Integrity : CRC
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2023-04-20 21:20:11
model     : Arexx-ML     ID        : 4f86
Temperature: 1759        Integrity : CRC
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2023-04-20 21:20:21
model     : Arexx-ML     ID        : 40b9
Humidity  : 0654         Integrity : CRC
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2023-04-20 21:20:22
model     : Arexx-ML     ID        : 4e85
Humidity  : 0714         Integrity : CRC
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2023-04-20 21:20:32
model     : Arexx-ML     ID        : 4e2b
Humidity  : 066d         Integrity : CRC
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2023-04-20 21:20:38
model     : Arexx-ML     ID        : 4dea
Temperature: 16c4        Integrity : CRC
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2023-04-20 21:20:50
model     : Arexx-ML     ID        : 4f87
Humidity  : 0666         Integrity : CRC
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2023-04-20 21:20:55
model     : Arexx-ML     ID        : 40b8
Temperature: 1770        Integrity : CRC
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2023-04-20 21:21:00
model     : Arexx-ML     ID        : 4da6
Temperature: 170e        Integrity : CRC
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2023-04-20 21:21:15
model     : Arexx-ML     ID        : 4e84
Temperature: 16ee        Integrity : CRC
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2023-04-20 21:21:28
model     : Arexx-ML     ID        : 4f86
Temperature: 175e        Integrity : CRC
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2023-04-20 21:21:32
model     : Arexx-ML     ID        : 4e2a
Temperature: 175e        Integrity : CRC
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2023-04-20 21:21:33
model     : Arexx-ML     ID        : 4da7
Humidity  : 0712         Integrity : CRC
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2023-04-20 21:21:39
model     : Arexx-ML     ID        : 4deb
Humidity  : 067a         Integrity : CRC

**Comment by inonoob** [comment]
Hey, 

I've done the next cross check: 

_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2023-04-20 22:00:33
model     : Arexx-ML     ID        : 4deb
Humidity  : 52.2 %       Sensor Raw: 0633          Integrity : CRC
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2023-04-20 22:00:43
model     : Arexx-ML     ID        : 4e2b
Humidity  : 53.3 %       Sensor Raw: 0657          Integrity : CRC
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2023-04-20 22:00:47
model     : Arexx-ML     ID        : 40b9
Humidity  : 53.1 %       Sensor Raw: 0651          Integrity : CRC
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2023-04-20 22:00:49
model     : Arexx-ML     ID        : 4da6
Temperature: 20.23 C     Alert     : 0             Sensor Raw: 1787          Integrity : CRC
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2023-04-20 22:01:05
model     : Arexx-ML     ID        : 4e2a
Temperature: 19.92 C     Alert     : 0             Sensor Raw: 1768          Integrity : CRC
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2023-04-20 22:01:11
model     : Arexx-ML     ID        : 4f87
Humidity  : 54.1 %       Sensor Raw: 0671          Integrity : CRC
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2023-04-20 22:01:15
model     : Arexx-ML     ID        : 40b8
Temperature: 20.09 C     Alert     : 0             Sensor Raw: 1779          Integrity : CRC
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2023-04-20 22:01:27
model     : Arexx-ML     ID        : 4da7
Humidity  : 56.2 %       Sensor Raw: 06b4          Integrity : CRC
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2023-04-20 22:01:36
model     : Arexx-ML     ID        : 4f86
Temperature: 19.72 C     Alert     : 0             Sensor Raw: 1754          Integrity : CRC
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2023-04-20 22:01:36
model     : Arexx-ML     ID        : 40b9
Humidity  : 53.1 %       Sensor Raw: 0650          Integrity : CRC
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2023-04-20 22:01:42
model     : Arexx-ML     ID        : 4e84
Temperature: 19.52 C     Alert     : 0             Sensor Raw: 1740          Integrity : CRC
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2023-04-20 22:01:44
model     : Arexx-ML     ID        : 4dea
Temperature: 19.41 C     Alert     : 0             Sensor Raw: 1735          Integrity : CRC
^CSignal caught, exiting!
 ino  ~  Software  rtl_433 

**Comment by zuckschwerdt** [comment]
Are those values plausible, are they what you expect?

**Comment by inonoob** [comment]
I have two comments for the moment. 

the temperature conversion: 
temp_c = sens_val * 0.01f - 40.0f  ==> it should be temp_c = sens_val * 0.01f - 39,6f as it is 3V 

In addition the datasheet mention that if temperatur is different from 25°C the relative humidity must be compensate. 

I found from Arexx the following formula for the humidity: 

3 nodes:
value=p0 + rawValue*(p1 + rawValue*p2)

p0=-4
p1=0.0405
p2=-2.8e-6

float humidity = -4 + 0.0367 * sens_val * (0.0405 * -sens_val* 2.8e-6) 

What do you think ? 

Source: https://github.com/redflo/pylarexx/blob/master/sensors.txt
https://github.com/redflo/pylarexx/blob/master/deviceinfo.xml

**Comment by inonoob** [comment]
But at the end I must release that the Accuracy for SHT10 is for Humidity +- 4,5% and for temperature +- 0,5°C. So I would say the are within specs.

**Comment by zuckschwerdt** [comment]
Thanks. Yes the 3V conversion seems better suited. The humidity conversion depends on wether the hardware is V3 or V4. Do you know it is V3 (the -4 p0, V4 has -2 there)?

**Comment by inonoob** [comment]
Could you tell me your source for the V3 and V4 topic ? I would like to double check.

**Comment by zuckschwerdt** [comment]
> Could you tell me your source for the V3 and V4 topic ? I would like to double check.

The [older datasheets](https://www.sparkfun.com/datasheets/Sensors/SHT1x_datasheet.pdf) have that note in "Table 6". The [current datasheet](https://sensirion.com/products/catalog/SHT10) only has the newer calculation.

**Comment by inonoob** [comment]
Oh nice catch. Yeah I would suggest to stick with you version then.

**Comment by inonoob** [comment]
I would also propose to change the ID to int dec: 

`"id", "ID", DATA_FORMAT, "%04x", DATA_INT, id,`

to 

`"id", "ID", DATA_FORMAT, "%d", DATA_INT, id,`

**Comment by inonoob** [comment]
Hey, 

question don't you have a conflict with [245]* ThermoPro TX-2C Thermometer and this branch as this sensor is 245 aswell ? 

best regards

**Comment by MacH-21** [comment]
Hi All,
Sorry for long delay in replying,

@zuckschwerdt 

> I still need to add the MCP9808 decoding for the IP-HA90.
> 
> We need to know if the Arexx TSN-70E is compatible to that. And @MacH-21 did you test your "Arexx IP-TH78EXT"(?) yet?

TSN-TH70E internal SHT10 is same as IP-TH78EXT external SHT10 IP rated enclosure, therefore compatible.
It is the sensor type that requires sorting first, which can be done on the 16bit ID
(Device ID & 0xf000) = 0x2000-TC-77,  0x4000-SHT10, 
32bit ID = MCP9808.
I have attached txt file!! snip of code to decode the sensors, hopefully it makes sense, also a screen capture of decode.  
RTL-Arexx-YAT-2
[rtl_issue_2487-1.txt](https://github.com/merbanan/rtl_433/files/11466037/rtl_issue_2487-1.txt)

**Comment by MacH-21** [comment]
> Are those values plausible, are they what you expect?

I use V3 parameters, so it has continuity with the Arexx software.

**Comment by inonoob** [comment]
Hey,

quick question merge still open or did I miss it ?

**Comment by inonoob** [comment]
Hey, 

quick question. The Arexx company seems to have started to sell those sensor again. The amount of units might increase over the time. I still see that this is branch on it own. The sensor did had the number 250 but in the meantime other sensors have been added. 

The sensor number could be changed and then merged into the master ? 

BR

**Comment by inonoob** [comment]
My setup is working since 7 month without any issue with MQTT and Home Assitant. So again many thanks to everyone making from electronic waste into useful set sensors.

**Comment by zuckschwerdt** [comment]
Thanks @inonoob for the feedback and keeping up with the long journey to get this merged!

**Comment by inonoob** [comment]
Thanks to you @zuckschwerdt for your support in the long journey and making it possible. Ah by the way, Arexx is back and has started to launch new sensors again. On Reichelt they have there new model. Let hope they keep the 433 encoding :)

**Pull request merged**
