### PR TITLE
gt_wt_02 new Output "2"

### PR DESCRIPTION
**Pull request by ludwich66**
Update gt_wt_02 with a cleand branch enviroment.
is it Ok ? Sorry i had always problems with GitHub...
ludwich

### CODE REVIEW

**Comment by ludwich66** [comment]
Update gt_wt_02 withe a cleand branchenviroment.
is it Ok ? Sorry always problems with GitHub...
ludwich

**Comment by ludwich66** [comment]
Please look at the GT_WT_02 PR again. I have removed the old files from the PR. So it should work.

**Comment by merbanan** [comment]
Sorry for the delay.

**Comment by ludwich66** [comment]
No topic, I thought you overlooked the change
thx ludwich

**Pull request merged**
