### PR TITLE
Add precision time and time report options

### PR DESCRIPTION
**Pull request by zuckschwerdt**
Like @merbanan suggested this snapshots the current time when a buffer is received and reports time with exact frame start precision.
Adds meta data options to add microseconds on time output, select sample position or data/time output.
Sample position output now shows the exact frame start instead of buffer start.

### CODE REVIEW

**Comment by zuckschwerdt** [comment]
A gettimeofday() implementation for win32 needs to be added.

**Comment by merbanan** [comment]
Looks good. Commit at will.

**Comment by zuckschwerdt** [comment]
Additionally this deprecates the `-U` option in favor of `-M utc` to get all meta data options in one place.

**Comment by zuckschwerdt** [comment]
@winterrace can you check if the gettimeofday implementation for win32 compiles cleanly and works?

**Comment by winterrace** [comment]
Of course. I will do so tomorrow

**Comment by zuckschwerdt** [comment]
@winterrace Thanks! I've just merged this, so you can PR a fix ;) cleanly on top of master.

**Pull request merged**
