### PR TITLE
Adds a boolean data type for structured output

### PR DESCRIPTION
**Pull request by tecknicaltom**
This adds a DATA_BOOL type for structured output. The value should be a
C99 bool type (through <stdbool.h>) and the JSON/KV/CSV output will be
true or false. This should be helpful for fields such as a low battery
status or other binary sensor fields.

### CODE REVIEW

**Comment by zuckschwerdt** [comment]
looks very good. I'll have to think about the whole `battery`, `battery_low`, `battery_ok` / `YES`, `NO`, `OK`, `LOW` example for a few days.

**Comment by tecknicaltom** [comment]
I plan to finish the implementation for the DSC sensors, which will involve (in addition to including the raw status byte) decoding the status byte to expose whether the sensor is indicating open (e.g. door/window opened), low battery, tamper sensor, heartbeat... Additionally it might be useful to expose whether the CRC check passed. A boolean data type seemed appropriate for these types of things.

**Comment by rct** [comment]
A boolean would be useful as there is a range of 0/1, True/False. 

@tecknicaltom - I've got the DSC bits mapped out (I'm the original author) though I haven't been decided on naming.  I'd like to compare notes via a different issue or direct. My email is in the Authors file.

**Comment by zuckschwerdt** [comment]
Yes, using boolean values totally makes sense. Though I pondering whether this will work well with consumers. I take it that time series loggers will store and aggregate numerical types well. Thus using `0` and `1` will work by default. Is there support for true booleans in e.g. Graphite, Influx, Sqlite and such? Is `battery_low: 1` or `battery_low: true` easier to process?
How about popular home automation tools, do they parse bools or ints as flags?

**Comment by zuckschwerdt** [comment]
Let's maybe come back to this PR when #827 and other discussion around formatting has settled.

**Pull request closed without merging**
