### PR TITLE
Refactoring of device support and combined pull requests for PRs #34, #50, #52, #54, #57, and #60

### PR DESCRIPTION
**Pull request by helgew**
I have factored out the device support into separate files and merged in the commits from all other pull requests.

### CODE REVIEW

**Comment by rct** [comment]
It's great to see you taking on this work.

Have you seen @Batilan's plugin work:  https://github.com/Batilan/rtl_433/tree/plugins?

There was a discussion under a different issue.  The decode routines are run (iterating over every sample) multiple times for device defined.

**Comment by helgew** [comment]
@rct I had not seen @Batilan's work, otherwise I would have gone off of it since it is much more mature already. What do you think, @merbanan?

**Comment by merbanan** [comment]
Looks good too me from a brief look.

**Comment by rct** [comment]
We need a better place than an issue to discuss rtl_433.  Issues get closed and the information gets hidden.

The structure I've been thinking about is to do the edge detection that analyze mode does and then to let the call backs work with that to determine if it is their signal or not rather than having every callback iterate over every sample each time to find the edges.

**Pull request merged**
