### PR TITLE
build: fix build for FreeBSD

### PR DESCRIPTION
**Pull request by micro3x**

### CODE REVIEW

**Comment by zuckschwerdt** [comment]
Thanks! Is that all that's needed? What inputs work, do you use librtlsdr, or SoapySDR? MAybe you also want to add notes to BUILDING.md?

**Comment by zuckschwerdt** [comment]
I guess we should really use
```
    #include <sys/types.h>
    #include <sys/socket.h>
    #include <netdb.h>
    #include <netinet/in.h>
```
unconditionally (except Win32).

Is settting `__BSD_VISIBLE` the proper way? Shouldn't we select the right `_SOURCE` level?
Only setting `_POSIX_C_SOURCE`, `_ANSI_SOURCE` or `_C99_SOURCE` will hide `__BSD_VISIBLE` and we set none of those, right?

**Comment by zuckschwerdt** [comment]
f26830d inserts the missing include. Can you test again and rebase this change if needed?

**Comment by micro3x** [comment]
"Fix socket portability" worked perfectly.
Closing this PR since now it's obsolete.

**Comment by zuckschwerdt** [comment]
Thanks for testing and the feedback!

**Pull request closed without merging**
