### PR TITLE
add TFA pool thermometer support

### PR DESCRIPTION
**Pull request by kissandr**

### CODE REVIEW

**Comment by merbanan** [comment]
Can you upload some sample signals ? Send a pull request to rtl_433_tests

**Comment by zuckschwerdt** [comment]
I don't think the ID will be at the end if you put the DECL in the middle ( include/rtl_433_devices.h vs  include/rtl_433_devices.h).

**Comment by zuckschwerdt** [comment]
@kissandr btw, you can amend your commit and force push. No need to open a new PR.

**Comment by kissandr** [comment]
I have already uploaded them;
https://github.com/merbanan/rtl_433_tests/tree/master/tests/TFA-Pool-thermometer-30.3160

üdv.: András

2016-05-26 23:46 GMT+02:00 Benjamin Larsson <notifications@github.com>:

**Pull request merged**
