### PR TITLE
Add support for longer EFTH800 messages

### PR DESCRIPTION
**Pull request by andrewjw**
This adds support for the longer EFTH800 messages in #2275. It passes all the tests, but I've yet to run it for real so probably not ready to be merged yet.

### CODE REVIEW

**Comment by zuckschwerdt** [comment]
Another idea to mostly keep the row search intact:
After the `row = bitbuffer_find_repeated_row(bitbuffer, 2, 48);` check if the row is not the one we are interested in.
If so set `bitbuffer->bits_per_row[row] = 0; // remove this row from candidates` and again run `row = bitbuffer_find_repeated_row(bitbuffer, 2, 48);`

**Comment by zuckschwerdt** [comment]
Sorry, more changes. I think this is the most obvious way to clear out the long rows and keep the logic of one simple `bitbuffer_find_repeated_row()`

Just this block as first code in the decoder, no other changes needed then.

```
    // Remove long rows with unknown data
    for (row = 0; row < bitbuffer->num_rows; ++row) {
        if (bitbuffer->bits_per_row[row] > 49) {
            bitbuffer->bits_per_row[row] = 0; // cancel row
        }
    }
```

**Comment by zuckschwerdt** [comment]
And add this comment between: `(0-bit) 250 us pulse, 480 us gap.` and `Data layout:`

```

There might be an alternative (longer) packet interleaved, e.g.:

    {65} 2B 1E A9 90 AB D3 83 2A 8
    {49} AB 1F B3 B7 B6 BE 80
    {65} 2B 1E A9 90 AB D3 83 2A 8
    {49} AB 1F B3 B7 B6 BE 8

```

**Comment by andrewjw** [comment]
Thanks for the suggestions, I've applied them and will test them out for a few days. Seems to be working fine though.

With the earlier code one of my four devices dropped out for about 24h, but then reappeared. Unfortunately I didn't get time to capture unknown signals in that time. Might just have been a reception issue though. If it happens again I'll try to investigate.

**Comment by merbanan** [comment]
@zuckschwerdt will this work ? are we not destroying the bitbuffer for other possible decoders with lower priority?

**Comment by zuckschwerdt** [comment]
Yes perfectly fine ;) Each decoder gets a fresh bitbuffer always. E.g. `bitbuffer_invert()` would be a problem otherwise.

**Comment by merbanan** [comment]
True. LGTM then :)

**Comment by zuckschwerdt** [comment]
Ideally we would understand and parse the longer messages. They should contain the same data really.

Maybe @andrewjw can be persuaded to log the long and short codes side-by-side for a few days and share a list?
A text file with (unique) lines similar to `{65} 2B 1E A9 90 AB D3 83 2A 8    {49} AB 1F B3 B7 B6 BE 8`

**Comment by andrewjw** [comment]
Don't worry, I'm easily persuaded. I'll see what I can do over the Christmas period 😃

**Pull request merged**
