### PR TITLE
RTGN129 author name

### PR DESCRIPTION
**Pull request by siddolo**
Code in PR #634

### CODE REVIEW

**Comment by zuckschwerdt** [comment]
Can you also add a header to `oregon_scientific.c`? Look at e.g. `fineoffset.c` for a template. It would be great if you can find other authors in git blame.

**Comment by siddolo** [comment]
I don't know who originally wrote oregon_scientific.c so i don't know how to write the copyright row. I only added the RTGN129 support.

**Comment by zuckschwerdt** [comment]
Looks like this dates back to the first days. A glances at https://github.com/merbanan/rtl_433/commits/master/src/devices/oregon_scientific.c shows maybe 8 authors. I need to do this on a rainy day then ;)

**Comment by siddolo** [comment]
done

**Comment by zuckschwerdt** [comment]
Thanks. The first line in `oregon_scientific.c` should be like "Various Oregon Scientific protocols" not "Fineoffset...", right?
Sorry, about the authors: I think it's best if every author opts-in to have his name and address in the AUTHORS file. Just put all the names in the oregon_scientific.c header in the Copyright line.

**Comment by siddolo** [comment]
do you think that this is the right format?

**Comment by zuckschwerdt** [comment]
thanks!

**Pull request merged**
