### PR TITLE
Update all header doc comments

### PR DESCRIPTION
**Pull request by evilpete**

### CODE REVIEW

**Comment by zuckschwerdt** [comment]
Great start :) Files should look like e.g. https://github.com/merbanan/rtl_433/blob/master/src/devices/kerui.c
- `@file` doc-comment with just one line description (short) and author, copyright. Indented, no leading asteriks.
- doc-comment with one line description (can be longer), no indent, valid markdown.

With the reason that we need copyright information per file and decoder docs per decoder.
Extracting the decoder markdown doc with doxygen isn't great, thus we limit ourselves to a simple text with no indent :)

**Comment by evilpete** [comment]
ok I'll see what I can do about more "cleanup"

As you may have guessed I've been bored,  I'll keep throwing pull requests at you till I get distracted by something else thats new and shiny

**Comment by merbanan** [comment]
@evilpete care to look at https://github.com/merbanan/rtl_433/issues/1424. It is very shiny.

**Comment by evilpete** [comment]
@zuckschwerdt is this better?

**Comment by zuckschwerdt** [comment]
This is really getting us somewhere with the machine-readable doc comments, thanks!

**Comment by evilpete** [comment]
Meh.. No problem, it was less then a hour of editing...

any other low hanging requests??

**Comment by merbanan** [comment]
DOUBLE -> FLOAT wrt datatype name

**Pull request merged**
