### PR TITLE
Add battery_mV to rtl_433_mqtt_hass, change moisture class

### PR DESCRIPTION
**Pull request by fallenpegasus**
Moisture should be "moisture" class, not "humidity" class.
Some devices have battery_mv in addition to battery_ok.

### CODE REVIEW

**Comment by zuckschwerdt** [comment]
Thanks. We don't output `battery_mv` but `battery_mV` :)
Yes, class of `moisture` is valid according to https://www.home-assistant.io/integrations/sensor/ (I guess it wasn't before?)

**Comment by noahwilliamsson** [comment]
Re: fix moisture class.  I'm thinking that the `"object_suffix": "H"` should be changed to `"object_suffix": "M"`.  It's used when computing the MQTT publishing path.  I assume it's in place to avoid name conflicts when a device has multiple sensors.

- https://github.com/merbanan/rtl_433/blob/master/examples/rtl_433_mqtt_hass.py#L751-L759

```
def publish_config(mqttc, topic, model, object_id, mapping, value=None):
    """Publish Home Assistant auto discovery data."""
    global discovery_timeouts

    device_type = mapping["device_type"]
    object_suffix = mapping["object_suffix"]
    object_name = "-".join([object_id, object_suffix])

    path = "/".join([args.discovery_prefix, device_type, object_id, object_name, "config"])
```

For reference, from https://www.home-assistant.io/integrations/sensor/#device-class

>  **humidity**: Percentage of humidity in the air in %
>  **moisture**: Percentage of water in a substance in %

**Comment by zuckschwerdt** [comment]
@fallenpegasus can you include the `object_suffix` change so we can merge this?

**Comment by fallenpegasus** [comment]
I'm going to resubmit this as two pull requests, incorporating the requested changes.

**Pull request closed without merging**
