### PR TITLE
Fixes and example project to compile using MS Visual Studio 2015

### PR DESCRIPTION
**Pull request by winterrace**
Pull request as requested in https://github.com/merbanan/rtl_433/issues/777

### CODE REVIEW

**Comment by zuckschwerdt** [comment]
Thanks.
- Clean up the README ("This is a fork")
- Use restrict instead of RESTRICT and `ifdef` just for `_MSC_VER` like you already do.

**Comment by winterrace** [comment]
winterrace:feat-vs2015 is now reworked as requested (hopefully ;-) )

**Comment by winterrace** [comment]
Sorry, I just accidentally closed the PR. Reopened...

**Comment by zuckschwerdt** [comment]
Looks good, thanks. Can you check if the `rtl_433.vcxproj.filters` file is actually needed to build? Would be one less file to care about when devices are added.

**Comment by winterrace** [comment]
The rtl_433.vcxproj.filters "just" provides a mapping of all the source files (from rtl_433.vcxproj) into different virtual folders in the source file browser. The main advantage is that all device implementations are displayed in a common subfolder, that can be collapsed or expanded.

We could remove rtl_433.vcxproj.filters from the repository, it is not needed to compile the project. However, the project looks quite ugly this way (all *.c and *.h files in one common root folder)

We could also keep it. If we introduce new source files it is basically enough to add them to rtl_433.vcxproj. If they are not added to rtl_433.vcxproj.filters, they will show up in the root folder and can simply be moved by drag and drop (this will auto-update rtl_433.vcxproj.filters).

**Comment by zuckschwerdt** [comment]
For the sake of simplicity I'd rather not have extra files. The reasoning is: we like to support building with other environments, but we don't necessarily want to support development in other environments. I think it would be nice to have but I do see the trouble of maintaining that. (And once we commit to something it's rather hard to remove…)
I only ever use CMake and it's already a problem to keep the Automake in top shape.

Perhaps we could get more opinions on this?

**Comment by merbanan** [comment]
If a script could generate the rtl_433.vcxproj.filters file that would be preferable.

**Comment by zuckschwerdt** [comment]
A small python script to refresh auxiliary files, maybe also the help output in the README etc, yes.

**Comment by auphofBSF** [comment]
Well done,works very well, including using the debugger.   Instructions worked well.

On windows 10, Visual Studio 2015 Community edition I had switch from Win8.1SDK to the Win10SDK that I already had installed. I already had used the 10.0.16299.0  version

Change SDK by  selecting Properties of the project
image

**Comment by winterrace** [comment]
Thanks for sharing your experience. Great that it was useful to you...

**Comment by winterrace** [comment]
Today I included some minor updates the the feat-vs2015 branch: In the vs2015 project files, I renamed the German filter names to English and removed a link to an autogenerated readme file not existing any more. Also, the compilation instructions have been updated with a link to the recent librtlsdr 0.6.0 release (new Win64 project at https://github.com/winterrace/librtlsdr).
Still works well with the latest rtl_433 updates...

**Pull request merged**
