### PR TITLE
Add InFactory PT-310 parsing to Rubicson (longer packet length)

### PR DESCRIPTION
**Pull request by unverbraucht**
Adds the parsing for InFactory PT-310 (aka ZX...) to the Rubicson device.

As discussed in issue #2119.

### CODE REVIEW

**Comment by zuckschwerdt** [comment]
Looks good, thanks! We can't change "model" -- can you undo that change?
And if possible: run `./maintainer-update.py` and commit afterwards.
Just add more commits, we squash on merge.

**Comment by unverbraucht** [comment]
Done. I don't think that maintainer-update changed anything this time.

**Comment by zuckschwerdt** [comment]
Thanks. It should have though. README and example conf are built using the .name value, and that looks different? Maybe you didn't compile recently?

**Comment by unverbraucht** [comment]
Ah yes, that was it, I forgot to build - thanks. I also pulled master just in case.

**Comment by zuckschwerdt** [comment]
Thanks for sticking with this. It can be a nuisance, but we tend to forget to fix small things once PRs are merged ;)

**Comment by unverbraucht** [comment]
Not at all, it's great that the small things matter :)
I've observed around 1-2 wrong measurements per day, I'll investigate and open a separate PR for this.

**Pull request merged**
