### PR TITLE
S3318P: Add Fahrenheit to Celsius conversion (°F to °C)

### PR DESCRIPTION
**Pull request by Koumes**
Adds Fahrenheit to Celsius conversion (°F to °C).

### CODE REVIEW

**Comment by zuckschwerdt** [comment]
Sorry, the device decoders should output all values in a native format only. There is `-C si` for temperature (and other metric) conversion.

**Comment by zuckschwerdt** [comment]
Also I'll take this as a hint to reorganize the help output to be a bit friendlier ;)

**Comment by merbanan** [comment]
Maybe make SI the default?

**Comment by merbanan** [comment]
Well I'm undecided. Maybe guessing with the help of the locale, to really complicate things?

**Comment by zuckschwerdt** [comment]
I've been thinking about adding config files for a while now. Something like an Ini-File parser to read all settings from a well documented file. There could be pseudo-defaults like conversion, choice of some supported center frequencies, a list of possible decoders with annotations and hints, examples of flex decoders, and so on. Also users can simply manage and exchange those configs with others. Not sure about the best format and if we should look into libraries for that.

**Comment by merbanan** [comment]
I wanted to add a daemon mode for rtl_433. That would go hand in hand with a config file. Json might be an option for the config file format.

**Comment by zuckschwerdt** [comment]
Since it's not machine-to-machine data JSON could be too complicated. If INI-file doesn't fit maybe something like YAML or TOML (where TOML is a natural extension of simple INI-files).

**Comment by rct** [comment]
* +1 for the idea of adding a config file, especially with flex decoding and running out of option letters.
* I personally don't like the idea of having translated units be the default especially since the general idea is that rtl_433 should be machine consumed rather than human read.  I would probably have less objection if I was pretty sure the errors that were do to the combination of pretty printing / rounding were eliminated.
* I think the README should be split into multiple documents or at least sections in this order.
   * README - basic overview with links to the other docs.
   * Build/Install
   * Running
   * Adding new decoders

**Pull request closed without merging**
