### PR TITLE
add a flexible general purpose decoder

### PR DESCRIPTION
**Pull request by zuckschwerdt**
Very much a work in progress. Just to put some code to the idea of a quick analyze/debug/hack way to get bitbuffers from rtl_433.
Not for merge, but please use and comment.

### CODE REVIEW

**Comment by panarom** [comment]
:+1:

**Comment by zuckschwerdt** [comment]
Mostly feature complete now. Please test if you are interested. This will be merged in a few days. See #658 for an example.

**Comment by Habbie** [comment]
Don't know where else to write this down - perhaps when this feature lands, we can have some place where we keep a database of useful decoders?

Anyway, I have a 'SelectRemote 1728029' that controls up to 5 230V switches. Using `-F kv  -X "sr:OOK_PWM_RAW:400:800:1600,demod=0"` I get useful output. 

ON button, numbers 1 through 5, filtered through `uniq`:
```
2018-01-07 20:17:34 :	sr 	:	1 	:	1 	:	[	:	25 	:	c0ff3f80]
2018-01-07 20:17:34 :	sr 	:	1 	:	1 	:	[	:	5 	:	c8]
2018-01-07 20:17:35 :	sr 	:	1 	:	1 	:	[	:	25 	:	f0ff3f80]
2018-01-07 20:17:35 :	sr 	:	1 	:	1 	:	[	:	20 	:	f0ff30]
2018-01-07 20:17:36 :	sr 	:	1 	:	1 	:	[	:	25 	:	ccff3f80]
2018-01-07 20:17:36 :	sr 	:	1 	:	1 	:	[	:	14 	:	ccfc]
2018-01-07 20:17:37 :	sr 	:	1 	:	1 	:	[	:	25 	:	fcff3f80]
2018-01-07 20:17:37 :	sr 	:	1 	:	1 	:	[	:	4 	:	f0]
2018-01-07 20:17:38 :	sr 	:	1 	:	1 	:	[	:	25 	:	c3ff3f80]
2018-01-07 20:17:38 :	sr 	:	1 	:	1 	:	[	:	1 	:	80]
```

`uniq` has filtered out repeats of the `25` lines.

Filtering on the 25 length would recognize the 5 individual button presses without the trailing noise.

The OFF buttons change 3f80 to ff80.

**Comment by zuckschwerdt** [comment]
Thanks, yes we need some kind of "cookbook" with recipe for common cases and examples.
I guess this is a kind of x1527 encoder with 24 bits (and a misplaced sync bit =25).
You can filter the noise with the `bits>=24` option (`minbits=24` in older versions).
Also you might want to `match={16}0xff3f` on the fixed part. The `demod` is not really needed, `0` is the default.

**Comment by Habbie** [comment]
Yes, I saw that I could filter. I don't want to match exactly because the remote has 10 buttons, I guess we'd need some 'extraction' for that - or I could define 10 rules, of course. I added the demod while tinkering, I figured it might not be needed. Thanks!

**Comment by Habbie** [comment]
A crash:
```
$ lldb -- ./rtl_433 -F json -X "sr:OOK_PWM_PRECISE:54:167:1750" -R sr
(lldb) target create "./rtl_433"
Current executable set to './rtl_433' (x86_64).
(lldb) settings set -- target.run-args  "-F" "json" "-X" "sr:OOK_PWM_PRECISE:54:167:1750" "-R" "sr"
(lldb) run
Process 69748 launched: './rtl_433' (x86_64)
Disabling all device decoders.
Process 69748 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x4)
    frame #0: 0x00000001000097d1 rtl_433`register_protocol + 177
rtl_433`register_protocol:
->  0x1000097d1 <+177>: cvtsi2ssl 0x4(%rax), %xmm1
    0x1000097d6 <+182>: divss  %xmm0, %xmm1
    0x1000097da <+186>: cvttss2si %xmm1, %ecx
    0x1000097de <+190>: movl   %ecx, 0x4(%rax)
Target 0: (rtl_433) stopped.
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x4)
  * frame #0: 0x00000001000097d1 rtl_433`register_protocol + 177
    frame #1: 0x00000001000086c3 rtl_433`main + 4691
    frame #2: 0x00007fffb8fa6235 libdyld.dylib`start + 1
```

Same with Debug build:
```
$ lldb -- ./rtl_433 -F json -X "sr:OOK_PWM_PRECISE:54:167:1750" -R sr
(lldb) target create "./rtl_433"
runCurrent executable set to './rtl_433' (x86_64).
(lldb) settings set -- target.run-args  "-F" "json" "-X" "sr:OOK_PWM_PRECISE:54:167:1750" "-R" "sr"
(lldb) run
Process 71142 launched: './rtl_433' (x86_64)
Disabling all device decoders.
Process 71142 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x4)
    frame #0: 0x000000010000c8f3 rtl_433`register_protocol(demod=0x0000000101800000, t_dev=0x00000001005000a0) at rtl_433.c:193
   190 	    p->demod_arg = t_dev->demod_arg;
   191 	    if (p->modulation == OOK_PULSE_PWM_PRECISE || p->modulation == OOK_PULSE_CLOCK_BITS) {
   192 	        PWM_Precise_Parameters *pwm_precise_parameters = (PWM_Precise_Parameters *)p->demod_arg;
-> 193 	        pwm_precise_parameters->pulse_tolerance = (float)pwm_precise_parameters->pulse_tolerance / ((float)1000000 / (float)samp_rate);
   194 	    }
   195 	    bitbuffer_clear(&p->bits);
   196
Target 0: (rtl_433) stopped.
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x4)
  * frame #0: 0x000000010000c8f3 rtl_433`register_protocol(demod=0x0000000101800000, t_dev=0x00000001005000a0) at rtl_433.c:193
    frame #1: 0x000000010000b325 rtl_433`main(argc=7, argv=0x00007fff5fbff888) at rtl_433.c:1137
    frame #2: 0x00007fffb8fa6235 libdyld.dylib`start + 1
    frame #3: 0x00007fffb8fa6235 libdyld.dylib`start + 1
(lldb) print pwm_precise_parameters
(PWM_Precise_Parameters *) $0 = 0x0000000000000000
```

**Comment by zuckschwerdt** [comment]
Yes, sorry. _PRECISE is not implemented. I'll get on it.

**Comment by zuckschwerdt** [comment]
The `-R sr` is an error, only int's are possible. Maybe you wanted `-r sr`?
`OOK_PWM_PRECISE` is now implemented and should work.
```
rtl_433 -F json -R 0 -X "sr:OOK_PWM_PRECISE:54:167:1750:100" -r sr
```
(additional `:tolerance[:syncwidth]` there, see `-X help` for more.)

**Comment by Habbie** [comment]
> The -R sr is an error, only int's are possible. Maybe you wanted -r sr?

ah, unclear from the help text. I just wanted to disable all provided decoders.

**Comment by zuckschwerdt** [comment]
Then it will work as expected :) `-R sr` is equivalent to `-R 0` and disables all decoders.

**Pull request merged**
