### PR TITLE
Add Holman WS5029 decoder

### PR DESCRIPTION
**Pull request by rmounce**
Also see samples and tests: https://github.com/merbanan/rtl_433_tests/pull/295

### CODE REVIEW

**Comment by merbanan** [comment]
Looks real good. Can you post a few bitbuffers so we can take a brief look at the checksum?

**Comment by merbanan** [comment]
It might be reverse Dallas One-wire CRC.

crc8(br, 11, 0x31, 0xff)
or
crc8(br, 8, 0x31, 0xff)

**Comment by rmounce** [comment]
`rtl_433 -R 0 -X 'name=WS5029,modulation=FSK_PCM,short=100,long=100,preamble={48}0xAAAAAAAAAAAA,reset=19200' -r rtl_433_tests/tests/holman_ws5029/01/*.cu8`
```
98f3a5d2010a030001018000000000ba08000
98f3a5d201f7323001000000000000b708000
```
And some more
```
98f3a54d080a12f000007000000000ad07000
98f3a54d080a22f0000070000000009d07000
98f3a5d20108e390010000000000001908000
98f3a5d2010893d0010000000000002908000
```
I tried Dallas one-wire CRC based on the implementation at https://forum.arduino.cc/index.php?topic=37648.0 and was successful on my first attempt... by sheer chance.

**Comment by merbanan** [comment]
So where you able to add the crc check? It is a bit unclear from the text.

**Comment by rmounce** [comment]
I wasn't successful - as far as I can tell it isn't Dallas one-wire CRC.

**Comment by merbanan** [comment]
We'll have to sort out the CRC later.

**Comment by zuckschwerdt** [comment]
Doesn't look like enough entropy for a CRC. The lower bits look like XOR, the upper somewhat like a sum. Maybe an Adler/Fletcher type of check.
@rmounce Can you collect more code lines?

**Comment by rmounce** [comment]
Here are all of the unique samples I have
https://gist.github.com/rmounce/b8b3f3849d78393066c4c232b1e87331

**Comment by merbanan** [comment]
98f3a5d20106a4d001000000000000a008000 - 6a4 - a -> a^a=0
98f3a5d20106e4d001000000000000e008000 - 6e4 - e -> e^e=0

98f3a54d080a12f000007000000000ad07000 - a12 - a -> 1^a=b
98f3a54d080a22f0000070000000009d07000 - a22 - 9 -> 2^9=b

98f3a5d201fb220001000000000000db08000 - b22 - d -> 2^d=f
98f3a5d201fbe200010000000000001b08000 - be2 - 1 -> e^1=f

98f3a5d2010574e0010000000000001308000 - 574 - 1 -> 7^1=6
98f3a5d20105e4e0010000000000008308000 - 5e4 - 8 -> e^8=6

**Comment by merbanan** [comment]
98 f3 a5 d2 01 08 c3 b0 01 00 00 00 00 00 00 19 08000
98 f3 a5 d2 01 08 d3 a0 01 00 00 00 00 00 00 19 08000
98 f3 a5 d2 01 08 e3 90 01 00 00 00 00 00 00 19 08000
c^b == d^a == e^9 = 7

So there is a linear relation
98 f3 a5 d2 01 08 73 e0 01 00 00 00 00 00 00 f9 08000
7^e^f == c^b^1

and
98 f3 a5 d2 01 08 [c3 b0 01 00 00] 00 00 00 00 (1)9 08000
98 f3 a5 d2 01 0a [03 00 00 03 20] 00 00 00 00 (4)9 06000
2^4 == c^b^1 = 6

So this range seem to be valid. Maybe the XORsum should result in a constant.

If we look at the low nibble 8^3^1 == a^3^3 so this is linear also. Most likely the same.
XORSUM(98 f3 a5 d2 01 0a [03 00 00 03 20] 00 00 00 00 (4)9) = 7E
XORSUM(98 f3 a5 d2 01 08 [c3 b0 01 00 00] 00 00 00 00 (1)9) = 7E

but with the following payload:
XORSUM(98 f3 a5 4d 08 0a 12 f0 00 00 70 00 00 00 00 ad) = BE

it doesn't match. So something is still missing.

**Comment by zuckschwerdt** [comment]
Note: This seems to be a newer version with PCM modulation.
See #947 for the older version with PWM modulation.

**Pull request merged**
