### PR TITLE
Add generic list type

### PR DESCRIPTION
**Pull request by zuckschwerdt**
Adds a resizing generic list type and replaces fixed length list

### CODE REVIEW

**Comment by winterrace** [comment]
Looks well, compiles well, runs well :)
My vote is yours :)

**Comment by klohner** [comment]
Under MinGW-w64, getting `Registered zu out of 96 device decoding protocols` in output.  MinGW-w64 doesn't seem to like `%zu` format in `fprintf(stderr, "Registered %zu out of %d device decoding protocols",` by default.

Possible remediation tips here: (https://stackoverflow.com/questions/25670522/c-program-shows-zu-after-conversion-to-windows)

**Comment by klohner** [comment]
As explained at [#377 C library bug: Modifiers %jd %ju %zu not working](https://sourceforge.net/p/mingw-w64/wiki2/gnu%20printf/), I was able to add `#define __USE_MINGW_ANSI_STDIO 1` before including stdio.h to mitigate this.

**Comment by klohner** [comment]
Perhaps not?  I just made a fresh build in Windows and was getting the `Registered zu out of 96 device decoding protocols`

**Comment by zuckschwerdt** [comment]
Of course you are right :) https://github.com/merbanan/rtl_433/blob/master/src/rtl_433.c#L1543 I'll fix that.

**Pull request merged**
