### PR TITLE
Replace CRC implementation

### PR DESCRIPTION
**Pull request by emontnemery**
The CRC algorithm is in fact standard CRC-8 with parameters:
width=8  poly=0x31  init=0x6c  refin=false  refout=false  xorout=0x00

Update rubicson.c to reflect this.

This was simple to find by using this excellent tool: http://reveng.sourceforge.net/

### CODE REVIEW

**Comment by merbanan** [comment]
I never got my head around how to do bit wise crc. I assume the patch is correct.

**Comment by merbanan** [comment]
bb[1] is the first repeat of the message, because of demodulator quirks one bit might be dropped in the initial message (bb[0]). That was the reason initially, things might have changed. Dumping all repeats might show this.

Anyway in theory all copies (initial and the repeats) of the message should be the same (signal collisions make that ). We should use the repeats to validate messages better. But if a protocol has a crc we only need to verify that once to be pretty sure that the message is valid.

For protocols without crc we should/could use the repeats to validate the transmission better. We could also repair bit errors with the help of repeats. But no one has derived the classification process for this. The 433MHz band has lots of collisions so another sensor reading will be transmitted later anyway. It is ok to miss a few.

But feel free to work on it if you want.

**Comment by emontnemery** [comment]
@merbanan OK, but then bb[1] should actually be used both for CRC check and data extraction?
For 8-bit CRC there's of course a 1/256 chance of matching CRC when receiving broken data, so it would make sense to check the buffer for 1-2 repetitions as well?

**Comment by merbanan** [comment]
Yes and yes. I think there is a function that can validate several rows.

**Comment by zuckschwerdt** [comment]
It looks like Rubicson and Solight are the same type of transmitter (or even sensor). I need to take a closer look but we should combine the files and unifiy where possible (as you already did with the CRC).

**Pull request merged**
