### PR TITLE
Add support for HCS200 KeeLoq encoder

### PR DESCRIPTION
**Pull request by 667bdrm**
Added Microchip HCS200 based remotes decoder

Sample data: https://github.com/merbanan/rtl_433_tests/pull/287

### CODE REVIEW

**Comment by zuckschwerdt** [comment]
Looks good, thanks.
- Is `serial` unique per device, then it should be `id`. Or is it some kind of message "counter"?
- The `battery` key should be `battery_ok` with an `int`value.
- `(b[1] << 24)` should be `((unsigned)b[1] << 24)` (others are fine as-is)
- For `serial` reduce every shift by 4 there and don't shift and mask "at the end"
- Both `%04X` overflow and should be `%08X`
- Please use 4 spaces as indent
- Continued lines (after data_make, output_fields, r_device) should have two indents
- Add a trailing comma after that last field in output_fields and r_device

**Comment by 667bdrm** [comment]
> Is serial unique per device, then it should be id. Or is it some kind of message "counter"?

Yes, it should be unique id

> For serial reduce every shift by 4 there and don't shift and mask "at the end"

If I do so there will be data from the battery status byte. Per datasheet page 8 there are 28 bit serial field and there are button status data next ` >> 4`at the end is used to cut off this, `& 0x0fffffff` is used to remove 0xf from the beginning.

**Comment by zuckschwerdt** [comment]
The `& 0x0F` should probably be `& 0xF0`, because the former with `>>4` is effectivly `& 0x00`
I.e. you actually want `(b[5] << 20) | (b[6] << 12) | (b[7] << 4) | (b[8] >> 4)`, right?

**Comment by 667bdrm** [comment]
Yes, it is. The serial (id) decoding now the same for the test data.

**Comment by zuckschwerdt** [comment]
Can you add the GPL notice like in other decoders, if that license is okay with you?

**Comment by 667bdrm** [comment]
Yes, sure. GPL is ok.

**Comment by merbanan** [comment]
@zuckschwerdt can we merge this? Code looks clean.

**Comment by zuckschwerdt** [comment]
Needs a rebase but otherwise good to merge!

**Comment by nunojpg** [comment]
@667bdrm why are you looking for buttons at b[8] == 2,4,6,9? My Remote (Gibidi) uses 1,2,3,4. Maybe this is a artifact of some changes done in the value content? With current master I definitely only get button 1 and button 2 to show as ON, button 3 and 4 alias to button 2, and I checked athat b[8] becomes 1,2,3,4.

**Comment by zuckschwerdt** [comment]
See #1512 for a discussion on relabeling the buttons to fit the protocol description.

**Pull request merged**
