### PR TITLE
Added Chinese lamp remote based on 226x encoder

### PR DESCRIPTION
**Pull request by yshestakov**
Added Chinese lamp remote based on 226x encoder and working on @ 913.3MHz

### CODE REVIEW

**Comment by merbanan** [comment]
Can you send some sample signals for this remote ?

**Comment by yshestakov** [comment]
I've captured some signals for the given "Chinese lamp" remote based on 2262 encoder:
  https://www.dropbox.com/s/4dfwoj1uiywbn0b/ch_lamp_remote_913_23MHz_gdata.zip?dl=0

Also there is screen capture of spectrum / waterfall for this remote made in GQRX:  https://www.dropbox.com/s/2d8i8bd742xou9n/rf%20spectre%20913.25.png?dl=0

and some text notes I made when tried to patch "generic_remote.c" driver:
   https://www.dropbox.com/s/o4bwuxk91u9tx7f/lamp_913_25MHz.txt?dl=0

**Comment by yshestakov** [comment]
BTW, today I got EV1527 encoder based 433.92MHz  outlet remote control from AliExpress: https://goo.gl/OqotQD

It was not recognized by "generic_remote.c" driver until I made small patch: https://pastebin.com/wDQKm4kA

I can capture signals and share with you if you're interested

**Comment by merbanan** [comment]
Can you send a pull request with the signals to the rtl_433_tests repository ?

**Comment by zuckschwerdt** [comment]
Support for e.g. buttons, PIR, … is now easily done with flex and a conf file. See the provided [rtl_433.example.conf](https://github.com/merbanan/rtl_433/blob/master/rtl_433.example.conf) for hints.

**Pull request closed without merging**
