### PR TITLE
WIP code of new fsk demod

### PR DESCRIPTION
**Pull request by merbanan**
Test code for new fsk demod

### CODE REVIEW

**Comment by merbanan** [comment]
This code works for a few sample files. Real of the air readings has not yet been done.

**Comment by merbanan** [comment]
Seems to actually perform ok over the air.

src/rtl_433 -s 1000k -A -g 30 -f 868800k -v -v -v

Shows quite stable pulse readings. The beginning and end has significant period differences. But in the middle there is very little jitter:

Analyzing pulses...
Total count:  394,  width: 12.81 ms		(12812 S)
Pulse width distribution:
 [ 0] count:    1,  width:    0 us [0;0]	(   0 S)
 [ 1] count:  191,  width:    9 us [9;11]	(   9 S)
 [ 2] count:    4,  width:   40 us [40;40]	(  40 S)
 [ 3] count:  160,  width:   19 us [19;21]	(  19 S)
 [ 4] count:   38,  width:   29 us [25;31]	(  29 S)
Gap width distribution:
 [ 0] count:  213,  width:   10 us [9;13]	(  10 S)
 [ 1] count:  122,  width:   20 us [19;21]	(  20 S)
 [ 2] count:    9,  width:   40 us [39;41]	(  40 S)
 [ 3] count:   49,  width:   30 us [30;31]	(  30 S)
Pulse period distribution:
 [ 0] count:    1,  width:   13 us [13;13]	(  13 S)
 [ 1] count:  120,  width:   20 us [19;21]	(  20 S)
 [ 2] count:  140,  width:   30 us [29;31]	(  30 S)
 [ 3] count:   61,  width:   51 us [41;61]	(  51 S)
 [ 4] count:   65,  width:   39 us [39;40]	(  39 S)
 [ 5] count:    6,  width:   70 us [70;70]	(  70 S)


Pulse data: 394 pulses
[  0] Pulse:    0, Gap:   13, Period:   13
[  1] Pulse:   10, Gap:   10, Period:   20
[  2] Pulse:   10, Gap:   10, Period:   20
[  3] Pulse:   10, Gap:   10, Period:   20
[  4] Pulse:   10, Gap:   10, Period:   20
[  5] Pulse:   10, Gap:   10, Period:   20
[  6] Pulse:   10, Gap:   10, Period:   20
[  7] Pulse:   10, Gap:   20, Period:   30
[  8] Pulse:   10, Gap:   10, Period:   20
[  9] Pulse:   10, Gap:   10, Period:   20
[ 10] Pulse:   10, Gap:   10, Period:   20
[ 11] Pulse:   10, Gap:   10, Period:   20
[ 12] Pulse:   11, Gap:    9, Period:   20
[ 13] Pulse:   10, Gap:   10, Period:   20
[ 14] Pulse:   11, Gap:    9, Period:   20
[ 15] Pulse:   11, Gap:   10, Period:   21
[ 16] Pulse:   10, Gap:   10, Period:   20
[ 17] Pulse:   10, Gap:   10, Period:   20
[ 18] Pulse:   10, Gap:   10, Period:   20
[ 19] Pulse:   10, Gap:   10, Period:   20
[ 20] Pulse:   10, Gap:   10, Period:   20
[ 21] Pulse:   10, Gap:   10, Period:   20
[ 22] Pulse:   10, Gap:   10, Period:   20
[ 23] Pulse:   10, Gap:   10, Period:   20
[ 24] Pulse:   10, Gap:   10, Period:   20
[ 25] Pulse:   10, Gap:   10, Period:   20
[ 26] Pulse:   10, Gap:   10, Period:   20
[ 27] Pulse:   10, Gap:   10, Period:   20
[ 28] Pulse:   10, Gap:   10, Period:   20
[ 29] Pulse:   10, Gap:   10, Period:   20
[ 30] Pulse:   10, Gap:   40, Period:   50
[ 31] Pulse:   40, Gap:   10, Period:   50
[ 32] Pulse:   10, Gap:   10, Period:   20
[ 33] Pulse:   20, Gap:   20, Period:   40
[ 34] Pulse:   10, Gap:   10, Period:   20
[ 35] Pulse:   10, Gap:   20, Period:   30
[ 36] Pulse:   20, Gap:   10, Period:   30
[ 37] Pulse:   30, Gap:   30, Period:   60
[ 38] Pulse:   30, Gap:   20, Period:   50
[ 39] Pulse:   10, Gap:   30, Period:   40
[ 40] Pulse:   20, Gap:   10, Period:   30
[ 41] Pulse:   30, Gap:   30, Period:   60
[ 42] Pulse:   10, Gap:   10, Period:   20
[ 43] Pulse:   20, Gap:   10, Period:   30
[ 44] Pulse:   10, Gap:   20, Period:   30
[ 45] Pulse:   10, Gap:   10, Period:   20
[ 46] Pulse:   10, Gap:   10, Period:   20
[ 47] Pulse:   10, Gap:   20, Period:   30
[ 48] Pulse:   30, Gap:   20, Period:   50
[ 49] Pulse:   10, Gap:   10, Period:   20
[ 50] Pulse:   10, Gap:   20, Period:   30
[ 51] Pulse:   30, Gap:   30, Period:   60
[ 52] Pulse:   20, Gap:   10, Period:   30
[ 53] Pulse:   10, Gap:   10, Period:   20
[ 54] Pulse:   10, Gap:   20, Period:   30
[ 55] Pulse:   20, Gap:   10, Period:   30
[ 56] Pulse:   10, Gap:   10, Period:   20
[ 57] Pulse:   20, Gap:   30, Period:   50
[ 58] Pulse:   20, Gap:   10, Period:   30
[ 59] Pulse:   10, Gap:   10, Period:   20
[ 60] Pulse:   20, Gap:   10, Period:   30
[ 61] Pulse:   10, Gap:   30, Period:   40
[ 62] Pulse:   20, Gap:   10, Period:   30
[ 63] Pulse:   10, Gap:   10, Period:   20
[ 64] Pulse:   10, Gap:   10, Period:   20
[ 65] Pulse:   20, Gap:   30, Period:   50
[ 66] Pulse:   20, Gap:   10, Period:   30
[ 67] Pulse:   20, Gap:   30, Period:   50
[ 68] Pulse:   20, Gap:   10, Period:   30
[ 69] Pulse:   20, Gap:   20, Period:   40
[ 70] Pulse:   20, Gap:   30, Period:   50
[ 71] Pulse:   20, Gap:   20, Period:   40
[ 72] Pulse:   20, Gap:   10, Period:   30
[ 73] Pulse:   10, Gap:   20, Period:   30
[ 74] Pulse:   20, Gap:   10, Period:   30
[ 75] Pulse:   10, Gap:   10, Period:   20
[ 76] Pulse:   10, Gap:   20, Period:   30
[ 77] Pulse:   30, Gap:   20, Period:   50
[ 78] Pulse:   20, Gap:   10, Period:   30
[ 79] Pulse:   10, Gap:   20, Period:   30
[ 80] Pulse:   10, Gap:   10, Period:   20
[ 81] Pulse:   10, Gap:   20, Period:   30
[ 82] Pulse:   10, Gap:   10, Period:   20
[ 83] Pulse:   20, Gap:   10, Period:   30
[ 84] Pulse:   10, Gap:   10, Period:   20
[ 85] Pulse:   20, Gap:   10, Period:   30
[ 86] Pulse:   10, Gap:   10, Period:   20
[ 87] Pulse:   20, Gap:   30, Period:   50
[ 88] Pulse:   10, Gap:   10, Period:   20
[ 89] Pulse:   20, Gap:   20, Period:   40
[ 90] Pulse:   10, Gap:   10, Period:   20
[ 91] Pulse:   20, Gap:   20, Period:   40
[ 92] Pulse:   10, Gap:   10, Period:   20
[ 93] Pulse:   20, Gap:   20, Period:   40
[ 94] Pulse:   10, Gap:   10, Period:   20
[ 95] Pulse:   20, Gap:   20, Period:   40
[ 96] Pulse:   10, Gap:   10, Period:   20
[ 97] Pulse:   20, Gap:   30, Period:   50
[ 98] Pulse:   30, Gap:   20, Period:   50
[ 99] Pulse:   20, Gap:   10, Period:   30
[100] Pulse:   10, Gap:   20, Period:   30
[101] Pulse:   20, Gap:   20, Period:   40
[102] Pulse:   10, Gap:   10, Period:   20
[103] Pulse:   30, Gap:   20, Period:   50
[104] Pulse:   10, Gap:   20, Period:   30
[105] Pulse:   10, Gap:   10, Period:   20
[106] Pulse:   10, Gap:   10, Period:   20
[107] Pulse:   10, Gap:   10, Period:   20
[108] Pulse:   20, Gap:   10, Period:   30
[109] Pulse:   10, Gap:   20, Period:   30
[110] Pulse:   11, Gap:    9, Period:   20
[111] Pulse:   11, Gap:    9, Period:   20
[112] Pulse:   31, Gap:   39, Period:   70
[113] Pulse:   31, Gap:   19, Period:   50
[114] Pulse:   21, Gap:    9, Period:   30
[115] Pulse:   11, Gap:   20, Period:   31
[116] Pulse:   20, Gap:   20, Period:   40
[117] Pulse:   10, Gap:   20, Period:   30
[118] Pulse:   30, Gap:   10, Period:   40
[119] Pulse:    9, Gap:   11, Period:   20
[120] Pulse:    9, Gap:   21, Period:   30
[121] Pulse:    9, Gap:   11, Period:   20
[122] Pulse:    9, Gap:   11, Period:   20
[123] Pulse:   19, Gap:   11, Period:   30
[124] Pulse:    9, Gap:   21, Period:   30
[125] Pulse:    9, Gap:   11, Period:   20
[126] Pulse:   19, Gap:   11, Period:   30
[127] Pulse:   19, Gap:   40, Period:   59
[128] Pulse:   30, Gap:   20, Period:   50
[129] Pulse:   10, Gap:   10, Period:   20
[130] Pulse:   20, Gap:   30, Period:   50
[131] Pulse:   20, Gap:   10, Period:   30
[132] Pulse:   10, Gap:   10, Period:   20
[133] Pulse:   20, Gap:   10, Period:   30
[134] Pulse:   10, Gap:   20, Period:   30
[135] Pulse:   20, Gap:   20, Period:   40
[136] Pulse:   10, Gap:   21, Period:   31
[137] Pulse:   29, Gap:   10, Period:   39
[138] Pulse:   10, Gap:   11, Period:   21
[139] Pulse:   19, Gap:   31, Period:   50
[140] Pulse:   29, Gap:   41, Period:   70
[141] Pulse:   20, Gap:   10, Period:   30
[142] Pulse:   20, Gap:   30, Period:   50
[143] Pulse:   40, Gap:   30, Period:   70
[144] Pulse:   10, Gap:   10, Period:   20
[145] Pulse:   10, Gap:   10, Period:   20
[146] Pulse:   20, Gap:   10, Period:   30
[147] Pulse:   10, Gap:   10, Period:   20
[148] Pulse:   20, Gap:   40, Period:   60
[149] Pulse:   30, Gap:   30, Period:   60
[150] Pulse:   30, Gap:   20, Period:   50
[151] Pulse:   20, Gap:   10, Period:   30
[152] Pulse:   10, Gap:   20, Period:   30
[153] Pulse:   20, Gap:   20, Period:   40
[154] Pulse:   10, Gap:   20, Period:   30
[155] Pulse:   20, Gap:   10, Period:   30
[156] Pulse:   20, Gap:   30, Period:   50
[157] Pulse:   20, Gap:   10, Period:   30
[158] Pulse:   10, Gap:   10, Period:   20
[159] Pulse:   20, Gap:   10, Period:   30
[160] Pulse:   10, Gap:   20, Period:   30
[161] Pulse:   10, Gap:   10, Period:   20
[162] Pulse:   10, Gap:   20, Period:   30
[163] Pulse:   20, Gap:   10, Period:   30
[164] Pulse:   10, Gap:   20, Period:   30
[165] Pulse:   30, Gap:   20, Period:   50
[166] Pulse:   20, Gap:   10, Period:   30
[167] Pulse:   10, Gap:   20, Period:   30
[168] Pulse:   20, Gap:   20, Period:   40
[169] Pulse:   10, Gap:   10, Period:   20
[170] Pulse:   30, Gap:   40, Period:   70
[171] Pulse:   20, Gap:   10, Period:   30
[172] Pulse:   10, Gap:   10, Period:   20
[173] Pulse:   10, Gap:   10, Period:   20
[174] Pulse:   20, Gap:   10, Period:   30
[175] Pulse:   10, Gap:   20, Period:   30
[176] Pulse:   10, Gap:   10, Period:   20
[177] Pulse:   10, Gap:   10, Period:   20
[178] Pulse:   20, Gap:   10, Period:   30
[179] Pulse:   10, Gap:   30, Period:   40
[180] Pulse:   30, Gap:   20, Period:   50
[181] Pulse:   20, Gap:   10, Period:   30
[182] Pulse:   10, Gap:   20, Period:   30
[183] Pulse:   20, Gap:   20, Period:   40
[184] Pulse:   10, Gap:   10, Period:   20
[185] Pulse:   20, Gap:   10, Period:   30
[186] Pulse:   10, Gap:   20, Period:   30
[187] Pulse:   20, Gap:   20, Period:   40
[188] Pulse:   10, Gap:   10, Period:   20
[189] Pulse:   10, Gap:   10, Period:   20
[190] Pulse:   20, Gap:   10, Period:   30
[191] Pulse:   10, Gap:   10, Period:   20
[192] Pulse:   20, Gap:   30, Period:   50
[193] Pulse:   20, Gap:   20, Period:   40
[194] Pulse:   10, Gap:   20, Period:   30
[195] Pulse:   30, Gap:   20, Period:   50
[196] Pulse:   20, Gap:   10, Period:   30
[197] Pulse:   10, Gap:   20, Period:   30
[198] Pulse:   20, Gap:   20, Period:   40
[199] Pulse:   20, Gap:   20, Period:   40
[200] Pulse:   20, Gap:   10, Period:   30
[201] Pulse:   10, Gap:   20, Period:   30
[202] Pulse:   20, Gap:   10, Period:   30
[203] Pulse:   10, Gap:   10, Period:   20
[204] Pulse:   20, Gap:   30, Period:   50
[205] Pulse:   30, Gap:   30, Period:   60
[206] Pulse:   20, Gap:   20, Period:   40
[207] Pulse:   10, Gap:   10, Period:   20
[208] Pulse:   20, Gap:   10, Period:   30
[209] Pulse:   10, Gap:   20, Period:   30
[210] Pulse:   10, Gap:   10, Period:   20
[211] Pulse:   20, Gap:   10, Period:   30
[212] Pulse:   10, Gap:   20, Period:   30
[213] Pulse:   10, Gap:   10, Period:   20
[214] Pulse:   10, Gap:   10, Period:   20
[215] Pulse:   10, Gap:   10, Period:   20
[216] Pulse:   20, Gap:   30, Period:   50
[217] Pulse:   30, Gap:   10, Period:   40
[218] Pulse:   10, Gap:   10, Period:   20
[219] Pulse:   10, Gap:   20, Period:   30
[220] Pulse:   20, Gap:   30, Period:   50
[221] Pulse:   21, Gap:   19, Period:   40
[222] Pulse:   21, Gap:    9, Period:   30
[223] Pulse:   21, Gap:   19, Period:   40
[224] Pulse:   21, Gap:    9, Period:   30
[225] Pulse:   11, Gap:    9, Period:   20
[226] Pulse:   21, Gap:   30, Period:   51
[227] Pulse:    9, Gap:   21, Period:   30
[228] Pulse:   20, Gap:   10, Period:   30
[229] Pulse:   10, Gap:   10, Period:   20
[230] Pulse:   20, Gap:   30, Period:   50
[231] Pulse:   19, Gap:   11, Period:   30
[232] Pulse:    9, Gap:   11, Period:   20
[233] Pulse:   29, Gap:   41, Period:   70
[234] Pulse:   29, Gap:   11, Period:   40
[235] Pulse:    9, Gap:   11, Period:   20
[236] Pulse:    9, Gap:   20, Period:   29
[237] Pulse:   20, Gap:   30, Period:   50
[238] Pulse:   20, Gap:   20, Period:   40
[239] Pulse:   20, Gap:   10, Period:   30
[240] Pulse:   20, Gap:   20, Period:   40
[241] Pulse:   20, Gap:   10, Period:   30
[242] Pulse:   10, Gap:   20, Period:   30
[243] Pulse:   10, Gap:   10, Period:   20
[244] Pulse:   10, Gap:   20, Period:   30
[245] Pulse:   10, Gap:   10, Period:   20
[246] Pulse:   20, Gap:   10, Period:   30
[247] Pulse:   11, Gap:    9, Period:   20
[248] Pulse:   21, Gap:   30, Period:   51
[249] Pulse:   19, Gap:   11, Period:   30
[250] Pulse:   20, Gap:   10, Period:   30
[251] Pulse:   19, Gap:   41, Period:   60
[252] Pulse:   30, Gap:   20, Period:   50
[253] Pulse:   10, Gap:   10, Period:   20
[254] Pulse:   20, Gap:   30, Period:   50
[255] Pulse:   20, Gap:   10, Period:   30
[256] Pulse:   20, Gap:   10, Period:   30
[257] Pulse:   10, Gap:   20, Period:   30
[258] Pulse:   20, Gap:   30, Period:   50
[259] Pulse:   20, Gap:   20, Period:   40
[260] Pulse:   20, Gap:   10, Period:   30
[261] Pulse:   20, Gap:   20, Period:   40
[262] Pulse:   20, Gap:   10, Period:   30
[263] Pulse:   10, Gap:   10, Period:   20
[264] Pulse:   20, Gap:   20, Period:   40
[265] Pulse:   20, Gap:   20, Period:   40
[266] Pulse:   10, Gap:   30, Period:   40
[267] Pulse:   30, Gap:   10, Period:   40
[268] Pulse:   20, Gap:   20, Period:   40
[269] Pulse:   10, Gap:   10, Period:   20
[270] Pulse:   10, Gap:   30, Period:   40
[271] Pulse:   40, Gap:   30, Period:   70
[272] Pulse:   10, Gap:   10, Period:   20
[273] Pulse:   10, Gap:   10, Period:   20
[274] Pulse:   20, Gap:   30, Period:   50
[275] Pulse:   20, Gap:   10, Period:   30
[276] Pulse:   10, Gap:   20, Period:   30
[277] Pulse:   30, Gap:   30, Period:   60
[278] Pulse:   30, Gap:   10, Period:   40
[279] Pulse:   10, Gap:   10, Period:   20
[280] Pulse:   10, Gap:   20, Period:   30
[281] Pulse:   20, Gap:   30, Period:   50
[282] Pulse:   20, Gap:   20, Period:   40
[283] Pulse:   20, Gap:   10, Period:   30
[284] Pulse:   20, Gap:   20, Period:   40
[285] Pulse:   20, Gap:   10, Period:   30
[286] Pulse:   10, Gap:   10, Period:   20
[287] Pulse:   20, Gap:   20, Period:   40
[288] Pulse:   20, Gap:   20, Period:   40
[289] Pulse:   10, Gap:   20, Period:   30
[290] Pulse:   10, Gap:   10, Period:   20
[291] Pulse:   20, Gap:   30, Period:   50
[292] Pulse:   20, Gap:   10, Period:   30
[293] Pulse:   10, Gap:   20, Period:   30
[294] Pulse:   20, Gap:   10, Period:   30
[295] Pulse:   10, Gap:   20, Period:   30
[296] Pulse:   30, Gap:   10, Period:   40
[297] Pulse:   10, Gap:   10, Period:   20
[298] Pulse:   10, Gap:   20, Period:   30
[299] Pulse:   20, Gap:   30, Period:   50
[300] Pulse:   20, Gap:   20, Period:   40
[301] Pulse:   20, Gap:   10, Period:   30
[302] Pulse:   20, Gap:   20, Period:   40
[303] Pulse:   20, Gap:   10, Period:   30
[304] Pulse:   10, Gap:   20, Period:   30
[305] Pulse:   10, Gap:   10, Period:   20
[306] Pulse:   10, Gap:   10, Period:   20
[307] Pulse:   20, Gap:   10, Period:   30
[308] Pulse:   10, Gap:   20, Period:   30
[309] Pulse:   10, Gap:   10, Period:   20
[310] Pulse:   20, Gap:   31, Period:   51
[311] Pulse:   19, Gap:   10, Period:   29
[312] Pulse:   10, Gap:   10, Period:   20
[313] Pulse:   20, Gap:   10, Period:   30
[314] Pulse:   10, Gap:   30, Period:   40
[315] Pulse:   30, Gap:   10, Period:   40
[316] Pulse:   10, Gap:   10, Period:   20
[317] Pulse:   10, Gap:   20, Period:   30
[318] Pulse:   20, Gap:   30, Period:   50
[319] Pulse:   20, Gap:   20, Period:   40
[320] Pulse:   20, Gap:   10, Period:   30
[321] Pulse:   20, Gap:   20, Period:   40
[322] Pulse:   20, Gap:   10, Period:   30
[323] Pulse:   10, Gap:   20, Period:   30
[324] Pulse:   20, Gap:   30, Period:   50
[325] Pulse:   30, Gap:   10, Period:   40
[326] Pulse:   10, Gap:   10, Period:   20
[327] Pulse:   10, Gap:   20, Period:   30
[328] Pulse:   30, Gap:   20, Period:   50
[329] Pulse:   10, Gap:   20, Period:   30
[330] Pulse:   11, Gap:   19, Period:   30
[331] Pulse:   31, Gap:   30, Period:   61
[332] Pulse:   19, Gap:   10, Period:   29
[333] Pulse:   11, Gap:    9, Period:   20
[334] Pulse:   21, Gap:   30, Period:   51
[335] Pulse:   20, Gap:   10, Period:   30
[336] Pulse:   10, Gap:   10, Period:   20
[337] Pulse:   20, Gap:   20, Period:   40
[338] Pulse:    9, Gap:   21, Period:   30
[339] Pulse:   30, Gap:   10, Period:   40
[340] Pulse:    9, Gap:   11, Period:   20
[341] Pulse:    9, Gap:   21, Period:   30
[342] Pulse:   19, Gap:   31, Period:   50
[343] Pulse:   19, Gap:   20, Period:   39
[344] Pulse:   20, Gap:   11, Period:   31
[345] Pulse:   19, Gap:   20, Period:   39
[346] Pulse:   20, Gap:   10, Period:   30
[347] Pulse:   20, Gap:   20, Period:   40
[348] Pulse:   10, Gap:   10, Period:   20
[349] Pulse:   20, Gap:   10, Period:   30
[350] Pulse:   10, Gap:   30, Period:   40
[351] Pulse:   10, Gap:   10, Period:   20
[352] Pulse:   20, Gap:   30, Period:   50
[353] Pulse:   20, Gap:   10, Period:   30
[354] Pulse:   10, Gap:   11, Period:   21
[355] Pulse:    9, Gap:   10, Period:   19
[356] Pulse:   20, Gap:   21, Period:   41
[357] Pulse:   20, Gap:   10, Period:   30
[358] Pulse:    9, Gap:   21, Period:   30
[359] Pulse:   20, Gap:   10, Period:   30
[360] Pulse:   10, Gap:   10, Period:   20
[361] Pulse:   20, Gap:   30, Period:   50
[362] Pulse:   10, Gap:   20, Period:   30
[363] Pulse:   10, Gap:   10, Period:   20
[364] Pulse:   30, Gap:   30, Period:   60
[365] Pulse:   20, Gap:   20, Period:   40
[366] Pulse:   30, Gap:   20, Period:   50
[367] Pulse:   10, Gap:   20, Period:   30
[368] Pulse:   40, Gap:   10, Period:   50
[369] Pulse:   10, Gap:   20, Period:   30
[370] Pulse:   20, Gap:   20, Period:   40
[371] Pulse:   10, Gap:   20, Period:   30
[372] Pulse:   20, Gap:   10, Period:   30
[373] Pulse:   10, Gap:   10, Period:   20
[374] Pulse:   20, Gap:   10, Period:   30
[375] Pulse:   10, Gap:   40, Period:   50
[376] Pulse:   30, Gap:   10, Period:   40
[377] Pulse:   10, Gap:   20, Period:   30
[378] Pulse:   20, Gap:   20, Period:   40
[379] Pulse:   10, Gap:   10, Period:   20
[380] Pulse:   20, Gap:   20, Period:   40
[381] Pulse:   10, Gap:   10, Period:   20
[382] Pulse:   20, Gap:   20, Period:   40
[383] Pulse:   10, Gap:   20, Period:   30
[384] Pulse:   20, Gap:   10, Period:   30
[385] Pulse:   20, Gap:   10, Period:   30
[386] Pulse:   10, Gap:   30, Period:   40
[387] Pulse:   20, Gap:   10, Period:   30
[388] Pulse:   20, Gap:   20, Period:   40
[389] Pulse:   20, Gap:   20, Period:   40
[390] Pulse:   10, Gap:   10, Period:   20
[391] Pulse:   10, Gap:   10, Period:   20
[392] Pulse:   10, Gap:   10, Period:   20
[393] Pulse:   25, Gap:   13, Period:   38

**Comment by merbanan** [comment]
IKEA sparsnäs worked out of the box with the new code.

**Comment by reaper7** [comment]
https://github.com/merbanan/rtl_433/issues/617#issuecomment-541514488

**Comment by merbanan** [comment]
The code needs to be reworked so that decoders can specify a specific demodulator/bit-slicer chain. Enabled decoders should in turn enable the chain they need. That way a user can request just the needed code to be run.

**Comment by reaper7** [comment]
with this patch it reads two acurite sensors and of course m-bus meters :)

**Comment by reaper7** [comment]
something is wrong...
received frame indicates length (first byte) as 0x4e -> 78bytes
but real length received frames ranges from 91 to 92bytes (random)

the initial bytes look good...
but after Meter version(byte) and Device type(byte), in my case "water" 
I get two additional bytes, which I didn't have in rtl_wmbus...
maybe it's a checksum I should skip???

and next, now correctly:
Control Information  (0x7a), Access code etc
although the frame is still too long

**Comment by merbanan** [comment]
The on the air payload contains more data then the mbus header reads.

The 2 values you talk about is the CRC. I will probably skip outputting them later in the output message because if the crc is invalid there wont be any message anyway.

At the end there might be some noise (random data). But in the mbus case this does not matter as the payload has a well defined structure that will disregard extra bits.

**Comment by merbanan** [comment]
The initial response and tests with the new code has given some insight how to go forward with the new logic. As always it will take some time but at least there is code to play with.

**Comment by merbanan** [comment]
@reaper7 0x7a is a good value.

The feat-fsk_demod_new_test branch has some mode mbus code. You can try it if you want.

**Comment by reaper7** [comment]
0x7a yes, but the previous two bytes do not occur in rtl_wmbus reply...

I am very glad that you took care of this.
I don't expect it to work right now :) do you remember when I reported the problem...
..so, I am available, I can test and report bugs

**Comment by merbanan** [comment]
New pulse detector merged. Closing this PR.

**Pull request closed without merging**
