### PR TITLE
Add Support for Ecowitt WN34D and improve FineOffset WN34

### PR DESCRIPTION
**Pull request by ProfBoc75**
Related to issue #2943 

Update the existing decoder to take into account this model WN34D, temperature without offset.
Few document updates and improvement.

### CODE REVIEW

**Comment by zuckschwerdt** [comment]
I think `subtype` might be a good choice here as it is a different "function" (coding of the value) in the same protocol.
But this will be a breaking change as the subtype is part of the MQTT key.

As a rare exception I would rather change the "model" key here to not break existing usage, i.e.
```
"model", "", DATA_COND, sub_type != 4, DATA_STRING, "Fineoffset-WN34",
"model", "", DATA_COND, sub_type == 4, DATA_STRING, "Fineoffset-WN34D",
```
and don't report `subtype`.

What do you think?

**Comment by ProfBoc75** [comment]
> I think `subtype` might be a good choice here as it is a different "function" (coding of the value) in the same protocol. But this will be a breaking change as the subtype is part of the MQTT key.
> 
> As a rare exception I would rather change the "model" key here to not break existing usage, i.e.
> 
> ```
> "model", "", DATA_COND, sub_type != 4, DATA_STRING, "Fineoffset-WN34",
> "model", "", DATA_COND, sub_type == 4, DATA_STRING, "Fineoffset-WN34D",
> ```
> 
> and don't report `subtype`.
> 
> What do you think?

Yes, good approach, I'm updating the decoder. Instead, I will add the subtype as a verbose message.
Because we know the sub-type is 0x4 for WN34D, and it's 0x0 for WN34L ( cu8 files from this [PR at rtl_433_tests](https://github.com/merbanan/rtl_433_tests/pull/426)), but we don't know for other models, may be other values than 0 & 4, I would like to catch, the reason why I'm asking for some feedback in the issue.

In the same time, I was also wondering how to show this model, because the decoder is always reporting WN34, and yet it's able to decode other models WN34L/S and D, your approach answers to this concern, and I will enrich also the name accordingly.

Good point, thx.

**Comment by Mart124** [comment]
Many thanks @ProfBoc75 for your work and @zuckschwerdt for your review 👍
Could we think about merging this patch if everything is OK with it ? So that we can begin using it :)
Thank you again !

**Comment by zuckschwerdt** [comment]
Guess it doesn't matter too much, we can further enlarge the allowed length to 500. Do you want to PR the change?

**Pull request merged**
