### PR TITLE
Add Bresser 6-in-1 support

### PR DESCRIPTION
**Pull request by zuckschwerdt**
See #1214

### CODE REVIEW

**Comment by merbanan** [comment]
Can we merge this? It looks to be in fairly good shape.

**Comment by zuckschwerdt** [comment]
Updated. I'm waiting for one of the reporters fomr #1214 to confirm this is working.

**Comment by ar0berts** [comment]
Dear Christian,

As a Bresser 6 in 1 owner I'm really looking forward to the 6in1 code. I have cloned your branch but not knowing the code for the 6in1 decoder has prevented me accessing my weather station. `-R 119` doesn't work. I'm happy to send output from `rtl_433 -s 1M -X 'n=Bresser-6in1,m=FSK_PCM,s=120,l=120,r=2500' ` if that helps.

Andrew

**Comment by zuckschwerdt** [comment]
Would be great to have a device owner confirm this working and finally close this.

Does it work when you try the files from here? https://github.com/merbanan/rtl_433_tests/tree/master/tests/bresser_6in1/01
(note that you need to specify the sample rate when reading back files: `rtl_433 -s 1000k gfile.cu8`)

If the rtl_433_tests samples work but your device does not, please capture some new samples (`-S unknown`) check if there is data (your -X line looks good for that) and upload here as zip.

**Comment by RebeckaJohansson** [comment]
I did some code check
And got this output 

I tested to spin my wind pointer and the numbercode changed in the end of the code. Its both wind speed and wind gust that i tested but dont know how to formatting it right in bitbench https://triq.net/bitbench?c=%7B205%7Daaaaaaaaaa2dd47c6a1910084d18ffffff3538168481fff0f5f8&c=%7B204%7D55555555545ba91e8e3220109a31fffffe6a71fffffffe02040&c=%7B196%7D55555555545ba89c8a3220109a31fffffe0131fffffffe03a&c=%7B204%7D55555555545ba9c8703220109a31fffffe01302d0905ffe193f&c=%7B206%7Daaaaaaaaaa2dd44e451910084d18ffffff0098ffffffff01d7fc&c=%7B204%7D55555555545ba97ad03220109a31fffffe01302d0903ffe1940&f=SYNC16h%20CHK%3F8h8h%20ID%3F8h8h8h8h8h%20WIND%20SPEED%208h8h8h%20WIND%20DIR%208h4h%20%3F4h%20TEMP8h.4h%20%3F4h%20HUM8h%20RAIN%3F8h%20TEMP%20NEG%208h%208h%208h%0A&a=Sync&m=2dd4

**Comment by zuckschwerdt** [comment]
S.a. #1416 #1212 #1172 #1492 #1214

**Comment by konserninjohtaja** [comment]
I am getting this:
time      : 2020-10-06 10:11:37
model     : Bresser-6in1 id        : 18b00301
channel   : 0            Battery   : 0             Wind Gust : 3.5 m/s       Wind Speed: 3.0 m/s       Direction : 114           Rain      : 0.0 mm        Flags     : 1             Integrity : CRC
bresser_6in1_decode: {144} 81 eb 18 b0 03 01 18 fd dd fd 12 18 12 54 89 ff 90 9c

Please report your exact sensor model and this ID "18b0 0301 18"
at https://github.com/merbanan/rtl_433/pull/1214
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2020-10-06 10:11:49
model     : Bresser-6in1 id        : 18b00301
channel   : 0            Battery   : 0             Temperature: 12.5 C       Humidity  : 89            Wind Gust : 2.2 m/s       Wind Speed: 2.2 m/s       Direction : 121           Flags     : 1             Integrity : CRC
MSG: {200} ed 49 19 10 13 64 2b 00 00 00 00 00 06 59 99 80 00 13 ff ff e0 e0 00 00 00
XOR: {200} 47 e3 b3 ba b9 ce 81 aa aa aa aa aa ac f3 33 2a aa b9 55 55 4a 4a aa aa aa
bresser_6in1_decode: {144} f6 d3 18 b0 03 01 18 fd aa fd 10 08 ff ff ff ff 01 62

Please report your exact sensor model and this ID "18b0 0301 18"
at https://github.com/merbanan/rtl_433/pull/1214

Station outdoor sensor is https://www.bresser.de/en/Weather-Time/Weather-Center/BRESSER-Professional-WIFI-Weather-Centre-6in1.html

**Comment by konserninjohtaja** [comment]
Seems ok?

rtl_433 -f 868.3M -s 1M -R 119
rtl_433 version 20.02-176-g04feb2b branch master at 202010060945 inputs file rtl_tcp RTL-SDR
Use -h for usage help and see https://triq.org/ for documentation.
Trying conf file at "rtl_433.conf"...
Trying conf file at "/home/pi/.config/rtl_433/rtl_433.conf"...
Trying conf file at "/usr/local/etc/rtl_433/rtl_433.conf"...
Trying conf file at "/etc/rtl_433/rtl_433.conf"...

New defaults active, use "-Y classic -s 250k" for the old defaults!

Registered 1 out of 167 device decoding protocols [ 119 ]
Found Rafael Micro R820T tuner
Exact sample rate is: 1000000.026491 Hz
[R82XX] PLL not locked!
Sample rate set to 1000000 S/s.
Tuner gain set to Auto.
Tuned to 868.300MHz.
Allocating 15 zero-copy buffers
bresser_6in1_decode: {144} f2 66 18 b0 03 01 18 ff 66 ff 19 48 13 14 70 ff 60 60
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2020-10-10 15:07:49
model     : Bresser-6in1 id        : 18b00301
channel   : 0            Battery OK: 1             Temperature: 13.1 C       Humidity  : 70            kind      : 1             Wind Gust : 0.9 m/s       Wind Speed: 0.9 m/s       Direction : 194           Integrity : CRC
bresser_6in1_decode: {144} 44 8e 18 b0 03 01 18 ff cc ff 19 48 ff ff ff ff 01 f3
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2020-10-10 15:08:01
model     : Bresser-6in1 id        : 18b00301
channel   : 0            Battery OK: 1             kind      : 1             Wind Gust : 0.3 m/s       Wind Speed: 0.3 m/s       Direction : 194           Rain      : 0.0 mm        Integrity : CRC
bresser_6in1_decode: {144} 35 22 18 b0 03 01 18 fe ff fe 16 98 13 14 70 ff 90 4c

**Pull request merged**
