### PR TITLE
Add comment and change div with mul

### PR DESCRIPTION
**Pull request by sbsrouteur**

### CODE REVIEW

**Comment by zuckschwerdt** [comment]
This looks clean now! I've made some changes in the meantime: #547 but this can be merged first for attribution and I'll reroll my branch.

**Comment by merbanan** [comment]
Oops, my bad. Can you rebase again? I accidentally applied the other patch first.

**Comment by zuckschwerdt** [comment]
The changes done here are included in my patch. I had a talk with @sbsrouteur by mail and he explained the needed documentation to me :)

**Comment by zuckschwerdt** [comment]
Kudos to @sbsrouteur for figuring out the strange inHg units -- I would have guessed badly with 0,5 PSI as unit. Thanks for adding the documentation (which went in with my patch). This can be closed.

**Comment by merbanan** [comment]
ok

**Pull request closed without merging**
