### PR TITLE
Solight TE44 wireless thermometer

### LINKED ISSUE #563: Solight TE44
I have mostly decoded my home wireless thermometer, it is some kind of generic simple chinese transmitter used in different kits, so far I have found two (Solight TE44 and EMOS E0107T) sold mostly in central europe.

---

I am able to decode the data discovered by `rtl_433 -a -t`, the format is following:

12 repetitions of the same 36 bit payload, 1 zero between each repetition.

36 bit payload format: `xxxxxxxx 10ccmmmm tttttttt 1111hhhh hhhh`

`x` - random key - changes after device reset - 8 bits
`c` - channel (0-2) - 2 bits
`m` - multiplier - signed integer, two's complement - 4 bits
`t` - temperature in celsius - unsigned integer - 8 bits
`h` - checksum - 8 bits

temperature = `((256 * m) + t) / 10`

(not sure how the checksum is calculated yet but it seems it takes at least the first three bytes into account) 

There might be some battery low signal, which I did not tested yet.

---

Sample output from `rtl_433 -r gfile022.data -a` (attached [gfile022.zip](https://github.com/merbanan/rtl_433/files/1066479/gfile022.zip)):

```
Test mode active. Reading samples from file: gfile022.data
Input format: uint8
*** signal_start = 16227, signal_end = 262145
signal_len = 245918,  pulses = 455
Iteration 1. t: 126    min: 125 (94)    max: 127 (361)    delta 4
Iteration 2. t: 126    min: 125 (1)    max: 127 (454)    delta 0
Distance coding: Pulse length 126

Short distance: 233, long distance: 483, packet distance: 971

p_limit: 126
bitbuffer:: Number of rows: 12 
[00] {37} 94 91 15 fe 90 : 10010100 10010001 00010101 11111110 10010
[01] {37} 94 91 15 fe 90 : 10010100 10010001 00010101 11111110 10010
[02] {37} 94 91 15 fe 90 : 10010100 10010001 00010101 11111110 10010
[03] {37} 94 91 15 fe 90 : 10010100 10010001 00010101 11111110 10010
[04] {37} 94 91 15 fe 90 : 10010100 10010001 00010101 11111110 10010
[05] {37} 94 91 15 fe 90 : 10010100 10010001 00010101 11111110 10010
[06] {37} 94 91 15 fe 90 : 10010100 10010001 00010101 11111110 10010
[07] {37} 94 91 15 fe 90 : 10010100 10010001 00010101 11111110 10010
[08] {37} 94 91 15 fe 90 : 10010100 10010001 00010101 11111110 10010
[09] {37} 94 91 15 fe 90 : 10010100 10010001 00010101 11111110 10010
[10] {37} 94 91 15 fe 90 : 10010100 10010001 00010101 11111110 10010
[11] {36} 94 91 15 fe 90 : 10010100 10010001 00010101 11111110 1001
Test mode file issued 4 packets
```
decoded as:

channel 2 (`c` = 1, indexed from 0)
`m` = 1 
`t` = 21

temperature 27,7 C - ((256 * 1) + 21) / 10

Output from `rtl_433 -r gfile022.data -A` does not make much sense.

---

My question is, what settings should I specify in `r_device` struct to get any sensible data to my callback? So far I was not able to figure anything out, even though I experimented quite a lot with those settings.

Could anybody help me with finding the optimal settings for `modulation`, `short_limit`, `long_limit`, `reset_limit`? Thanks

### PR DESCRIPTION
**Pull request by oujesky**
Solight TE44 

Closes #563. I will add testing data to https://github.com/oujesky/rtl_433_tests too.

Image of the thermometer

### CODE REVIEW

**Comment by merbanan** [comment]
Automake changes are missing. Can you send some bit decodes also so we can try to figure out the crc/checksum ?

**Comment by zuckschwerdt** [comment]
Please document the exact timings, not just the calculated limits. You need to check if there are at least 12 rows before looping over them. Do you really need a TAB character in the ID output?

**Comment by oujesky** [comment]
Thanks for review, I fixed it and squashed the commit. 
- added check for exactly 12 rows
- added the file to Makefile.am
- added the timing information
- removed the tab from Id formatting (this was actually copy pasted from some other driver source, it is in few of them, no idea why, in other drivers this is not present)

---

As for the checksum investigation, there are some other messages I captured:

```
11011010 10000001 11110011 11111001 01000  49,9 CH1
11011010 10000001 11011111 11111111 11000  47,9 CH1
11011010 10000001 11001110 11110110 01100  46,2 CH1
11011010 10000001 11000001 11111111 11110  44,9 CH1
11011010 10000001 10100100 11111101 11010  42,0 CH1
11011010 10000001 10001110 11111110 11110  39,8 CH1
11011010 10000001 10000111 11110010 11000  39,1 CH1
11011010 10000001 01111100 11110010 11100  38,0 CH1
11011010 10000001 01110100 11110001 10010  37,2 CH1
11011010 10000001 01101111 11110110 11010  36,7 CH1
11011010 10000001 01100111 11110101 10100  35,9 CH1
11011010 10000001 01100011 11111101 10010  35,5 CH1
11011010 10000001 01011110 11110010 10110  35,0 CH1
11011010 10000001 01011011 11110101 11000  34,6 CH1
11011010 10000001 01011000 11110111 00010  34,4 CH1
11011010 10000001 01010100 11111100 01010  34,0 CH1
11011010 10000001 01001110 11110100 01010  33,4 CH1
11011010 10000001 01001010 11111100 01100  32,9 CH1
11011010 10000001 01001001 11111110 10110  32,9 CH1
11011010 10000001 01001001 11111110 10110  32,9 CH1
11011010 10000001 01001000 11110001 11110  32,8 CH1
11011010 10000001 01000101 11110101 11110  32,5 CH1
11011010 10000001 01000011 11110000 01010  32,3 CH1
11011010 10000000 10010110 11111111 00000  15,0 CH1
11011010 10000000 10000000 11111100 01000  12,8 CH1
11011010 10000000 01101010 11110101 11000  10,6 CH1
11011010 10000000 01011101 11110100 00000   9,3 CH1
11011010 10000000 01001100 11111101 10100   7,6 CH1
11011010 10000000 00101101 11110111 10110   4,5 CH1
11011010 10000000 00001101 11111010 01110   1,3 CH1
11011010 10001111 11111110 11110010 00110  -0,2 CH1
11011010 10001111 11110000 11110100 11100  -1,6 CH1
11011010 10000000 00010100 11110000 10100   2,0 CH1
11011010 10001111 11110100 11111100 11010  -1,2 CH1
11011010 10001111 11100100 11111010 00110  -3,6 CH1
11011010 10001111 11001000 11111100 10110  -5,6 CH1
11011010 10001111 10011000 11110010 11000 -10,4 CH1
11011010 10001111 01100100 11111000 00000 -15,6 CH1
11011010 10001111 01100001 11111111 01110 -15,9 CH1
11011010 10001111 01100101 11110111 01000 -15,5 CH1
11011010 10001111 01100010 11111101 10100 -15,8 CH1
11011010 10001111 11001011 11111110 01100  -5,3 CH1
11011010 10001111 01110101 11110001 10100 -13,9 CH1
10010100 10000001 00001010 11111011 10100  26,6 CH1

10010100 10010001 00000000 11111111 00000  25,6 CH2
10010100 10010001 00010101 11111110 10010  27,7 CH2
10010100 10010000 11111111 11110011 01110  25,5 CH2
10010100 10010001 00000000 11111111 00000  25,6 CH2

10010100 10100000 11111110 11110001 11100  25,4 CH3
10010100 10100000 11111101 11110011 00110  25,3 CH3
10010100 10100000 11111011 11110110 10010  25,1 CH3

10010100 10000001 00000110 11110000 11100  26,2 CH1
11111010 10000001 00000111 11110111 11110  26,3 CH1
11111010 10000001 00001010 11110011 11110  26,6 CH1
00111001 10000001 00001100 11111110 10000  26,8 CH1
00111001 10000001 00001111 11111100 01010  26,1 CH1
00111001 10000001 00010100 11111011 00010  27,6 CH1
```

I only tried to find if this matches CRC-8 checksum here: http://crccalc.com/, but frankly I did not spend much time on that. I can also send the captured files for some of them if needed.

**Comment by zuckschwerdt** [comment]
Looks good too me :) Minor nit-picking: it's spelled "always" and the last newline is missing. But that is no showstopper. (and kudos for squashing, seems few people care about understanding git anymore.)

**Comment by oujesky** [comment]
Ad checksum: I tried to bruteforce the combinations of polynomial and intial value for crc8 and ran it down on this dataset (with both `crc8()` and `crc8le()` functions from `utils.h`), but no complete match there.

I also tried few combinations of adding, subtracting, anding, oring and xoring the first three bytes together, but here my imagination probably ends :)

**Comment by merbanan** [comment]
Jolly good.

**Pull request merged**
