### PR TITLE
Added website and sensor specifications for Jansite TPMS Model Solar

### PR DESCRIPTION
**Pull request by freundm**

### CODE REVIEW

**Comment by zuckschwerdt** [comment]
Thanks. First line should be a title and end with a dot and two newlines. (just put the link in an extra line).
We want to stick to 7bit ascii in source files, "±" and "°" need to be replaced.

**Comment by freundm** [comment]
Fixed.

I pulled the ° from [src/devices/tpms_jansite.c](https://github.com/merbanan/rtl_433/blob/master/src/devices/tpms_jansite.c#L14), I can remove that as well if you want.

**Comment by merbanan** [comment]
I have now merged the decoder, can you rebase your PR ?

**Comment by AutomGuy** [comment]
Hi Guys,
i have a question. what is the send intervall of the jansite solar TPMS?

Many thx in advance

**Pull request merged**
