### PR TITLE
Fix FSK demodulation when sample rate is not 250 kHz

### PR DESCRIPTION
**Pull request by f1oat**
Here is a fix for issue #1135

### CODE REVIEW

**Comment by f1oat** [comment]
Works on file, but not with RTL dongle.
Need to do more testing.

**Comment by zuckschwerdt** [comment]
Just keep this open and update with more commits. Easier to follow the isssue on a single PR.

**Comment by zuckschwerdt** [comment]
Regarding `PD_MIN_PULSE_SAMPLES`, we want to be sure that not just a few samples are mixed up but that we really changed state (OOK). This should be independent of the sample rate.
I.e. here it means "ignore a few stray samples", but more than a few samples in a new state then accept that.
If we use a value that grows with a higher sample rate then we just have a low-pass filter and can't read faster signals by using a higher sample rate. The cut-off would be fixed. Perhaps a good thing, but it should be noted.

**Comment by f1oat** [comment]
Thanks for the help.
Looks like my patch is not working well with more noisy signal (so the issue is not related to realtime run with RTL dongle).
I have captured the signal on file, and tried to decode it.
Here is the result @1024k with my patch
Detected FSK package    @0.039603s
Analyzing pulses...
Total count:   21,  width: 8.15 ms              ( 8342 S)
Pulse width distribution:
 [ 0] count:   11,  width:  104 us [102;107]    ( 106 S)
 [ 1] count:    3,  width:   78 us [73;83]      (  80 S)
 [ 2] count:    4,  width:  202 us [187;209]    ( 207 S)
 [ 3] count:    3,  width:  304 us [289;312]    ( 311 S)
Gap width distribution:
 [ 0] count:   12,  width:  108 us [104;129]    ( 111 S)
 [ 1] count:    1,  width:  732 us [732;732]    ( 750 S)
 [ 2] count:    1,  width:  524 us [524;524]    ( 537 S)
 [ 3] count:    2,  width:  377 us [338;416]    ( 386 S)
 [ 4] count:    3,  width:  218 us [210;233]    ( 223 S)
 [ 5] count:    1,  width: 1076 us [1076;1076]  (1102 S)
Pulse period distribution:
 [ 0] count:    7,  width:  205 us [184;235]    ( 210 S)
 [ 1] count:    1,  width:  838 us [838;838]    ( 858 S)
 [ 2] count:    1,  width:  626 us [626;626]    ( 641 S)
 [ 3] count:    4,  width:  435 us [396;489]    ( 445 S)
 [ 4] count:    6,  width:  317 us [292;338]    ( 325 S)
 [ 5] count:    1,  width: 1285 us [1285;1285]  (1316 S)
Level estimates [high, low]:  15903,    181
RSSI: -0.1 dB SNR: 19.4 dB Noise: -19.5 dB
Frequency offsets [F1, F2]:    -285,  -7452     (-4.5 kHz, -116.4 kHz)
Guessing modulation: No clue...

And the same file resampled to 250k with sox and demodulated @250k
Detected FSK package    @0.039604s
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : @0.039604s   brand     : LaCrosse
model     : TX35DTH-IT   id        : 43
Battery   : OK           NewBattery: 0             Temperature: 10.8 C       Humidity  : 77 %          Integrity : CRC
Analyzing pulses...
Total count:   29,  width: 8.42 ms              ( 2104 S)
Pulse width distribution:
 [ 0] count:   21,  width:  104 us [104;112]    (  26 S)
 [ 1] count:    4,  width:  208 us [208;208]    (  52 S)
 [ 2] count:    3,  width:  312 us [312;316]    (  78 S)
 [ 3] count:    1,  width:   56 us [56;56]      (  14 S)
Gap width distribution:
 [ 0] count:   20,  width:  104 us [104;108]    (  26 S)
 [ 1] count:    2,  width:  312 us [312;316]    (  78 S)
 [ 2] count:    4,  width:  208 us [208;212]    (  52 S)
 [ 3] count:    2,  width:  416 us [416;420]    ( 104 S)
Pulse period distribution:
 [ 0] count:   15,  width:  208 us [208;216]    (  52 S)
 [ 1] count:    7,  width:  476 us [420;524]    ( 119 S)
 [ 2] count:    6,  width:  312 us [312;316]    (  78 S)
Level estimates [high, low]:  15968,     61
RSSI: -0.1 dB SNR: 24.1 dB Noise: -24.2 dB
Frequency offsets [F1, F2]:     632, -20633     (+2.4 kHz, -78.7 kHz)
Guessing modulation: No clue...

We see some differences on pulse width distribution.
Any idea?

**Comment by zuckschwerdt** [comment]
I always like to check with `./examples/sigrok-open.sh` (needs Pulseview from sigrok) to see what the demod is doing.

**Comment by f1oat** [comment]
Here is sigrok output @1024k
image

And the same signal @250k
image

The problem seems located in the FM demodulator.

**Comment by merbanan** [comment]
I do have my vaporware fsk demod algorithm waiting for implementation. @f1oat  Do you wanna try implementing it? I can try (in a few days) and see how it performs with the samples you posted in the issue ticket.

And have you tried just doing PD_MIN_PULSE_SAMPLES 5? That has worked as a workaround for a few people.

**Comment by f1oat** [comment]
Thanks: the decoding is ok with PD_MIN_PULSE_SAMPLES 5 (scaled to 20 for 1024k).

image

And here is the new noisy sample I am using for this test.

[g001_868.35M_1024k_NOISY.cu8.zip](https://github.com/merbanan/rtl_433/files/3585426/g001_868.35M_1024k_NOISY.cu8.zip)

Not sure having enough free time for coding your new algorithm.
Is it a complex one?

**Comment by merbanan** [comment]
[fsk_demodulator.zip](https://github.com/merbanan/rtl_433/files/3586650/fsk_demodulator.zip)

The idea is simple and related to the current code but there are some complexities in implementing it.

**Comment by f1oat** [comment]
I have read the .m file.
I agree, there is a some significative work to have it works in streaming mode. I will not have enough time for that, but I can help on testing.
I am wondering if some filtering or averaging is needed when estimating var_test_min and var_test_max: when there is some local large estimation error on phase gradient (poor SNR), it should not disturb the overall estimation of the mid frequency.

**Comment by merbanan** [comment]
The samples I tested did work fine with the suggested algorithm. The components used are the following, arctan demod with 2 unknown levels. The level values should converge with a max/min tracker after the first transition from low to high or vise versa. When you know the levels, back-track to the signal start and keep track with hysteris of the level transitions.

This method was able to do blind bit recovery of signals of significantly different dynamics. Theoretically this method could be used to demod OOK/ASK and FSK in different steps.

**Pull request closed without merging**
