### PR TITLE
Adds GE Smartremote Plus

### PR DESCRIPTION
**Pull request by mores**

### CODE REVIEW

**Comment by merbanan** [comment]
LGTM but we need one signal sample also.

**Comment by mores** [comment]
I added the samples here: https://groups.google.com/g/rtl_433/c/S8Ty9utN-no
Where should I put it for this merge ?

**Comment by merbanan** [comment]
https://github.com/merbanan/rtl_433_tests

**Comment by mores** [comment]
https://github.com/merbanan/rtl_433_tests/pull/434
Has been added.

**Pull request merged**
