### PR TITLE
support for hideki/cresta temperature sensor

### PR DESCRIPTION
**Pull request by Mindavi**
This patch adds support for the cresta temperature sensor module.
The module talks with the HIDEKI protocol, but doesn't contain the
humidity/wind/rain data (afaict). This means we can easily parse those
using the existing infra. Only a new 'module type' needs to be added.

### CODE REVIEW

**Comment by zuckschwerdt** [comment]
Thanks. Do we have some samples in rtl_433_tests?

**Comment by Mindavi** [comment]
Didn't have them earlier, but added them just now.

**Comment by Mindavi** [comment]
This also triggers on the SIGMA-TE130NL and mebus_te204nl sensors. Both of those sensors look a lot like the sensor I've got at home, so I think that's correct. This might also mean that the https://github.com/merbanan/rtl_433/blob/master/src/devices/mebus.c should be deleted. It doesn't trigger anymore when I enable it with `rtl_433 -R 13 -r rtl_433_tests/tests/mebus_te204nl/01/gfile001.cu8`, so I'm not sure about the state of that code.

**Comment by zuckschwerdt** [comment]
I don't think we have samples for "Mebus 433" from mebus.c. I guess that was a different device.
No comments, no samples, it's likely to be removed someday.
At least the PPM expected there doesn't match the MC samples in mebus_te204nl/01 and shouldn't ever have.

**Pull request merged**
