### PR TITLE
ADD: Missing delay and low battery codes for DS10A door sensor.

### PR DESCRIPTION
**Pull request by azuca**
Tested with several DS10A on min, max and low battery

### CODE REVIEW

**Comment by merbanan** [comment]
Hi, the LSB sound like a battery indicator. Mask it out and add it as a separate parameter.

**Comment by azuca** [comment]
Hi, The LSB is a low battery indicator for the DS10A devices but I don't own the other X10 devices handled in this module so I can't verify their use of this bit. Enhancing the switch statement for the DS10A cases that I am able to specifically test seemed the lowest risk approach, especially when dealing with security devices. Open to suggestions/recommendations.

**Comment by zuckschwerdt** [comment]
There is no existing use of the LSB so this should be safe:
`battery_low = b[2] & 1;` and
`switch (b[2] & 0xfe) {`
Handle the battery_low like here: https://github.com/merbanan/rtl_433/blob/master/src/devices/eurochron.c#L75

**Comment by azuca** [comment]
Looks good. Thanks for the pointer to the eurochron code.

**Comment by azuca** [comment]
Some X10 security devices, like MS10A, do not support a battery indicator so I can't output a "Battery OK" message when the LSB is cleared because the battery state is obviously unknown. I could only include the battery indicator in the output data when the LSB is set. This would also maintain backwards compatibility in the output format for DS10A devices. Alternatively, I could explicitly tag events as originating from an X10 security device that I know for sure supports the battery indicator and only output the battery indicator for those events. Any preferences?

**Comment by merbanan** [comment]
Looks good to me

**Pull request merged**
