### PR TITLE
Remove all (4) unreferenced variables

### PR DESCRIPTION
**Pull request by winterrace**
see above, minor stuff...

### CODE REVIEW

**Comment by merbanan** [comment]
You need to rebase/rework this. Changes looks ok. But 75 commits are abit to much.

**Comment by winterrace** [comment]
OK, I have to check how to do this...

**Comment by winterrace** [comment]
Hm, it was the same with my last pull requests. But each of them ended up in a single commit to rtl_433. So the long commit history of my source brances has no negative effect to the rtl_433 repo. However, I try to get rid of this...

**Comment by zuckschwerdt** [comment]
Yes, we can squash merge this, but the PR looks really messy. Perhaps you can reset your master branch, pull our upstream master branch and then in the future branch your changes off that.

**Pull request merged**
