### PR TITLE
Add X10 Dim, Bright, All Lights ON, and All Off commands

### PR DESCRIPTION
**Pull request by dfleck**
Adds remaining X10 commands. Adds debugging. Cleaned up data verification. Adjusted timing to meet specs.

### CODE REVIEW

**Comment by zuckschwerdt** [comment]
Looks good, thanks!
- line 11 (mods) should be line 5
- can you put `clang-format on/off` around the data_make (see other decoders)
- should "ALL LTS ON" be "ALL ON"?

**Comment by dfleck** [comment]
> Looks good, thanks!
> 
> * line 11 (mods) should be line 5
> * can you put `clang-format on/off` around the data_make (see other decoders)
> * should "ALL LTS ON" be "ALL ON"?

First two changes made.
There's two types of modules, Light and Appliance. ALL OFF turns all of both off. ALL LTS ON turns all Light modules on but leave Appliance modules alone.

**Comment by dfleck** [comment]
Sorry, I'm a bit new to this. I intended the addition of the LaCrosse TX25U to be a separate pull request to keep things clean but the changes ended up being added to this request.

**Comment by zuckschwerdt** [comment]
Ok :) Looks good too. We'll fix this on merge.

**Comment by dfleck** [comment]
What are the "rules" regarding enabling a device? The RF protocol for X10 is almost identical to X10_Security which is enabled, so I don't think there are any particularly bad interactions with other devices at the signal level. I have tested X10 with several controllers I have and they seem to work as expected. Should I have enabled the X10 device?

**Comment by zuckschwerdt** [comment]
> What are the "rules" regarding enabling a device?

Checksum. There has to be a check to distinguish random bits from a proper transmission. X10_sec has 13 parity bits. Not sure why there is mention of "CRC" (maybe because the notion of xor?), the `mic` should actually be "SUM", i.e. the "strength" of a sum, mor than just "PARITY" but not "CRC".

**Comment by merbanan** [comment]
> What are the "rules" regarding enabling a device?

That there is enough logic to reject bogus/random transmissions.

**Comment by dfleck** [comment]
In that case I've gone ahead and enabled the X10 device. There are three quality checks:
1) The packet is the proper length
2) The data is two bytes but sent as four. The extra two bytes are the complement of the "regular" two bytes. There is a check that byte 0 is the complement of byte 1 and byte 2 is the complement of byte 3.
3) Some bits are always zero or always one. These are validated.

**Pull request merged**
