### PR TITLE
Add support for RTGN318

### PR DESCRIPTION
**Pull request by tazounet**
Hello,

This patch add support for Oregon Thermo Hygro RF Clock Sensor RTGN318.

Jérôme

### CODE REVIEW

**Comment by merbanan** [comment]
Hi, can you send some sample recordings also? To the rtl_433_tests repo.

**Comment by merbanan** [comment]
Can you split this patch in a functional change and one cosmetics ? If you look at it now there are 4 hunks with spacing changes and one function change. I'd like to keep them apart.

**Comment by merbanan** [comment]
The functional changes looks fine.

**Comment by tazounet** [comment]
I split the patch.

**Comment by merbanan** [comment]
Thanks.

**Pull request merged**
