### PR TITLE
Small Python Cleanup

### PR DESCRIPTION
**Pull request by Cabalist**
Not really necessary but I PEP8'd the python code here.  
Also: 
remove unused imports
fix typos
make the exception handling more specific in the JSON Decoder

### CODE REVIEW

**Comment by zuckschwerdt** [comment]
Looks good to me, thanks. But others might want to take a look, merge maybe late next week.

**Comment by merbanan** [comment]
@vestom pr will be merged in a week unless you have objections.

**Comment by zuckschwerdt** [comment]
I guess it is already merged with #716 ?

**Comment by Cabalist** [comment]
Yep.  Sorry about that.  I had a rebase issue looks like I combined the two.  This can be closed.

**Comment by vestom** [comment]
Looks good.

**Pull request closed without merging**
