### PR TITLE
DSC Sensors break out status bits

### PR DESCRIPTION
**Pull request by rct**
Break out the DSC sensor status bits into individual fields.

Currently using INTs but should be booleans if/when data_make supports it.

### CODE REVIEW

**Comment by dmcwhinnie** [comment]
Tested this and everything looks good.  Real nice to have all the bits broken out into individual fields.

**Comment by rct** [comment]
@zuckschwerdt, @merbanan - is there anything that needs to be done to get this merged?

**Comment by merbanan** [comment]
Nope, looks good.

**Comment by zuckschwerdt** [comment]
I'm just trying to catch up with the last week. Looks good, as @merbanan said. Just follow up with a cleanup for those temporary/experimental fields when the dust settles.

**Pull request merged**
