### PR TITLE
Add support for parsing timedate in wbus

### PR DESCRIPTION
**Pull request by jedi7**
Tested on Maddalena water meter

### CODE REVIEW

**Comment by merbanan** [comment]
Can you show how it looks before and after?

**Comment by zuckschwerdt** [comment]
Please keep decoders simple, I recommend just dumping the datetime fields into a string, see e.g. https://github.com/merbanan/rtl_433/blob/master/src/devices/ambientweather_wh31e.c#L254

Decoders are not responsible for cleaning up bad or malicious transmissions.
E.g. ` t->tm_sec   = data[0] & 0x3F` has 61-63 as invalid values anyway (60 could be a leap second). If the upper bits are not used and set to `0` then include them (drop the and-mask) -- leave enough room for (bad) 3-digit components.

Also I'd like to see `assert` replaced with a simple if+fprintf -- as all other sanity checks do it.
And if possible do with out varargs.

**Comment by jedi7** [comment]
ofcourse :) Not sure if here it will be visible enough :-/
old:
`time      : 2021-01-17 15:17:19                    Protocol  : 104
model     : Wireless-MBus Mode      : T            Manufacturer: MAD         ID        : 19111976
Version   : 80           Device Type: 0x07         Device Type String: Water Control   : 0x44          Data Length: 173          Data      : aa4424347619111950077aa50000202f2f0413aa020000046d112fb12104fd17000000000e78196506812000441369010000426c9f2c8401136901000082016c9f2cd3013bed0100c4016d0c2aa3218104fd280182046c9f2c84041369010000c404134000000084051300000000c405130000000084061300000000c406130000000084071300000000c407130000000084081300000000c408130000000084091300000000c4091300000000ffff
Integrity : CRC
Control Info: 0x7A       Access number: 0xA5       Device Type: 0x00         Configuration Word: 0x2000  Volume   : 0.682 m3     Max Volume flow : 0.493 m3/h                         Volume of month -1: 0.361 m3
 Volume of month -2: 0.064 m3                       Volume of month -3: 0.000 m3                        Volume of month -4: 0.000 m3                        Volume of month -5: 0.000 m3
 Volume of month -6: 0.000 m3                       Volume of month -7: 0.000 m3                        Volume of month -8: 0.000 m3                        Volume of month -9: 0.000 m3
 Volume of month -10: 0.000 m3                      Volume of month -11: 0.000 m3                       Volume of month -12: 0.000 m3
Modulation: FSK          Freq1     : 868.9 MHz     Freq2     : 869.0 MHz
RSSI      : -4.2 dB      SNR       : 16.9 dB       Noise     : -21.1 dB`

new:
`time      : 2021-01-17 15:13:22                    Protocol  : 104
model     : Wireless-MBus Mode      : T            Manufacturer: MAD         ID        : 19111976
Version   : 80           Device Type: 0x07         Device Type String: Water Control   : 0x44          Data Length: 173          Data      : aa4424347619111950077aa30000202f2f0413aa020000046d0d2fb12104fd17000000000e78196506812000441369010000426c9f2c8401136901000082016c9f2cd3013bed0100c4016d0c2aa3218104fd280182046c9f2c84041369010000c404134000000084051300000000c405130000000084061300000000c406130000000084071300000000c407130000000084081300000000c408130000000084091300000000c4091300000000ffff
Integrity : CRC
Control Info: 0x7A       Access number: 0xA3       Device Type: 0x00         Configuration Word: 0x2000  Volume   : 0.682 m3      TimeDate : 21/1/17 15:13:00                         Date     : 20/12/31
 Date     : 20/12/31     Max Volume flow : 0.493 m3/h                         TimeDate : 21/1/3 10:12:00                          Date     : 20/12/31       Volume of month -1: 0.361 m3
 Volume of month -2: 0.064 m3                       Volume of month -3: 0.000 m3                        Volume of month -4: 0.000 m3                        Volume of month -5: 0.000 m3
 Volume of month -6: 0.000 m3                       Volume of month -7: 0.000 m3                        Volume of month -8: 0.000 m3                        Volume of month -9: 0.000 m3
 Volume of month -10: 0.000 m3                      Volume of month -11: 0.000 m3                       Volume of month -12: 0.000 m3
Modulation: FSK          Freq1     : 868.9 MHz     Freq2     : 869.0 MHz
RSSI      : -0.2 dB      SNR       : 23.5 dB       Noise     : -23.7 dB`

**Comment by jedi7** [comment]
@zuckschwerdt Not sure what you mean. The upper bit is part of wbus protocol. Some times/dates are not set in the device and it can be detected by the bit. So there is no reason to display invalid/unused dates. No other checking is used (as you pointed at the seconds).

I can replace the assert, but imho wrong number in exp is program bug. (user input is already limited to ranges)

Vararg are very helpful here, because there is lot of different types (I will add another parsing later) and I anyway need to put all of these things into string. Because data_append does not support more complex values.
Or why you thing vararg is bad thing?

**Comment by zuckschwerdt** [comment]
The question was: what is `data[0] & 0xC0`? and shouldn't `data[0] & 0x3F == data[0]`?
I don't like the use of `time.h`, just dump the time data in a string buffer. Date format should be ISO8601, `"%04d-%02d-%02dT%02d:%02d:%02dZ"`.

If you are sure the assert will always work do it like https://github.com/merbanan/rtl_433/blob/master/src/pulse_demod.c#L42

Vararg can be tricky. E.g. you are not annotating for the compiler, this might confuse a static checker. (e.g. https://github.com/merbanan/rtl_433/blob/master/include/term_ctl.h#L73). Best to stick to basics if possible, clever decoders make maintainance that more involved for us.

**Comment by merbanan** [comment]
Can you post the the json ? That way I can always reformat as I see fit.

And as a note, a complete OMS compatible wmbus decoder will be quite complicated. If you look at the wmbusmeters project you will see that there are lots of different sensors implementing the protocol and lots of proprietary deviations. I am not sure how much we should support. I think that everything that can be decoded with the wmbus standard can be implemented. For example there are temperature sensors that has a battery time of 15 years and can be configured to not use encryption. For those rtl_433 is a perfect match. But if people send patches of good quality I'm not going to stop it. As long as I feel I could maintain the code I will accept the code.

But I'm not sure we need the assert code. I'll let @zuckschwerdt rule on that. Anyway keep the patches coming. More support is welcome.

**Comment by jedi7** [comment]
The code is based on many pdfs and googling. Not directly on the Maddalena meter (it is used only for testing). So I hope It will be close to standard.

I will adapt the code and also send it with the json. It will take some time.

**Comment by jedi7** [comment]
not sure what to do with the year. Because it is only %02d, in Maddalena it is +2000, but on other devices it can be different value. So I changed it to just %02d.

old json:
`{"time" : "2021-01-17 17:33:14", "protocol" : 104, "model" : "Wireless-MBus", "mode" : "T", "M" : "MAD", "id" : 20017193, "version" : 80, "type" : 7, "type_string" : "Water", "C" : 68, "data_length" : 173, "data" : "aa4424349371012050077a310000202f2f041331060000046d2131b12104fd17000000000e789559048120004413eb030000426c9f2c840113eb03000082016c9f2cd3013b9a0200c4016d2931ad218104fd280182046c9f2c840413eb030000c404131a00000084051300000000c405130000000084061300000000c406130000000084071300000000c407130000000084081300000000c408130000000084091300000000c4091300000000ffff", "mic" : "CRC", "CI" : 122, "AC" : 49, "ST" : 0, "CW" : 8192, "inst_volume_0" : "1.585 m3", "max_volume_flow_h_3" : "0.666 m3/h", "inst_volume_0" : "1.003 m3", "inst_volume_1" : "0.026 m3", "inst_volume_2" : "0.000 m3", "inst_volume_3" : "0.000 m3", "inst_volume_4" : "0.000 m3", "inst_volume_5" : "0.000 m3", "inst_volume_6" : "0.000 m3", "inst_volume_7" : "0.000 m3", "inst_volume_8" : "0.000 m3", "inst_volume_9" : "0.000 m3", "inst_volume_10" : "0.000 m3", "inst_volume_11" : "0.000 m3", "mod" : "FSK", "freq1" : 868.906, "freq2" : 868.980, "rssi" : -2.234, "snr" : 19.998, "noise" : -22.232}`

new json: 
`{"time" : "2021-01-17 17:31:22", "protocol" : 104, "model" : "Wireless-MBus", "mode" : "T", "M" : "MAD", "id" : 20012906, "version" : 80, "type" : 7, "type_string" : "Water", "C" : 68, "data_length" : 173, "data" : "aa4424340629012050077ac10000202f2f041306070000046d1e31b12104fd17000000000e787880048120004413c9040000426c9f2c840113c904000082016c9f2cd3013b9a0200c4016d0534a7218104fd280182046c9f2c840413c9040000c404131b00000084051300000000c405130000000084061300000000c406130000000084071300000000c407130000000084081300000000c408130000000084091300000000c4091300000000ffff", "mic" : "CRC", "CI" : 122, "AC" : 193, "ST" : 0, "CW" : 8192, "inst_volume_0" : "1.798 m3", "inst_timedate_0" : "21-01-17T17:30:00Z", "inst_date_1" : "20-12-31", "inst_date_2" : "20-12-31", "max_volume_flow_h_3" : "0.666 m3/h", "inst_timedate_3" : "21-01-07T20:05:00Z", "inst_date_8" : "20-12-31", "inst_volume_0" : "1.225 m3", "inst_volume_1" : "0.027 m3", "inst_volume_2" : "0.000 m3", "inst_volume_3" : "0.000 m3", "inst_volume_4" : "0.000 m3", "inst_volume_5" : "0.000 m3", "inst_volume_6" : "0.000 m3", "inst_volume_7" : "0.000 m3", "inst_volume_8" : "0.000 m3", "inst_volume_9" : "0.000 m3", "inst_volume_10" : "0.000 m3", "inst_volume_11" : "0.000 m3", "mod" : "FSK", "freq1" : 868.907, "freq2" : 868.985, "rssi" : -0.182, "snr" : 23.450, "noise" : -23.632}`

**Comment by zuckschwerdt** [comment]
> not sure what to do with the year. Because it is only %02d, in Maddalena it is +2000, but on other devices it can be different value. So I changed it to just %02d.

Difficult decision indeed. I don't think ISO8601 allows omitting the century, but if we can not be sure that the implied offset is always `2000`, well…
Another thought, is the timezone known to be Zulu or might it be a local timezone (I saw something about DST there)?

**Comment by jedi7** [comment]
not sure about the DST :( I cannot test it. Hard to say what to do. Imho timedate will be all in local time, so there is no info about zone.

**Comment by jedi7** [comment]
Are some more modifications requested? Or this is ok?

**Comment by zuckschwerdt** [comment]
A suggestions would be to drop the "Z" in the time strings as the zone is not known, other than that @merbanan has the final say in things wmbus :)

**Pull request merged**
