### PR TITLE
Change support for qx-30x to extract device and button ID

### PR DESCRIPTION
**Pull request by edco**
Per [my comment](https://github.com/merbanan/rtl_433/issues/2902#issuecomment-2094812165) on the initial support request for these devices, this PR adds ID and button extraction based on the EV1527 encoding.

@adminy would you be able to give this a try with your switches and share the ID and button values extracted? I'm hoping you've got a 2-gang QX-302, but I'm keen to see the output regardless.

### CODE REVIEW

**Comment by zuckschwerdt** [comment]
These changes won't break anything, even if you get no test confirmation please ping back for merge in a few days.

**Comment by edco** [comment]
> These changes won't break anything, even if you get no test confirmation please ping back for merge in a few days.

Ping.

**Comment by adminy** [comment]
sure, I'll run a test tomorrow morning if that's okay.

**Comment by edco** [comment]
Sounds good.

**Comment by adminy** [comment]
So your config didn't work out of the box, I had to add extra fields, namely `name`, `modulation`, `short`
```sh
# QX-30X
#
# This decoder reads button presses from QX-302, QX-304 and QX-305 self powered
# switches. These switches appear to use an EV1527 based encoding, where the
# first 20 bits contain the device ID, the next 4 bits identify which button on
# the device was pushed, and there may be a trailing sync bit. A sample rate of
# around 1MHz is recommended to reliably detect these devices.
#

decoder {
	name        = QX,
	modulation  = OOK_PWM,
	short  	    = 33,
	long        = 100,
	gap         = 150,
	reset       = 1500,
	bits       >= 24,
	bits       <= 25,
	get         = get=@0:{20}:id,
	get         = get=@20:{4}:button,
        unique
}
```
Screenshot 2024-07-31 at 09 35 24

Also I added `unique` back and now the output looks a lot more readable:

Screenshot 2024-07-31 at 09 40 40

**Comment by zuckschwerdt** [comment]
> So your config didn't work out of the box, I had to add extra fields, namely `name`, `modulation`, `short`

Did you perhaps copy from the diff? The file seems complete (click the dots to the very right of the file name, then View File) https://github.com/merbanan/rtl_433/blob/dd57e1f879231b8c13530389284425d147681b3b/conf/qx-30x.conf

**Comment by adminy** [comment]
hahah, yeah, that's it.

**Comment by edco** [comment]
> as for two gang switch, data is mostly the same:

It seems wrong that each one would have a different device ID. But then-again, I suppose it's entirely possible that they've put a completely separate transmitter board in each of the switches, rather than trying to wire up the generators from both switches to a single board and attempting to tell the board which button is being pushed while sending a brief pulse of power to it.

It seems to me like it's working.

**Pull request merged**
