### PR TITLE
Normalize weather (rain/wind) keys

### PR DESCRIPTION
**Pull request by zuckschwerdt**
This normalizes weather (rain/wind) related keys. The change is selected only with the `newmodel` option.
The new keys are:
- `rain_mm`
- `rain_in`
- `rain_rate_mm_h`
- `rain_rate_in_h`
- `wind_avg_km_h`
- `wind_avg_mi_h`
- `wind_avg_m_s`
- `wind_max_km_h`
- `wind_max_mi_h`
- `wind_max_m_s`
- `wind_dir_deg`

Should "gust_speed_" perhaps be named "wind_gust_" to relate it closer to "wind_speed_"? Not sure, please comment.

### CODE REVIEW

**Comment by steepleian** [comment]
The use of wind together with gust (rather than gust on its own) seems to
be the more prevalent expression in the weather community.

**Comment by zuckschwerdt** [comment]
Thanks! Also nicely groups all wind related keys with a `wind_` prefix. Would it be canonical to use `wind_gust_` with `wind_speed_` or rather `wind_avg_` then?

**Comment by steepleian** [comment]
Not sure. Maybe there are some other weather enthusiasts who can contribute to the discussion.

**Comment by zuckschwerdt** [comment]
Browsing some meteorology forums I get the impression that the measurements would best described as `avg` and `peak` (or `max`). The term "gust" seems to be some specific fast wind event, not the highest value over some period.
Could really use more insight here.

**Comment by steepleian** [comment]
Both the weather data logger (WeeWX) and website template (weather34) I use
have max for wind speed gust as default.

**Comment by zuckschwerdt** [comment]
Okay, `wind_avg_` and `wind_max_` it is!

**Comment by steepleian** [comment]
OK

**Comment by dgrostoto** [comment]
I am currently making domoticz newmodel compliant, during the analysis,
I have found :
       4 "direction_deg" 
      1 "wind_direction"
can you check if it is correct ?

**Comment by zuckschwerdt** [comment]
Thanks! Yes those should be changed. I'll do this right away.

**Pull request merged**
