### PR TITLE
Update README. Improve Pulse Analyzer

### PR DESCRIPTION
**Pull request by vestom**
Fooling around with wiki formatting - but should be easier to update in future.
pulse_analyzer(): Ternary PWM detection works better. Code simplified by sorting histograms.

### CODE REVIEW

**Comment by merbanan** [comment]
Thanks

**Comment by merbanan** [comment]
Can you add code that will generate a template file for a new sensor. Ie calculate the correct pulse values and add placeholder functions?

**Comment by vestom** [comment]
Interesting idea :-) That kind of metaprogramming is a bit above my head though. Getting the whole tool-chain working is probably a bigger problem than making a stub-driver by copying an existing driver.

**Comment by ortylp** [comment]
If we assume, that pulse_analyser() detects modulation type and measures timing, then it should be possible to spit out the stub for the decoder.  Just a longer printf...

**Pull request merged**
