### PR TITLE
Add support for Kedsum Temperature/Humidity sensor

### PR DESCRIPTION
**Pull request by nebulous**
Adds support for http://amzn.to/1Y3DHb6, which was the cheapest temp/humidity sensor I could find on Amazon. Very similar to a couple of other sensors, with frustrating differences in endianness.

### CODE REVIEW

**Comment by merbanan** [comment]
Can you upload some sample signals also? Patch is ok, will merge when I get test signals.

**Comment by nebulous** [comment]
Added in tests PR 98
https://github.com/merbanan/rtl_433_tests/pull/98

**Comment by mastadook** [comment]
Is it possible somehow to get the Temperature in Celsius instead of Fahrenheit?
Any Idea?

**Comment by zuckschwerdt** [comment]
If you just need the output to ber Celsius use the `-C si` parameter. https://github.com/merbanan/rtl_433/blob/master/src/rtl_433.c#L131

**Comment by mastadook** [comment]
Thank you, that worked fine.

**Pull request merged**
