### PR TITLE
Refactor AM analyzer

### PR DESCRIPTION
**Pull request by zuckschwerdt**
Refactors the AM analyzer (-a) as well defined module.
No functional changes except the analyzer can now run alongside the decoders.
The analyzer code is mostly unchanged but isolated and properly wrapped.

### CODE REVIEW

**Comment by merbanan** [comment]
ok

**Comment by merbanan** [comment]
Does it allow the signal recorder code (-t) to either filter out the signals that a decoder picks up? Or change the name of a recorded signal when a decoder identifies it?

**Comment by zuckschwerdt** [comment]
Yes `-a` now honors the `-I` setting (`rtl_433 -a -I 1 -t` will only grab unknown signals). Changing the name sounds good, I'll work on that afterwards.

**Comment by merbanan** [comment]
Maybe even place them in specific folders. signals/known | signals/unknown, placing them in the current directory is maybe not the best option.

**Comment by zuckschwerdt** [comment]
After the analyzer is refactored I plan to split the signal grabber off and use the auto-level framing instead of that analyzers framing. Also using proper ring buffers with the input will eliminate the need to continuously copy all the input buffers :)

**Pull request merged**
