### PR TITLE
Add Carchet TPMS

### PR DESCRIPTION
**Pull request by kesuhm**
Hi, there! 

I characterized the Carchet TPMS sensor in May of last year and had wanted to perform a few additional tests before sharing.  Since my last post, I have made corrections to the checksum code and confirmed the flags for low battery and inflation detection.  I would like to share my work up to this point.

In testing the code this week, I see that the Carchet TPMS sensor is similar to the EezTire-E618 sensor added earlier this year.  The data format is the same and the flags seem to agree. Perhaps the low battery and inflate flags in the Carchet TPMS code will be useful.  Also, I characterized the sensor data in PSI and deg F, so the pressure and temperature readouts will compliment the readouts of the EezTire-E618.

This is my first pull request. I hope I have done everything correctly.

### CODE REVIEW

**Comment by zuckschwerdt** [comment]
Thanks. Do you suspect both to be the same protocol or are they just somewhat similar?

**Comment by kesuhm** [comment]
I suspect they are the same protocol, due to the identical checksum methods and fast leak and inflation flag signatures.

**Comment by zuckschwerdt** [comment]
We should then try to merge both decoders. I.e. bring your refinements and documentation to the existing decoder.

**Comment by kesuhm** [comment]
I would like to do it. This is my first time working with GitHub and I would like to learn how the procedure works. I can begin working on it on Monday.

**Comment by zuckschwerdt** [comment]
You can keep this open and just add and remove all your changes. Create new commits and push.

**Comment by kesuhm** [comment]
I'm sorry.  I've never experienced the GitHub fork, branch, clone, edit, commit, push, pull request sequence before. I didn't realize the enticing green button would create a new PR number every time I pushed it.

**Comment by kesuhm** [comment]
I have merged the Carchet TPMS code with the EezTire code. It is ready for review.

**Comment by zuckschwerdt** [comment]
The code is manually merged with a7e5aaf

**Pull request closed without merging**
