### PR TITLE
change array separator in csv to ";"

### PR DESCRIPTION
**Pull request by zuckschwerdt**
otherwise RadioHead ASK output will break csv parsers

### CODE REVIEW

**Comment by merbanan** [comment]
This might upset some people.

**Comment by merbanan** [comment]
Maybe let it be configurable ?

**Comment by zuckschwerdt** [comment]
ah, no. i worded that badly. CSV is still Comma separated ;) This is about the nested separator in data arrays. No device except RadioHead ASK uses this: https://github.com/merbanan/rtl_433/blob/master/src/devices/radiohead_ask.c#L145

**Comment by zuckschwerdt** [comment]
I.e.
```
time,model,id,nested_array,foo
@1,test_no_array,42,,bar
@2,test,42,[a,b,c,d,e],bar
```
now is properly
```
time,model,id,nested_array,foo
@1,test_no_array,42,,bar
@2,test_with_array,42,a;b;c;d;e,bar
```
Sorry if I gave anyone a heart attack ;)

**Comment by merbanan** [comment]
All good then.

**Pull request merged**
