### PR TITLE
hideki.c with support for rain sensor

### PR DESCRIPTION
**Pull request by Matthies**
This is for ludwich66: Attached a zipped hideki.c that may recognize the rain sensor. Please test and check if the rain data increases in a reasonable way. Seems that is just has an overall counter and the waetherstation calculates current rain / last hour / last 24h by storing the values in these intervalls.

[hideki.c.zip](https://github.com/merbanan/rtl_433/files/587892/hideki.c.zip)

### CODE REVIEW

**Comment by ludwich66** [comment]
Hi Matthies, thank you. tomorrow i take a longer test. i have received 5 Samples now.
the differences between the values are looking good.
The Batterylevel is LOW, the display has no "Low Level" Indikator. a first measured value on the sensor means 3,1 V. i don't know where the trigger between OK and LOW, but there is no sign on the display.
is it a misinterpretation of the received data?
-tomorrow i made the rocker quieter - it is very loud at the moment :-)

ludwich

**Comment by Matthies** [comment]
The battery level flag may be wrong, I just copied it from the temperature sensor.
Maybe you could try if the station shows some low battery sign if you use older batteries and then send some data files recorded when using these batteries.

**Comment by ludwich66** [comment]
Great,good news
 i test it with a powersupply today.
did you use the gfile-testdata from the comment or from the pullrequest on rtl_433-test?

ludwich

**Comment by ludwich66** [comment]
Hi Matthies,

very difficult to catch data, i hope this part is with the Bat Low indicator.
The receiver in the mainterminal is not good, the rtl-sdr stick is better.
i lost the connection to the base earlyer then the stick, but there is no control. the reading is always LOW.

i hope you can use this file.

ludwich

**Comment by merbanan** [comment]
Sorry guys but open a ticket for these kind of discussions, the patch in this ticket is totally unrelated. I took a look at the code in the hideki.c.zip and while it looked good there are some questions about it. @Matthies  can you send a new pull request that I can review ?

**Comment by Matthies** [comment]
Sorry for spamming your github repository. I tried to comment in the ludwich66 branch/pull request but obviously failed. Sending an email directly to a github member seems impossible, that's what I searched for.

Will try to create a new pull request with commit comments and data files and everything needed next weekend.

 

. Andreas

 

Gesendet: Montag, 14. November 2016 um 23:37 Uhr
Von: "Benjamin Larsson" <notifications@github.com>
An: merbanan/rtl_433 <rtl_433@noreply.github.com>
Cc: Matthies <a.matthies@online.de>, Mention <mention@noreply.github.com>
Betreff: Re: [merbanan/rtl_433] hideki.c with support for rain sensor (#443)


Sorry guys but open a ticket for these kind of discussions, the patch in this ticket is totally unrelated. I took a look at the code in the hideki.c.zip and while it looked good there are some questions about it. @Matthies can you send a new pull request that I can review ?

**Pull request closed without merging**
