### PR TITLE
Change CurrentCost and EfergyOptical keys to have units

### PR DESCRIPTION
**Pull request by zuckschwerdt**
Change some remaining keys to use a suffix of `_W` and `_kWh`.
Note this is breaking and needs a corresponding change in rtl_433_tests.

### CODE REVIEW

**Comment by merbanan** [comment]
LGTM

**Comment by merbanan** [comment]
My PR will also need tests changes.

**Comment by zuckschwerdt** [comment]
I have a some batch check/update working, I can just run the test updates after you merge. Otherwise try:
```
for f in tests/DEVICE/**/*.cu8 ; do rtl_433 -c 0 -F json -r $f >${f%.cu8}.json ; done
```

**Comment by merbanan** [comment]
Yeah, that went bad. Thought it would fix the conflict.

**Comment by merbanan** [comment]
Can you rebase or something?

**Comment by zuckschwerdt** [comment]
no problem :)

**Comment by merbanan** [comment]
Can this be merged?

**Pull request merged**
