### PR TITLE
Added support for FineOffset/ECOWITT WH51

### PR DESCRIPTION
**Pull request by 0x4d0x44**

### CODE REVIEW

**Comment by merbanan** [comment]
mic needs to be added.

**Comment by zuckschwerdt** [comment]
Note:
- mic needs to be added to `output_fields_WH51` too.
- key order should be "model", "id", "battery", "moisture", "boost", "ad", "mic" (i.e. battery up, boost down).
- battery should be battery_mV.
- `ad` is rather short, there might be a better key name.
- `sprintf( id, "%2.2x%2.2x%2.2x", ` should be  `sprintf(id, "%2x%2x%2x", `

**Comment by merbanan** [comment]
Committed a fix.

**Comment by zuckschwerdt** [comment]
We don't have samples for this?

**Pull request merged**
