### PR TITLE
initial implementation for GT_WT_02 decoder

### PR DESCRIPTION
**Pull request by ortylp**
This is initial implementation that works with the data we have.

We need more examples.  We need to reverse engineer the last set of bits, hopefully, some kind of CRC.

See also Issue  #117

### CODE REVIEW

**Comment by merbanan** [comment]
+static int gt_wt_02_process_row(int row, const bitbuffer_t *bitbuffer);
+static int gt_wt_02_callback(bitbuffer_t *bitbuffer)

Change the order so you don't need to forward declare the function.

+    printf("%s GT-WT-02 Sensor %02x: battery %s, channel %d, button %d, temperature %3.1f C / %3.1f F, humidity %2d%%\n"

use fprintf

+    time_t time_now;

Timestamp printout does not belong in the decoder. We should add some global handling of timestamp, not sure how yet so you can keep it if you add a comment about it.

+float celsius2fahrenheit(float celsius)

The output should be what the user configures it to be, but as we don't have the supporting code yet just add a comment about it.

If you fix these issues I will then merge the code.

**Comment by ortylp** [comment]
I am on it.

**Comment by ortylp** [comment]
I do agree, that we need infrastructure supporting the following:
1/ printing should be put outside of the decoder
2/ time stamps should be also outside of the decoder but based on the time stamp provided by the decoder (bitbuffer must support timestamps)

In my use case the time stamp is essential and a single package must fit its information on a single line, so that unix text processing tools (grep/awk/sed/perl) can work with it without additional code.

**Comment by merbanan** [comment]
I agree on all points. I think the thread about the output format has some relevant info regarding this.

**Comment by ortylp** [comment]
Can you point me to the thread?  Is it an issue on Github, do we have wiki to document requirements on this?

**Comment by merbanan** [comment]
It's a google groups thread:

Proposal: Output to stdout and adding timestamps to the output

https://groups.google.com/forum/#!topic/rtl_433/2mTMjihXbRg

**Comment by ortylp** [comment]
"You do not have permission to view this content."

**Comment by merbanan** [comment]
https://groups.google.com/forum/#!forum/rtl_433

**Comment by merbanan** [comment]
Search for the topic "Proposal: Output to stdout and adding timestamps to the output".

**Comment by merbanan** [comment]
I have now changed the setting so anyone should be able to read topics in this group. I just didn't know this setting was active.

**Comment by ortylp** [comment]
@merbanan do you want me to change anything more, or we "wait" until we figure out the CRC stuff?

**Comment by merbanan** [comment]
Nope thanks for the update.

**Pull request merged**
