### PR TITLE
Sonoff RM433

### PR DESCRIPTION
**Pull request by jkx**
I just added support for Sonoff RM433 remote control. Tested w/ 3 differents remote without issues.
Could you please merge this on the official distribution.

### CODE REVIEW

**Comment by zuckschwerdt** [comment]
Thanks. We support simple remotes with the flex decoder. There are some examples in the [conf folder](https://github.com/merbanan/rtl_433/tree/master/conf).
Can you please write this as a conf file for the flex decoder?

**Comment by zuckschwerdt** [comment]
Basically this should work:
```
rtl_433 -X 'n=Sonoff-RM433,m=OOK_PWM,s=260,l=744,r=8000,g=800,t=50,bits>=24,invert,get=@20:{4}:button:[8:A 12:B 4:C 9:D 2:E 5:F 1:G 3:H],unique'
```

**Comment by jkx** [comment]
This works quite well.

time      : 2019-09-15 23:21:09
model     : Sonoff-RM433 count     : 5             num_rows  : 5
len       : 25           data      : 6365080
button    : A
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2019-09-15 23:23:22
model     : Sonoff-RM433 count     : 7             num_rows  : 7
len       : 25           data      : 6365040
button    : C

The only issue I see, is that the remote ID is missing. I don't want to 
parse data to extract the remote ID.
Is there a way to extract ID too ?


Thanks.

**Comment by zuckschwerdt** [comment]
Yes, the syntax is quite **flex**ible ;) As conf file use e.g.
```
decoder {
    name=Sonoff-RM433,
    modulation=OOK_PWM,
    short=260,
    long=744,
    reset=8000,
    gap=800,
    tolerance=50,
    bits>=24,
    invert,
    get=@0:{20}:id,
    get=@20:{4}:button:[8:A 12:B 4:C 9:D 2:E 5:F 1:G 3:H],
    unique
}
```
If you like test and comment that and submit as conf (in this PR).

**Comment by jkx** [comment]
That works fine. I don't know how to submit this as conf.. ouups. 
Could you please do it. 

Thanks for support.

**Comment by jkx** [comment]
The last commit should be Ok. Hope this helps. 
Thanks

**Comment by zuckschwerdt** [comment]
I've merge the conf from your PR, with attribution. Thanks!

**Pull request merged**
