### PR TITLE
convert dsc output to JSON

### PR DESCRIPTION
**Pull request by dmcwhinnie**
Not the prettiest way to create JSON, but it was only a single printf statement so escaped the quotes and added the {}

### CODE REVIEW

**Comment by zuckschwerdt** [comment]
It would be grerat if you could convert this device to the `data_make()` format. JSON is for free then :)
(just push more commits on top in this PR.)

**Comment by zuckschwerdt** [comment]
Can you test if #725 (branch [`feat-dsc`](https://github.com/zuckschwerdt/rtl_433/tree/feat-dsc)) works for you?

**Comment by dmcwhinnie** [comment]
Sorry for the delay... Yes, I will test, but may not be until next week.

**Comment by rct** [comment]
FWIW, I have a version that does data_make and I've broken out the bits in a way that I think is sensible (to me as the original author), but I was waiting on the boolean issue, since the output is basically boolean.

**Comment by rct** [comment]
with PR #730 the output looks like the following.  This is somewhat temporary aid for the transition between the old unstructured data and structured.  The status bits are much easier to interpret when output as hex.   I will break out the bits in a new PR within a few days.

```
{"time" : "2018-05-23 09:50:16", "model" : "DSC Contact", "id" : 3520320, "esn" : "35b740", "status" : 161, "status_hex" : "a1", "mic" : "CRC"}
```

**Pull request closed without merging**
