### PR TITLE
Added DATA_BYTE 

### PR DESCRIPTION
**Pull request by FuzzIO**
Added support for DATA_BYTE, which is a uint8_t data (one byte). This is useful to print out raw byte values and compatible with the DATA_ARRAY structure. The output is printed in hexadecimal values.

### CODE REVIEW

**Comment by zuckschwerdt** [comment]
This is covered with DATA_INT + DATA_FORMAT, isn't it?

We don't like to add more types to data_t if there isn't a very solid reason like memory management or mapping requirements in the outputs.

I guess an array type might be more compact with shorter values then int, but it shouldn't be that long anyway.

There were ideas about a DATA_BITROW type, but that is more intrusive (fat pointer) and of limited value, rtl_433 really should decode bytes.

**Comment by FuzzIO** [comment]
The use case I have encountered was that I had to work on decoding a device with fields that were unknown. The unknown field could be archived as an array of bytes in the file output for ulterior analysis or if we needed it. 
Using DATA_FORMAT and DATA_INT consumed 32 bits (the size of int). As the value of interest was a Byte (8 bit), 32-bit was too much. 
Also, when a field covers more than one byte, but is not a multiple of 4 bytes (again, size of an int), declaring a DATA_ARRAY with DATA_INT would not cover the value properly. 

Let me know if more explanations are needed or if you think my use case could be handled with existing data structures. I did try before implementing DATA_BYTE, but I may have missed something.

Cheers!

**Comment by FuzzIO** [comment]
An example of  this is if a source and a destination address are encoded on a number of bytes unaligned with an int (e.g. 24 bits or 48 bits). Displaying the output in a an array of byte would then make sense. Again, let me know if something is already existent that covers this use case. More than happy to avoid "reinventing the wheel" !

**Comment by FuzzIO** [comment]
Here is an example that could be representative for a device.
```
data_make(
...
"raw",              "Raw data",      DATA_ARRAY, data_array(9, DATA_BYTE, byte_buffer)
...
)
```
Produces something like : 
image

**Comment by zuckschwerdt** [comment]
I see. Using a DATA_ARRAY is not recommended for general use. Some outputs don't handle that well.
In this case you likely want `bitrow_snprint()` to a buffer of sufficient size, then DATA_STRING as output.

**Comment by zuckschwerdt** [comment]
This should be picked up again – the main idea is a `DATA_STRING` variant with unsafe bytes vs. a hex formatted actual `DATA_STRING`.

**Comment by gdt** [comment]
Status?   still on the table, should be closed, something else?

**Comment by zuckschwerdt** [comment]
The verdict is: no to the change as-is but generally yes to the idea of some raw `DATA_STRING`.

**Comment by gdt** [comment]
So therefore close this PR, and if there is DATA_STRING later, we are happy to look at it?

**Comment by zuckschwerdt** [comment]
Yes, close. The implementation is good, and sound in principle, but we don't want more types in data_t.

The `DATA_STRING` currently prints as-is and there could be a variant that prints as hex. This needs a good case (e.g. some output that makes use of a better representation) to be really useful as we can just print to hex and use plain `DATA_STRING` right now.

**Pull request closed without merging**
