### PR TITLE
Add support for BTHGN129

### PR DESCRIPTION
**Pull request by sbsrouteur**

### CODE REVIEW

**Comment by merbanan** [comment]
Hi, you need to rebase this patch before I can merge it. Looks ok otherwise. And send samples if they are missing.

**Comment by sbsrouteur** [comment]
Yes, I just figured, I was behind. As soon as GitHub let's me get back your last changes, I'll update the PR. I have a sample file as well, i'll PR it right after.

**Comment by merbanan** [comment]
There are still conflicts and I can not merge it via the webgui. You need to rebase and fix your patch set again.

**Comment by sbsrouteur** [comment]
incredible, it seems to work :)

**Comment by merbanan** [comment]
Ok, now it is possible to merge it, but you add 5 files ? Get rid off them and I can merge the patch.

**Comment by sbsrouteur** [comment]
ok. 9 commits for 1 file change there's room for improvement.

Sorry for this.

**Comment by merbanan** [comment]
Haha :) patch merged.

**Pull request merged**
