### PR TITLE
Add celsius to Acurite 986 fridge temperature sensor

### PR DESCRIPTION
**Pull request by NorthernMan54**
Added Celsius to Acurite 986 Fridge temperature sensor

### CODE REVIEW

**Comment by merbanan** [comment]
Use -C si, it will convert to SI units. It is by design to report the native representation from the sensor.

**Comment by NorthernMan54** [comment]
Not to quibble, but output from "rtl_433 -F json -q -C si" shows

{"time" : "2018-06-02 20:13:29", "model" : "Acurite 986 Sensor", "id" : 28331, "channel" : "1R", "temperature_F" : 39, "battery" : "OK", "status" : 0}

**Comment by merbanan** [comment]
Issue confirmed, and issue should be fixed if you pull the repo.

**Comment by NorthernMan54** [comment]
@merbanan Tks, that works perfectly

**Pull request closed without merging**
