### PR TITLE
Add conditional to data_make

### PR DESCRIPTION
**Pull request by zuckschwerdt**
This adds a `DATA_COND` option to `data_make()` to simplify skipping conditional keys.

### CODE REVIEW

**Comment by zuckschwerdt** [comment]
E.g.
```
    data = data_make(
            "humidity",         "Humidity",     DATA_FORMAT, "%u %%", DATA_INT, humidity,
            NULL);
    if (pressure_raw != 0xffff) {
        data = data_append(data,
                "pressure_hPa",     "Pressure",     DATA_FORMAT, "%.01f hPa", DATA_DOUBLE, pressure,
                NULL);
    }
    data = data_append(data,
            "mic",              "Integrity",    DATA_STRING, "CRC",
            NULL);
```

is simplified to

```
    data = data_make(
            "humidity",         "Humidity",     DATA_FORMAT, "%u %%", DATA_INT, humidity,
            "pressure_hPa",     "Pressure",     DATA_COND,   pressure_raw != 0xffff, DATA_FORMAT, "%.01f hPa", DATA_DOUBLE, pressure,
            "mic",              "Integrity",    DATA_STRING, "CRC",
            NULL);
```

**Comment by zuckschwerdt** [comment]
This could also be used to clean up model keys and make it easier to parse for a summary:
```
            "model", "", DATA_STRING, type == 31 ? "Fineoffset-WH32" : type == 32 ? "Fineoffset-WH32B" : _X("Fineoffset-WH25","Fine Offset Electronics, WH25"),
```
becomes
```
            "model", "", DATA_COND, type == 31, DATA_STRING, "Fineoffset-WH32",
            "model", "", DATA_COND, type == 32, DATA_STRING, "Fineoffset-WH32B",
            "model", "", DATA_COND, type == 27, DATA_STRING, _X("Fineoffset-WH25","Fine Offset Electronics, WH25"),
```
But I'm not sure if that's a good use.

**Comment by zuckschwerdt** [comment]
@merbanan does this look sensible? Is `DATA_COND` a good label?

**Comment by zuckschwerdt** [comment]
The example is for #1431 and should be applied in fineoffset.c

**Comment by merbanan** [comment]
The idea is good, I have not looked through the code logic in detail. But if there are any issues the change is small so it will be easy to fix. So PR is ok.

**Comment by zuckschwerdt** [comment]
It's just 12 lines. everything below the line 268 `else {` is indentation only.

**Pull request merged**
