### PR TITLE
Improve bresser_7in1.c excluding init wrong BCD values

### PR DESCRIPTION
**Pull request by ProfBoc75**
Related to the issue #2816 , first signal is sending 0x0F values, which is not possible for BCD that can't be > 0x09.

This PR is to exclude these values through a simple DATA_COND formatting.

### CODE REVIEW

**Comment by Mart124** [comment]
@ProfBoc75 strangely enough, since this commit (and #2830), rtl_433 does not receive values from my VOC/HCHO sensor anymore.
No issue with PM2.5/PM10 and CO2 sensors (even better, as wrong values are now properly ignored).

At least I think there's a small bug here :
```
        int hcho_init = (msg[5] & 0x0f) == 0x0f;
        int voc_init  = voc == 0x0f;
```
I think we should only rely on `voc_init`, as VOC value of 15 can't exist, it's out of scale (5 max here).
On the contrary, a proper HCHO value of 15 can be expected.
So I think we should use `voc_init` in place of `hcho_init` in the HCHO `DATA_COND`.
Or we would miss proper HCHO values of 15...

But even with this, I can't see why rtl_433 does not receive values from this device anymore.
Did you manage to replay against samples from the initial device report (#2814) ?

Thank you again 👍

**Comment by Mart124** [comment]
Mmmh I finally may be wrong with my `voc_init` vs `hcho_init` proposal above, as per what you stated a few lines above in the code of this PR :
```
#2816 Bresser Air Quality sensors, ignore first packet:
    The first signal is not sending the good BCD values , all at 0xF and need to be excluded from result (BCD value can't be > 9) .
```
So should not be an issue...

**Comment by Mart124** [comment]
OK, found the culprit, @zuckschwerdt renamed the device in https://github.com/merbanan/rtl_433/commit/4c5081dbba8ac3a95a169425f8e28ca2c2e10746 :)
Sorry for the noise...

**Comment by zuckschwerdt** [comment]
Oops sorry, yes. We have strict naming rule https://triq.org/rtl_433/DATA_FORMAT.html#message-data

**Pull request merged**
