### PR TITLE
Add support for LaCrosse LTV-TH3 Thermo/Hygro sensor

### PR DESCRIPTION
**Pull request by mbruski**
Adding a decoder for the LaCrosse Technology View TH3 Thermo/Hygro sensor which transmits FSK-PCM encoded packets containing temperature and humidity data.

### CODE REVIEW

**Comment by mbruski** [comment]
Christian, I think I goofed this.   I had added two sensor files but I guess I should have done them one at a time.  There is another sensor (LTV-WR1 Multi-Sensor) being added as well.  The WR1 outputs wind speed, wind direction and rainfall data.  The rainfall data in the present decoder is 'raw' direct from the sensor.  Can't figure out at this time how to translate the numbers into rain_mm.

Mike

**Comment by zuckschwerdt** [comment]
Looks good. Can you clean up the whitespace errors (tabs and trailing spaces) from [the first file](https://github.com/merbanan/rtl_433/pull/1529/files), just add a commit.
This `temp_c = (float)raw_temp * 0.1 - 40.0;` should be written `temp_c = (raw_temp - 400) * 0.1f;` so it is one integer operation and one float, instead of two double ops.

**Comment by mbruski** [comment]
Not sure how that first file (lacrosse-LTV-WSDTH01.c file got in there.   That was from a commit a couple months ago.  I guess I need to refresh my branch here but don't know how to do that.  Anyway, the lacrosse-wr1.c and lacrosse-th3.c files are the two I intended to submit.

**Comment by mbruski** [comment]
Could you remove this pull request and I'll try again?

**Comment by zuckschwerdt** [comment]
You can just push new commits to this branch.

**Comment by mbruski** [comment]
Christian,I deleted the old branch and created a new one (but named it incorrectly -- don't think that matters though -- I'm still learning how to use git).  Added new file lacrosse-wr1.c and updated associated build files before doing commit.  Do I need to create another pull request?  Can I now update for lacrosse-th3.c or do I wait for you to merge wr1?MikeSent from Samsung Galaxy smartphone.
-------- Original message --------From: "Christian W. Zuckschwerdt" <notifications@github.com> Date: 10/23/20  08:19  (GMT-05:00) To: merbanan/rtl_433 <rtl_433@noreply.github.com> Cc: Mike <aj9x@comcast.net>, State change <state_change@noreply.github.com> Subject: Re: [merbanan/rtl_433] Add support for LaCrosse LTV-TH3 Thermo/Hygro sensor (#1529) 
You can just push new commits to this branch.

**Comment by zuckschwerdt** [comment]
If you have made changes either try to name the branch same as before ("mbruski-patch-1") an again push. That should then again appear here I guess. If that doesn't work open a new PR.

But If you havn't made any changes then I can just pick the two files from here.

**Comment by mbruski** [comment]
My new branch name is feat-ltv-th3.  I did the commit but guess I need a new PR.  I'll get the hang of this yet.  Thanks for your patience.MikeSent from Samsung Galaxy smartphone.
-------- Original message --------From: "Christian W. Zuckschwerdt" <notifications@github.com> Date: 10/23/20  11:32  (GMT-05:00) To: merbanan/rtl_433 <rtl_433@noreply.github.com> Cc: Mike <aj9x@comcast.net>, State change <state_change@noreply.github.com> Subject: Re: [merbanan/rtl_433] Add support for LaCrosse LTV-TH3 Thermo/Hygro sensor (#1529) 
If you have made changes either try to name the branch same as before ("mbruski-patch-1") an again push. That should then again appear here I guess. If that doesn't work open a new PR.
But If you havn't made any changes then I can just pick the two files from here.

**Comment by mbruski** [comment]
So, help me out here if you can.  I did a git clone on Master to my laptop and created feat-ltv-th3 there.  Added my new decoder, updated the appropriate .h, .am, .vcxproj & filter, and CMakeLists.txt files.  Did git add for each then git commit.  This is all on my laptop.  Now I need to go to web and create a PR.  How do I find that branch on the web or do I need to do a push first?MikeSent from Samsung Galaxy smartphone.
-------- Original message --------From: "Christian W. Zuckschwerdt" <notifications@github.com> Date: 10/23/20  11:32  (GMT-05:00) To: merbanan/rtl_433 <rtl_433@noreply.github.com> Cc: Mike <aj9x@comcast.net>, State change <state_change@noreply.github.com> Subject: Re: [merbanan/rtl_433] Add support for LaCrosse LTV-TH3 Thermo/Hygro sensor (#1529) 
If you have made changes either try to name the branch same as before ("mbruski-patch-1") an again push. That should then again appear here I guess. If that doesn't work open a new PR.
But If you havn't made any changes then I can just pick the two files from here.

**Comment by merbanan** [comment]
When you do a push, the client will respond with a url you can open to create a PR.

**Comment by mbruski** [comment]
Whoa pony.  When I do the push, its trying to access merbanan/rtl_433 , not mbruski/rtl_433.  Obviously I'm doing something wrong.  Help please?MikeSent from Samsung Galaxy smartphone.
-------- Original message --------From: Benjamin Larsson <notifications@github.com> Date: 10/23/20  11:52  (GMT-05:00) To: merbanan/rtl_433 <rtl_433@noreply.github.com> Cc: Mike <aj9x@comcast.net>, State change <state_change@noreply.github.com> Subject: Re: [merbanan/rtl_433] Add support for LaCrosse LTV-TH3 Thermo/Hygro sensor (#1529) 
When you do a push, the client will respond with a url you can open to create a PR.

**Comment by merbanan** [comment]
Fork merbanan/rt_433.

Check out mbruski/rtl_433
Create branch
Commit code
Push branch (this should now offer to create PR via url)

**Comment by mbruski** [comment]
Good enough, can do.  I assume the last commit I did earlier is in limbo and will just disappear into the ether?Thanks for your help.MikeSent from Samsung Galaxy smartphone.
-------- Original message --------From: Benjamin Larsson <notifications@github.com> Date: 10/23/20  13:18  (GMT-05:00) To: merbanan/rtl_433 <rtl_433@noreply.github.com> Cc: Mike <aj9x@comcast.net>, State change <state_change@noreply.github.com> Subject: Re: [merbanan/rtl_433] Add support for LaCrosse LTV-TH3 Thermo/Hygro sensor (#1529) 
Fork merbanan/rt_433.
Check out mbruski/rtl_433
Create branch
Commit code
Push branch (this should now offer to create PR via url)

**Comment by mbruski** [comment]
One last question if you don't mind.  I have a two month old fork 'mbrusli/rtl_433' but it is 53 commits behind 'merbanan:master' on my web page.  How do I bring it up to date so I'm working with the latest and greatest master?  Thanks.MikeSent from Samsung Galaxy smartphone.
-------- Original message --------From: Benjamin Larsson <notifications@github.com> Date: 10/23/20  13:18  (GMT-05:00) To: merbanan/rtl_433 <rtl_433@noreply.github.com> Cc: Mike <aj9x@comcast.net>, State change <state_change@noreply.github.com> Subject: Re: [merbanan/rtl_433] Add support for LaCrosse LTV-TH3 Thermo/Hygro sensor (#1529) 
Fork merbanan/rt_433.
Check out mbruski/rtl_433
Create branch
Commit code
Push branch (this should now offer to create PR via url)

**Comment by merbanan** [comment]
You need to rebase it against the remote master branch. I suggest you look at some tutorials regarding this. The thing with git is that when you understand the logic behind it you know what you need to to. But before it is a little complex.

**Comment by zuckschwerdt** [comment]
continued in #1533

**Pull request closed without merging**
