### PR TITLE
new command line option -C native | f-to-c | c-to-f

### PR DESCRIPTION
**Pull request by zuckschwerdt**
Introduces new command line option `-C native | si | customary` that hooks into `data_acquired_handler` and
if `si` and type is DATA_DOUBLE and key is temperature_C then celsius2fahrenheit,
if `customary` and type is DATA_DOUBLE and key is temperature_F then fahrenheit2celsius.
Also if there is a FORMAT the last character "C" / "F" will be switched accordingly.

See discussion at https://github.com/merbanan/rtl_433/issues/260

Written for and tested with
```
alecto.c:
  "temperature_C", "Temperature", DATA_FORMAT, "%.02f C", DATA_DOUBLE, (float) temp / 10.0F,
ambient_weather.c:
  "temperature_F", "", DATA_FORMAT, "%.1f", DATA_DOUBLE, temperature,
hideki.c:
  "temperature_C", "Temperature",   DATA_FORMAT, "%.02f C", DATA_DOUBLE, temp/10.f,
oil_watchman.c:
  "temperature_C", "", DATA_DOUBLE, temperature,
oregon_scientific.c:
  "temperature_C", "Temperature", DATA_FORMAT, "%.02f C", DATA_DOUBLE, get_os_temperature(msg, sensor_id),
prologue.c:
  "temperature_C", "Temperature", DATA_FORMAT, "%.02f C", DATA_DOUBLE, temp,
wt450.c:
  "temperature_C", "Temperature",DATA_FORMAT, "%.02f C", DATA_DOUBLE, temp,
```

### CODE REVIEW

**Comment by rct** [comment]
Perhaps thinking ahead for the weather stations, the command line args should be native|metric|english?   

We might want to handle KmPH <-> MPH, MM <-> IN., etc.

**Comment by rct** [comment]
(at this point only suggesting a change to the command line arguments, since I don't know if there are any weather stations using the new data format routines, I know the Acurite doesn't yet.)

**Comment by zuckschwerdt** [comment]
I thought of using a bit field later on for extensibility, but your suggestion is even better!
(also it might be worthwhile to consider introducing even more structure into the data fields, e.g. explicit units, significant digits. Or maybe to encourage a common structure for the FORMAT string.
I could make a table on the current practice and all current units if something in this direction is wanted.

**Comment by zuckschwerdt** [comment]
Can someone check if "english" is what we want to convey here? According to Wikipedia there seems to be "imperial", "english" and "U.S. customary".
I've always though Fahrenheit and Inches to be "imperial" but I can't make sense of it anyway ;)

**Comment by rct** [comment]
Nothing is ever simple.  ;-)

I'm fine wih imperial, but I'm sure there are some other opinions.   Some weather related sources I check didn't really have consensus, and add S.I. To the mix for the metric side.

**Comment by zuckschwerdt** [comment]
As far as I could gather (https://en.wikipedia.org/wiki/Imperial_and_US_customary_measurement_systems) "english" is pre-1824 and "imperial" users now all converted to metric. So we are really talking about "U.S. customary" here. But "us-customary" isn't a nice option value at all.
People with a stake in using that option need to speak up :)

**Comment by merbanan** [comment]
Native, si and customary.

A bit boring but somewhat correct. Imperial units or simplified English units would have been fun also but confusing.

Patch ok otherwise.

**Comment by eras** [comment]
Further development ideas: with this I think it might be a good idea to go away with the DATA_FORMAT being used to format temperatures and just always format temperature_C and temperature_F values with some common format string, such as the "%.2f C" or "F" every code uses anyway..

And to go a bit further would be to add actual type to the data side, so in addition to DATA_DOUBLE there would be DATA_UNIT_C or even DATA_ABS_TEMP, DATA_UNIT_C. This would work better if there are sensors that have multiple measured values we wish to convert between and can't expect them all to have a predefined name.

**Comment by zuckschwerdt** [comment]
Most likely we'd need to keep data type (and maybe precision) separate from the units. E.g. humidity is usually an integer, and then there is one sensors reporting a float...

**Comment by zuckschwerdt** [comment]
I changed the code (and squashed the commit) to `native | si | customary`.

**Pull request merged**
