### PR TITLE
Add support for the Govee Water Leak Detector H5054 and Govee Contact Sensor B5023

### PR DESCRIPTION
**Pull request by skilau**
Add support for the Govee Water Leak Detector H5054 and the Govee Contact Sensor B5023.

This is a basic driver for what is a basic (but quite nice) water leak sensor, as well as their contact sensor.

https://www.govee.com/products/110/water-leak-detector
https://www.govee.com/products/27/govee-door-contact-sensor

Pulled most of the info from this running thread:
https://github.com/merbanan/rtl_433/issues/1518

I have 5 of these leak sensors, and was able to test:
1) Each sensor has a unique ID value.
2) Button Press.
3) Water Leak.
4) Battery 5 Bars.
5) Battery 4 Bars.
6) Battery 1 Bar.

Unable to test Battery bars 2 and 3.
(But took the Event data for both of those from the thread mentioned above)

I also have 2 of the Contact Sensors, and was able to test both for:
1) Open.
NOTE: The sensor does not support sending a Close event.  This unfortunately makes this sensor far more limited in its actual uses in the real world.

### CODE REVIEW

**Comment by skilau** [comment]
Updated to pull in all latest changes from master branch...

Also just checking in, is there anything else that is needed for this to get accepted patch into the main repo/branch?

I know there are a couple others using my forked branch for this Govee support, and it would be nice to allow them to grab from the real/main repo instead of mine.

Just let me know if I missed something, I am more than happy to correct it.

Thank you!

**Comment by zuckschwerdt** [comment]
Looks nice so far.
- Decode func should be `govee_water_h5054_decode`
- Put `/* clang-format off */`and `/* clang-format on */` around data_make, see other decoders
- Don't use _X, just "Water-H5054"
- Indent e.g. "model" by 2 levels, 8 spaces, also in r_device
- Remove `.disabled = 0,`

**Comment by skilau** [comment]
Thanks for the code review, I really appreciate it!
I have made the changes as requested, let me know if there is anything else I need to change/add.
Thanks again for your help, and your project!

**Comment by skilau** [comment]
NOTE:  Updated this driver to support the Govee Contact sensor B5023:
https://www.govee.com/products/27/govee-door-contact-sensor

In doing so, I have made the driver a more "generic" Govee driver, to possibly support other Govee products in the future.

Let me know if there is anything else that should be done, to get this driver to be considered for inclusion in the main release of rtl_433.

Thank you!

**Comment by zuckschwerdt** [comment]
Looks good!
- Line 4 should look like any other decoder file, author information, not  model details.
- Can you add "battery_ok" with a float value of `bars * 0.2f`? This matches other decoders for that very common key.
- We would generally like each event to output a key with value `1`. This helps consumers to parse this.
  E.g. `"button", "Button press", DATA_COND, button, DATA_INT, 1,` -- if this is practical here?

**Comment by ideal2545** [comment]
Hi sorry to bump this, I want to add some of these devices, is there a specific protocol number to use with this driver? 

Devices: https://www.amazon.com/gp/product/B07QSFRSJX

**Comment by zuckschwerdt** [comment]
You need to checkout and compile this branch for now. I need to get around to finally test and merge this.

**Comment by aav7fl** [comment]
@zuckschwerdt Is there anything we can do to help test this? It sounds like a few people have been using this PR branch to support their Govee sensors for a bit. https://github.com/merbanan/rtl_433/issues/1518

**Comment by zuckschwerdt** [comment]
We still want to known what the last two bytes do. There is likely a checksum, which would improve the reliability.

This decoder is now merged, please everybody collect distinct Raw Code output so we can figure this out.

**Comment by drew-hill** [comment]
Is this what turned into Protocol 192 or Protocol 231? I am currently unable to load Protocol 231 with the error: "Protocol number specified (231) is larger than number of protocols" on v22.11, and I'm wondering if maybe they two were merged and the list of supported device protocols was not updated?

**Comment by skilau** [comment]
> Is this what turned into Protocol 192 or Protocol 231? I am currently unable to load Protocol 231 with the error: "Protocol number specified (231) is larger than number of protocols" on v22.11, and I'm wondering if maybe they two were merged and the list of supported device protocols was not updated?

Yes, this patch was eventually turned into 192, and is what I am using for my Govee water sensors now.
(And have been for a couple years now)

I haven't been watching the patches since then, since this driver works well, so I was surprised to see a new number 231 added.

After quickly looking at the new code, I see what and why it was added...
Apparently Govee changes the protocol a bit on newer versions of the sensor, and so 231 was added to capture that change.

You can see that patch set here:
https://github.com/merbanan/rtl_433/commit/4b6dc283824970b744d3f6e69a0d1172f68b33ae

So you will need to determine which hardware you have. (New or Old).
If it is old, you can use 192.
If it is new, you will need to use a more current version of rtl_433 than you are using, and then use the new 231 Protocol.

**Comment by drew-hill** [comment]
Thanks so much. This is super helpful.

**Comment by drew-hill** [comment]
I'm still unable to pull in any Protocols above 223 on v22.11 on my computer or on my separate Home Assistant device. Has anyone else had this problem? I'm considering starting an issue -- search currently pulls up 0 matches in Issues at the moment -- but imagine I'm probably just doing something stupid as an rtl_433 newbie.

**Pull request merged**
