### PR TITLE
Add stats reporting

### PR DESCRIPTION
**Pull request by zuckschwerdt**
early WIP, not for merge. s.a. #727

Adds an experimental undocumented option `-L` for stats reporting:
- 0: do not report (default)
- 1: report successful devices
- 2: report active devices
- 3: report all

Test with e.g. `rtl_433 -q -F json -L 1 -T 60`

### CODE REVIEW

**Comment by merbanan** [comment]
One thing somewhat related to this is that I would like to get the SNR of the signals. That way one could see if the signal from the device is good or not. I though of using the energy in the carrier and the silence as components for this. Together with the rejected statistics one could get limits to adjust ones setup against.

**Comment by merbanan** [comment]
In the OOK case, FSK should be easier as the signal is always there.

**Comment by zuckschwerdt** [comment]
You are right, it's an incompatible extension. I went with `dd`s interface there, for testing Ctrl-T is just so handy ;)

**Comment by rct** [comment]
It looks like output doesn't occur using test mode when reading back samples.

For Linux the SIGINFO should probably need to be turned into SIGUSR1,  29 is for SIGIO.

**Comment by rct** [comment]
It would be handy if the stats output had a timestamp (to make it easier to process later).

**Comment by zuckschwerdt** [comment]
This feature is now ready. With `-M stats` the default is to report stats every 10 minutes. You will see e.g.
```
{"time": "2019-03-26 12:01:54.180993", "enabled": 97,
 "frames": {"count": 198, "fsk": 23, "events": 63},
 "stats": [
  {"device":  8, "name": "LaCrosse-TX",   "events": 198, "ok": 22, "messages": 22, "fail_other": 176},
  {"device": 19, "name": "Nexus-TH",      "events":  90, "ok":  4, "messages":  4, "fail_other": 86},
  {"device": 52, "name": "Bresser-3CH",   "events": 841, "ok": 23, "messages": 23, "abort_length": 818},
  {"device": 60, "name": "Schrader-TPMS", "events":4964, "ok":  8, "messages":  8, "fail_other": 4956},
  {"device": 88, "name": "Toyota-TPMS",   "events": 118, "ok":  6, "messages":  6, "fail_other": 112}]}
```
Together with levels reporting this really allows good insight into operations and reception.
(e.g. the Schrader line shows that the demod tried to call the decoder 4964 times with different bitbuffers -- something to look into…)

Devices need to be updated to report something other than the general "fail_other" and the format isn't final -- there could be more interesting stats to add.

Good enough for now though. I'll merge in a day or two.

**Pull request merged**
