### PR TITLE
Add support for Vauno EN8822C - working

### PR DESCRIPTION
**Pull request by loopy321**
Fixed up temperature, humidity, and checksum.  Tested and working on my system.

### CODE REVIEW

**Comment by loopy321** [comment]
Trying to add the battery bits for the device.  I have found the battery bit in two places as follows (I think byte 1, bit 1 and byte 4, bit 4):
```
Frame structure (42 bits):

    Byte:      0        1        2        3        4
    Nibble:    1   2    3   4    5   6    7   8    9   10   11
    Type:      IIIIIIII B?CCTTTT TTTTTTTT HHHHHHHF FFFBXXXX XX

- I: Random device ID
- C: Channel (1-3)
- T: Temperature (Little-endian)
- H: Humidity (Little-endian)
- F: Flags (unknown)
- B: Battery (1=low voltage ~2.5V)
- X: Checksum (6 bit nibble sum)

```
As shown in the [bitbench here](https://triq.net/bitbench#c=6d%2000%20f6%2066%200d%2000&c=9b%2001%2011%2062%2007%20c0&c=9b%2011%2011%2062%2008%2000&c=9b%2021%2011%2062%2008%2040&c=d6%2001%200b%206e%200c%20c0&c=d6%2001%200f%206c%200d%2040&c=43%2001%2011%208e%2008%2000%20%5Bhalf%20bad%20battery%202.7V%5D&c=3b%2081%2001%2076%2019%2080%20%5Bbad%20battery%202.5V%5D&c=3b%2081%2001%2078%201a%2000%20%5Bbad%20battery%202.5V%5D&c=e9%2081%201e%206c%2010%2080%20%5Bbad%20battery%202.5V%5D&c=e9%2081%2026%20a0%201c%20c0%20%5Bbad%20battery%202.5V%5D&c=e9%2091%2020%20ba%201e%2040%20%5Bbad%20battery%202.5V%5D&c=e9%2081%201e%206c%2010%2080%20%5Bbad%20battery%202.5V%5D&c=e9%2081%201d%20be%2012%2000%20%5Bbad%20battery%202.5V%5D&f=ID%3A8d%20%3Fbb%20CH%3A2h%20TEMP_C%3A12s%20HUM%3A7d%20%3Fb%20%3Fbbb%20BAT_BAD%3Ab%20CRC%3A6h%20bbbbbb&cf=ADD&cl=36&cw=4).

Any suggestions for how to properly calculate the checksum with the bad battery bit?
In bitbench, length of 36, width 4 appears to give good results (vs. prior 32/4), so I guess I need to add the next 4 bits.
Obviously the current `add_nibbles(b, 4)` does not work when `bad_bat=1`.

**Comment by zuckschwerdt** [comment]
Add a single nibble like this: `add_nibbles(b, 4) + (b[4] >> 4)`

**Comment by loopy321** [comment]
Thanks!  Fixed and working.

**Comment by gumbald** [comment]
Am I OK to close my PR, that doesn't break this one?

**Comment by zuckschwerdt** [comment]
@gumbald yes, I guess @loopy321's changes are preferred now.

**Comment by clinta** [comment]
I've been testing this for a couple of days, it seemed to work until it got cold last night, and it stopped getting updates once the temperature dropped below 0C.

The receiver that came with it continued to get updates, and the receiver is near my RTL antenna, so I don't think it's a hardware issue. And once the temp got up to 0.1C this morning, it started getting updates again.

**Comment by loopy321** [comment]
@clinta Thanks for testing!   I too see some missed readings due to a bad checksum.  Doing a sampling with `-S unknown` I see the following with correct temperatures (including negative C), but the checksum differs.  However, I also see correctly decoded readings around the same time (although much less frequent).

Upon more analysis it looks like the error is in the checksum calculation:
See [Bitbench](https://triq.net/bitbench#c=%7B42%7D%20e6%200f%2026%208c%200f%20c0%20%5Bgood%5D&c=%7B42%7D%20e6%200f%2024%208c%200f%2040%20%5Bgood%5D&c=%7B42%7D%20e6%200f%2029%208c%2000%2080%20%5Bbad%5D&c=%7B42%7D%20e6%200f%2027%208c%2000%2000%20%5Bbad%5D&c=%7B42%7D%20e6%200f%2028%208c%2000%2040%20%5Bbad%5D&f=ID%3A8d%20CH%3A4h%20TEMP_C%3A12s%20HUM%3A7d%20%3F5b%20CRC%3A6h&cf=ADD&cl=36&cw=4) corresponding to:
```
{42} e6 0f 26 8c 0f c0 [good : 11100110 00001111 00100110 10001100 00001111 11]
{42} e6 0f 24 8c 0f 40 [good : 11100110 00001111 00100100 10001100 00001111 01]
{42} e6 0f 29 8c 00 80 [bad  : 11100110 00001111 00101001 10001100 00000000 10]
{42} e6 0f 27 8c 00 00 [bad  : 11100110 00001111 00100111 10001100 00000000 00]
{42} e6 0f 28 8c 00 40 [bad  : 11100110 00001111 00101000 10001100 00000000 01]
```

```
ID:230 CH:0 TEMP_C: -218 HUM:070 ?00000 CRC:111111 = 111111 [good : 11100110 00001111 00100110 10001100 00001111 11]
ID:230 CH:0 TEMP_C: -220 HUM:070 ?00000 CRC:111101 = 111101 [good : 11100110 00001111 00100100 10001100 00001111 01]
ID:230 CH:0 TEMP_C: -215 HUM:070 ?00000 CRC:000010 = 1000010 [bad : 11100110 00001111 00101001 10001100 00000000 10]
ID:230 CH:0 TEMP_C: -217 HUM:070 ?00000 CRC:000000 = 1000000 [bad : 11100110 00001111 00100111 10001100 00000000 00]
ID:230 CH:0 TEMP_C: -216 HUM:070 ?00000 CRC:000001 = 1000001 [bad : 11100110 00001111 00101000 10001100 00000000 01]
```
 So, I added `& 0x3f` in the checksum calculation to clear the extra bit.

See [updated code](https://github.com/merbanan/rtl_433/pull/2231/commits/6e07e7606336d7d412c4048ff7ea5d44dacc9998) with the fix that is tested and working on my setup with all checksums passing now.

**Comment by clinta** [comment]
Working great now. Temperature is continuing to drop and I'm getting updates at -1.8C now.

**Comment by gumbald** [comment]
Git continues to confuse me - has this been merged into rtl433 yet?

**Comment by gumbald** [comment]
Oh, no rush - thanks for all the work you do on this!

**Comment by blezalex** [comment]
Tested on my system, works nice, thank you for a valuable contribution!

**Pull request merged**
