### PR TITLE
Changed wind_km_h to wind_avg_km_h

### PR DESCRIPTION
**Pull request by soaringswine**
Changed wind_km_h to standard wind_speed_km_h for compatibility with scripts and uniformity with other devices.

### CODE REVIEW

**Comment by zuckschwerdt** [comment]
Ok, this is only 8 days old, the breaking change won't be too hard on users.

**Comment by zuckschwerdt** [comment]
But `wind_avg_km_h` and `wind_max_km_h` are the usual keys. Please use that.

**Comment by soaringswine** [comment]
Ok, @zuckschwerdt I've updated it to "wind_avg_km_h".

**Comment by zuckschwerdt** [comment]
@mbruski heads up: the wind speed key has changed to the default one used.

**Pull request merged**
