### PR TITLE
Add flex getter, WIP

### PR DESCRIPTION
**Pull request by zuckschwerdt**
Adds a spec to extract specific bits in flex decoder. WIP, not for merge.

### CODE REVIEW

**Comment by roger-** [comment]
This looks good to me!

**Comment by zuckschwerdt** [comment]
Thanks. With upcoming support for config files the syntax will even be less arcane ;)

**Comment by roger-** [comment]
Sweet, when's the merge happening?

**Comment by zuckschwerdt** [comment]
I'm still pondering things, looking for feedback and waiting for other developers to catch up. I guess both will be merged in the next weeks. I think I'll just take the liberty of changing details later -- don't expect anything about the flex decoder to be set in stone for now ;)

**Pull request merged**
