### PR TITLE
Added decode/parsing for Oregon Scientific v2.1 and v3 sensors and rough...

### PR DESCRIPTION
**Pull request by magellannh**
Adds support for a handful of Oregon Scientific v2.1 and v3 sensors plus very rough support for the AcuRite 0896 Rain Gauge.

OS v2.1 sensors tested include: BTHR968, RGR968, THGR968, THGR268
OS v3 sensors tested: THGR810

AcuRite (Chaney) Rain Gauge: 0896  (very rough with no error checking)

### CODE REVIEW

**Comment by merbanan** [comment]
Hi, can you rebase the patch ?

**Comment by helgew** [comment]
I merged all changes from this PR at [url=https://github.com/merbanan/rtl_433/pull/74]PR74[/url], which eliminates the need to pull this one.

**Comment by merbanan** [comment]
merged

**Comment by flexd** [comment]
Hi there. I have OS THN132N, which I believe is version 2.1, that I can't seem to get working properly with rtl_433. It reads the temperature fine, but the temperature is increasing by 0.1C every read, until it hits 63C (I think it's 63C) and it resets to 0C.

Have any of you experienced that before?
Here is some sample output from when I just powered up the sensor
```
Detected OOK package
2017-09-07 20:41:18 	:	OS :	THN132N
	House Code:	 252
	Channel:	 1
	Battery:	 OK
	Celcius:	 0.00 C
	Fahrenheit:	 32.00 F
pulse_demod_manchester_zerobit(): Oregon Scientific Weather Sensor 
bitbuffer:: Number of rows: 1 
[00] {168} 55 55 55 55 99 95 a5 a6 aa 6a a5 55 aa aa aa aa aa 99 5a 99 55 
2017-09-07 20:41:18 	:	OS :	THN132N
	House Code:	 252
	Channel:	 1
	Battery:	 OK
	Celcius:	 0.00 C
	Fahrenheit:	 32.00 F
pulse_demod_manchester_zerobit(): Oregon Scientific Weather Sensor 
bitbuffer:: Number of rows: 1 
[00] {168} 55 55 55 55 99 95 a5 a6 aa 6a a5 55 aa aa aa aa aa 99 5a 99 55 
Analyzing pulses...
Total count:  190,  width: 83865		(335.5 ms)
Pulse width distribution:
 [ 0] count:  146,  width:   242 [226;250]	( 968 us)
 [ 1] count:   44,  width:   119 [110;127]	( 476 us)
Gap width distribution:
 [ 0] count:  144,  width:   245 [236;261]	( 980 us)
 [ 1] count:   44,  width:   124 [114;133]	( 496 us)
 [ 2] count:    1,  width:  2321 [2321;2321]	(9284 us)
Pulse period distribution:
 [ 0] count:  122,  width:   488 [477;506]	(1952 us)
 [ 1] count:   44,  width:   366 [357;377]	(1464 us)
 [ 2] count:   22,  width:   244 [235;254]	( 976 us)
 [ 3] count:    1,  width:  2558 [2558;2558]	(10232 us)
Level estimates [high, low]:  15945,    357
Frequency offsets [F1, F2]:   19429,      0	(+74.1 kHz, +0.0 kHz)
Guessing modulation: No clue...

Detected OOK package
2017-09-07 20:41:19 	:	OS :	THN132N
	House Code:	 252
	Channel:	 1
	Battery:	 OK
	Celcius:	 0.10 C
	Fahrenheit:	 32.18 F
pulse_demod_manchester_zerobit(): Oregon Scientific Weather Sensor 
bitbuffer:: Number of rows: 1 
[00] {168} 55 55 55 55 99 95 a5 a6 aa 6a a5 55 aa 6a aa aa aa 59 5a 65 99 
2017-09-07 20:41:19 	:	OS :	THN132N
	House Code:	 252
	Channel:	 1
	Battery:	 OK
	Celcius:	 0.10 C
	Fahrenheit:	 32.18 F
pulse_demod_manchester_zerobit(): Oregon Scientific Weather Sensor 
bitbuffer:: Number of rows: 1 
[00] {168} 55 55 55 55 99 95 a5 a6 aa 6a a5 55 aa 6a aa aa aa 59 5a 65 99 
Analyzing pulses...
Total count:  196,  width: 83861		(335.4 ms)
Pulse width distribution:
 [ 0] count:  140,  width:   241 [231;249]	( 964 us)
 [ 1] count:   56,  width:   117 [105;132]	( 468 us)
Gap width distribution:
 [ 0] count:  138,  width:   246 [238;256]	( 984 us)
 [ 1] count:   56,  width:   126 [114;138]	( 504 us)
 [ 2] count:    1,  width:  2326 [2326;2326]	(9304 us)
Pulse period distribution:
 [ 0] count:  110,  width:   487 [477;500]	(1948 us)
 [ 1] count:   56,  width:   365 [354;380]	(1460 us)
 [ 2] count:   28,  width:   246 [236;253]	( 984 us)
 [ 3] count:    1,  width:  2571 [2571;2571]	(10284 us)
Level estimates [high, low]:  15966,    396
Frequency offsets [F1, F2]:   18719,      0	(+71.4 kHz, +0.0 kHz)
Guessing modulation: No clue...

Detected OOK package
2017-09-07 20:41:20 	:	OS :	THN132N
	House Code:	 252
	Channel:	 1
	Battery:	 OK
	Celcius:	 0.20 C
	Fahrenheit:	 32.36 F
pulse_demod_manchester_zerobit(): Oregon Scientific Weather Sensor 
bitbuffer:: Number of rows: 1 
[00] {168} 55 55 55 55 99 95 a5 a6 aa 6a a5 55 aa 9a aa aa aa a5 5a a6 66 
2017-09-07 20:41:20 	:	OS :	THN132N
	House Code:	 252
	Channel:	 1
	Battery:	 OK
	Celcius:	 0.20 C
	Fahrenheit:	 32.36 F
pulse_demod_manchester_zerobit(): Oregon Scientific Weather Sensor 
bitbuffer:: Number of rows: 1 
[00] {168} 55 55 55 55 99 95 a5 a6 aa 6a a5 55 aa 9a aa aa aa a5 5a a6 66 
Analyzing pulses...
Total count:  194,  width: 83980		(335.9 ms)
Pulse width distribution:
 [ 0] count:  142,  width:   241 [227;249]	( 964 us)
 [ 1] count:   52,  width:   117 [109;127]	( 468 us)
Gap width distribution:
 [ 0] count:  142,  width:   246 [239;257]	( 984 us)
 [ 1] count:   50,  width:   126 [114;137]	( 504 us)
 [ 2] count:    1,  width:  2197 [2197;2197]	(8788 us)
Pulse period distribution:
 [ 0] count:  116,  width:   488 [476;501]	(1952 us)
 [ 1] count:   52,  width:   365 [355;377]	(1460 us)
 [ 2] count:   24,  width:   246 [236;256]	( 984 us)
 [ 3] count:    1,  width:  2315 [2315;2315]	(9260 us)
Level estimates [high, low]:  15921,    398
Frequency offsets [F1, F2]:   18651,      0	(+71.2 kHz, +0.0 kHz)
Guessing modulation: No clue...

Detected OOK package
2017-09-07 20:41:21 	:	OS :	THN132N
	House Code:	 252
	Channel:	 1
	Battery:	 OK
	Celcius:	 0.30 C
	Fahrenheit:	 32.54 F
pulse_demod_manchester_zerobit(): Oregon Scientific Weather Sensor 
bitbuffer:: Number of rows: 1 
[00] {168} 55 55 55 55 99 95 a5 a6 aa 6a a5 55 aa 5a aa aa aa 65 5a 5a aa 
2017-09-07 20:41:21 	:	OS :	THN132N
	House Code:	 252
	Channel:	 1
	Battery:	 OK
	Celcius:	 0.30 C
	Fahrenheit:	 32.54 F
pulse_demod_manchester_zerobit(): Oregon Scientific Weather Sensor 
bitbuffer:: Number of rows: 1 
[00] {168} 55 55 55 55 99 95 a5 a6 aa 6a a5 55 aa 5a aa aa aa 65 5a 5a aa 
Analyzing pulses...
Total count:  192,  width: 83989		(336.0 ms)
Pulse width distribution:
 [ 0] count:  144,  width:   242 [230;250]	( 968 us)
 [ 1] count:   48,  width:   118 [106;128]	( 472 us)
Gap width distribution:
 [ 0] count:  144,  width:   245 [238;256]	( 980 us)
 [ 1] count:   46,  width:   125 [112;137]	( 500 us)
 [ 2] count:    1,  width:  2202 [2202;2202]	(8808 us)
Pulse period distribution:
 [ 0] count:  120,  width:   488 [477;500]	(1952 us)
 [ 1] count:   48,  width:   365 [353;382]	(1460 us)
 [ 2] count:   22,  width:   245 [236;255]	( 980 us)
 [ 3] count:    1,  width:  2325 [2325;2325]	(9300 us)
Level estimates [high, low]:  15964,    436
Frequency offsets [F1, F2]:   19204,      0	(+73.3 kHz, +0.0 kHz)
Guessing modulation: No clue...

Detected OOK package
2017-09-07 20:41:22 	:	OS :	THN132N
	House Code:	 252
	Channel:	 1
	Battery:	 OK
	Celcius:	 0.40 C
	Fahrenheit:	 32.72 F
pulse_demod_manchester_zerobit(): Oregon Scientific Weather Sensor 
bitbuffer:: Number of rows: 1 
[00] {168} 55 55 55 55 99 95 a5 a6 aa 6a a5 55 aa a6 aa aa aa 95 5a 6a 99 
2017-09-07 20:41:22 	:	OS :	THN132N
	House Code:	 252
	Channel:	 1
	Battery:	 OK
	Celcius:	 0.40 C
	Fahrenheit:	 32.72 F
pulse_demod_manchester_zerobit(): Oregon Scientific Weather Sensor 
bitbuffer:: Number of rows: 1 
[00] {168} 55 55 55 55 99 95 a5 a6 aa 6a a5 55 aa a6 aa aa aa 95 5a 6a 99 
Analyzing pulses...
Total count:  192,  width: 83865		(335.5 ms)
Pulse width distribution:
 [ 0] count:  144,  width:   241 [229;250]	( 964 us)
 [ 1] count:   48,  width:   117 [105;129]	( 468 us)
Gap width distribution:
 [ 0] count:  142,  width:   246 [238;259]	( 984 us)
 [ 1] count:   48,  width:   126 [113;137]	( 504 us)
 [ 2] count:    1,  width:  2317 [2317;2317]	(9268 us)
Pulse period distribution:
 [ 0] count:  118,  width:   488 [474;504]	(1952 us)
 [ 1] count:   48,  width:   365 [352;383]	(1460 us)
 [ 2] count:   24,  width:   245 [227;254]	( 980 us)
 [ 3] count:    1,  width:  2557 [2557;2557]	(10228 us)
Level estimates [high, low]:  16009,    408
Frequency offsets [F1, F2]:   19163,      0	(+73.1 kHz, +0.0 kHz)
Guessing modulation: No clue...

Detected OOK package
2017-09-07 20:41:23 	:	OS :	THN132N
	House Code:	 252
	Channel:	 1
	Battery:	 OK
	Celcius:	 0.50 C
	Fahrenheit:	 32.90 F
pulse_demod_manchester_zerobit(): Oregon Scientific Weather Sensor 
bitbuffer:: Number of rows: 1 
[00] {168} 55 55 55 55 99 95 a5 a6 aa 6a a5 55 aa 66 aa aa aa 55 5a 96 55 
2017-09-07 20:41:23 	:	OS :	THN132N
	House Code:	 252
	Channel:	 1
	Battery:	 OK
	Celcius:	 0.50 C
	Fahrenheit:	 32.90 F
pulse_demod_manchester_zerobit(): Oregon Scientific Weather Sensor 
bitbuffer:: Number of rows: 1 
[00] {168} 55 55 55 55 99 95 a5 a6 aa 6a a5 55 aa 66 aa aa aa 55 5a 96 55 
Analyzing pulses...
Total count:  192,  width: 83862		(335.4 ms)
Pulse width distribution:
 [ 0] count:  144,  width:   242 [229;250]	( 968 us)
 [ 1] count:   48,  width:   117 [106;132]	( 468 us)
Gap width distribution:
 [ 0] count:  142,  width:   245 [237;258]	( 980 us)
 [ 1] count:   48,  width:   126 [112;138]	( 504 us)
 [ 2] count:    1,  width:  2328 [2328;2328]	(9312 us)
Pulse period distribution:
 [ 0] count:  118,  width:   487 [478;503]	(1948 us)
 [ 1] count:   48,  width:   366 [352;382]	(1464 us)
 [ 2] count:   24,  width:   246 [237;254]	( 984 us)
 [ 3] count:    1,  width:  2575 [2575;2575]	(10300 us)
Level estimates [high, low]:  15989,    363
Frequency offsets [F1, F2]:   19416,      0	(+74.1 kHz, +0.0 kHz)
Guessing modulation: No clue...

Detected OOK package
2017-09-07 20:41:24 	:	OS :	THN132N
	House Code:	 252
	Channel:	 1
	Battery:	 OK
	Celcius:	 0.60 C
	Fahrenheit:	 33.08 F
pulse_demod_manchester_zerobit(): Oregon Scientific Weather Sensor 
bitbuffer:: Number of rows: 1 
[00] {168} 55 55 55 55 99 95 a5 a6 aa 6a a5 55 aa 96 aa aa aa aa a6 55 aa 
2017-09-07 20:41:24 	:	OS :	THN132N
	House Code:	 252
	Channel:	 1
	Battery:	 OK
	Celcius:	 0.60 C
	Fahrenheit:	 33.08 F
pulse_demod_manchester_zerobit(): Oregon Scientific Weather Sensor 
bitbuffer:: Number of rows: 1 
[00] {168} 55 55 55 55 99 95 a5 a6 aa 6a a5 55 aa 96 aa aa aa aa a6 55 aa 
Analyzing pulses...
Total count:  190,  width: 83989		(336.0 ms)
Pulse width distribution:
 [ 0] count:  146,  width:   242 [230;250]	( 968 us)
 [ 1] count:   44,  width:   118 [109;130]	( 472 us)
Gap width distribution:
 [ 0] count:  146,  width:   246 [237;260]	( 984 us)
 [ 1] count:   42,  width:   126 [114;135]	( 504 us)
 [ 2] count:    1,  width:  2201 [2201;2201]	(8804 us)
Pulse period distribution:
 [ 0] count:  124,  width:   487 [476;502]	(1948 us)
 [ 1] count:   44,  width:   365 [355;378]	(1460 us)
 [ 2] count:   20,  width:   246 [239;253]	( 984 us)
 [ 3] count:    1,  width:  2326 [2326;2326]	(9304 us)
Level estimates [high, low]:  15973,    408
Frequency offsets [F1, F2]:   19256,      0	(+73.5 kHz, +0.0 kHz)
Guessing modulation: No clue...

Detected OOK package
2017-09-07 20:41:25 	:	OS :	THN132N
	House Code:	 252
	Channel:	 1
	Battery:	 OK
	Celcius:	 0.70 C
	Fahrenheit:	 33.26 F
pulse_demod_manchester_zerobit(): Oregon Scientific Weather Sensor 
bitbuffer:: Number of rows: 1 
[00] {168} 55 55 55 55 99 95 a5 a6 aa 6a a5 55 aa 56 aa aa aa 6a a6 a9 66 
2017-09-07 20:41:25 	:	OS :	THN132N
	House Code:	 252
	Channel:	 1
	Battery:	 OK
	Celcius:	 0.70 C
	Fahrenheit:	 33.26 F
pulse_demod_manchester_zerobit(): Oregon Scientific Weather Sensor 
bitbuffer:: Number of rows: 1 
[00] {168} 55 55 55 55 99 95 a5 a6 aa 6a a5 55 aa 56 aa aa aa 6a a6 a9 66 
Analyzing pulses...
Total count:  194,  width: 83990		(336.0 ms)
Pulse width distribution:
 [ 0] count:  142,  width:   242 [228;250]	( 968 us)
 [ 1] count:   52,  width:   118 [109;128]	( 472 us)
Gap width distribution:
 [ 0] count:  142,  width:   246 [237;259]	( 984 us)
 [ 1] count:   50,  width:   125 [113;134]	( 500 us)
 [ 2] count:    1,  width:  2196 [2196;2196]	(8784 us)
Pulse period distribution:
 [ 0] count:  116,  width:   488 [479;504]	(1952 us)
 [ 1] count:   52,  width:   365 [354;377]	(1460 us)
 [ 2] count:   24,  width:   245 [234;254]	( 980 us)
 [ 3] count:    1,  width:  2318 [2318;2318]	(9272 us)
Level estimates [high, low]:  15953,    395
Frequency offsets [F1, F2]:   18594,      0	(+70.9 kHz, +0.0 kHz)
Guessing modulation: No clue...

Detected OOK package
2017-09-07 20:41:26 	:	OS :	THN132N
	House Code:	 252
	Channel:	 1
	Battery:	 OK
	Celcius:	 0.80 C
	Fahrenheit:	 33.44 F
pulse_demod_manchester_zerobit(): Oregon Scientific Weather Sensor 
bitbuffer:: Number of rows: 1 
[00] {168} 55 55 55 55 99 95 a5 a6 aa 6a a5 55 aa a9 aa aa aa 9a a6 a5 a6 
2017-09-07 20:41:26 	:	OS :	THN132N
	House Code:	 252
	Channel:	 1
	Battery:	 OK
	Celcius:	 0.80 C
	Fahrenheit:	 33.44 F
pulse_demod_manchester_zerobit(): Oregon Scientific Weather Sensor 
bitbuffer:: Number of rows: 1 
[00] {168} 55 55 55 55 99 95 a5 a6 aa 6a a5 55 aa a9 aa aa aa 9a a6 a5 a6 
Analyzing pulses...
Total count:  194,  width: 83989		(336.0 ms)
Pulse width distribution:
 [ 0] count:  142,  width:   241 [226;250]	( 964 us)
 [ 1] count:   52,  width:   117 [106;129]	( 468 us)
Gap width distribution:
 [ 0] count:  142,  width:   246 [238;257]	( 984 us)
 [ 1] count:   50,  width:   126 [113;138]	( 504 us)
 [ 2] count:    1,  width:  2202 [2202;2202]	(8808 us)
Pulse period distribution:
 [ 0] count:  116,  width:   488 [479;498]	(1952 us)
 [ 1] count:   52,  width:   365 [354;382]	(1460 us)
 [ 2] count:   24,  width:   245 [232;259]	( 980 us)
 [ 3] count:    1,  width:  2327 [2327;2327]	(9308 us)
Level estimates [high, low]:  15918,    448
Frequency offsets [F1, F2]:   18623,      0	(+71.0 kHz, +0.0 kHz)
Guessing modulation: No clue...
```

**Pull request closed without merging**
