### PR TITLE
Add Auriol-HG02832 support

### PR DESCRIPTION
**Pull request by zuckschwerdt**
S.a. #1161

### CODE REVIEW

**Comment by zuckschwerdt** [comment]
@OverSave please test if this works.

**Comment by merbanan** [comment]
No need to hold this up. Commit at will.

**Comment by OverSave** [comment]
looks like if everything works, thanks good and fast work

**Comment by OverSave** [comment]
have now found a small bug, sometimes the temperature 00001 is displayed too much. Example 16.700001

**Comment by zuckschwerdt** [comment]
That's just how a float works. But KV and CSV should only output a single decimal, JSON three decimals. Where do you see 6 decimals?

**Comment by zuckschwerdt** [comment]
The one place I didn't check. Good catch, fixed with c124af4 now.

**Comment by OverSave** [comment]
alright thanks

**Pull request merged**
