### PR TITLE
Add support for CED7000 timer

### PR DESCRIPTION
**Pull request by ppapadeas**
Test data in https://github.com/merbanan/rtl_433_tests/pull/441/files

Signed-off-by: Papadeas Pierros <pierros@papadeas.gr>

### CODE REVIEW

**Comment by zuckschwerdt** [comment]
Looks good, notes:
- you should loop all rows and find a / the long one, not hardcode `1`
- you should search the sync word, not assume it's at a fixed pos
- use one of `reverse8(), reflect_bytes(), reflect4(), reflect_nibbles()`
- you need to extract values as numbers not strings

E.g.
```
    uint8_t const sync_pattern[3] = {0xaa, 0x4d, 0x5e};

    // Find row
    int row = bitbuffer_find_repeated_row(bitbuffer, 1, 6*16+3*8);
    if (row < 0)
        return DECODE_ABORT_EARLY;

    // search for 24 bit sync pattern
    bitpos = bitbuffer_search(bitbuffer, row, bitpos, sync_pattern, 24) + 24;

    if ((bitpos >= bitbuffer->bits_per_row[row])
        return DECODE_ABORT_EARLY;

    bitbuffer_invert(bitbuffer);

    // Check and decode the Manchester bits
    ret = bitbuffer_manchester_decode(bitbuffer, row, bitpos, &decoded, NUM_BITS_DATA);

    ....

    int rfid = (b[1] & 0xF) * 1000 + (b[1] >> 4) * 100 + (b[0] & 0xF) * 10 + (b[0] >> 4);
```

**Comment by ppapadeas** [comment]
Thanks for the review @zuckschwerdt ! Should I amend the commit or push another one on top, based on your suggestions?

**Comment by zuckschwerdt** [comment]
As you like, adding commits is likely easier. We always squash on merge anyway.

**Comment by ppapadeas** [comment]
@zuckschwerdt Amended following your 4 comments. Thanks for the pointers!

**Comment by ppapadeas** [comment]
@zuckschwerdt let me know when adding this is next-in-line so I can rebase properly (to make your life easier ;) )

**Comment by zuckschwerdt** [comment]
Rebase and correct the two line with sticky braces (`if …){`).
Good for merge then.

**Comment by ppapadeas** [comment]
@zuckschwerdt done and done!

**Comment by zuckschwerdt** [comment]
Perfect, thanks!
I just noticed: "rfid" is that an ID? It should be named just "id" then. All decoders have "model", "id", …

**Comment by ppapadeas** [comment]
> "rfid" is that an ID?

Not really. It is a user-set parameter from the device menu to be able to "sync" the device with accessories and use multiple ones on the field.

**Comment by zuckschwerdt** [comment]
Ok, so more like a "channel" settings on temperature sensors.
It would be nice if this was a random number by default, but I guess it's simply "0000"?

We really always want an "id" key to be present, this is the best we get. I kind of answers the "which (local) device is this" question. Can you document that RFID is used as ID and change the key then?

**Comment by ppapadeas** [comment]
@zuckschwerdt gotcha. I changed it to ID now. Thanks!

**Pull request merged**
