### PR TITLE
Update tpms_nissan.c

### PR DESCRIPTION
**Pull request by CppBaddy**
Fixed reported pressure_psi value.

### CODE REVIEW

**Comment by zuckschwerdt** [comment]
Thanks!
The inversion of the documented `(PSI+THREE)*FOUR` would be `float pressure_psi = (float)pressure_raw / 4.0f - 3.0f;`, won't it?

**Comment by CppBaddy** [comment]
I found by accident that the pressure value tracks my tire gauge better. Original formula gives much lower values. To verify, I am going to capture some data from my winter wheels tonight.

**Comment by zuckschwerdt** [comment]
The decoder was merged from #2536 but I messed up the pressure by applying the factor twice.

I think only that error should be corrected. The difference in measurement you see is more likely due to operating temperature?

**Comment by CppBaddy** [comment]
Ok, this makes sense, I'll make changes then.

**Comment by zuckschwerdt** [comment]
Thanks! Sorry to be picky, could you use `4.0f` to be consistent with other float literals?

**Comment by CppBaddy** [comment]
No worries, fixed.
Cheers!

**Pull request merged**
