### PR TITLE
get sample rate from filename

### PR DESCRIPTION
**Pull request by evilpete**
added shell operators to get sample rate from filename

### CODE REVIEW

**Comment by Mindavi** [comment]
Does this work for filenames not containing sample rate as well? I might imagine people changing filenames before uploading etc., so it should handle that case.

**Comment by merbanan** [comment]
Well as long as you still can override the sample rate it doesn't matter IMO. It is a tool more targeted for developers.

**Comment by zuckschwerdt** [comment]
I have some experimental code to create the Pulseview format directly in rtl_433. We'd have more control over all the options (sample rate, frequency, …) then.
The interesting bit is to call the zip util, I'd rather not include a lib for that.
I see if I can finish that code soon.

**Comment by zuckschwerdt** [comment]
I think enhancing the script will make it to fragile in the end. We should move away from a shell script, there is some prototype code in #1297

**Pull request closed without merging**
