### PR TITLE
kerui: cleanup

### PR DESCRIPTION
**Pull request by roger-**
A few minor changes:

* rename to Kerui PIR / Contact Sensor
* cleanup state names (e.g. PIR -> motion)
* move state to separate field to make easier to parse

### CODE REVIEW

**Comment by zuckschwerdt** [comment]
A needed clean-up, thanks. All those changes are breaking the current output though. I don't know if people rely on the current names and format?
Let this sit for two weeks and see if anyone complains ;)

**Comment by roger-** [comment]
No complaints yet!

**Comment by zuckschwerdt** [comment]
But let's change the "model" string to the shorter, agreed format of two words while we are at it. "Kerui Security" sounds good.

**Comment by roger-** [comment]
Sure -- done!

**Comment by zuckschwerdt** [comment]
Sorry, only the model. The protocol name can be descriptive, like you had.

**Comment by roger-** [comment]
Got it, reverted part of the edit.

**Comment by zuckschwerdt** [comment]
Thanks. Reasoning (if someone stumbles apon this later):
- r_device.name is a descriptive string for the help texts
- data.model is a concise key for the consumers (which might use it as machine-readable key/tag)

**Pull request merged**
