### PR TITLE
Enhance Honeywell for 2Gig, RE208

### PR DESCRIPTION
**Pull request by zuckschwerdt**
s.a. #746

### CODE REVIEW

**Comment by zuckschwerdt** [comment]
there are regressions. don't merge for now.

**Comment by mazubieta** [comment]
So I'm testing this out.  I noticed that the `state` value does not change when I open/close a contact.  Am I misinterpreting what that state value should be?

### RE-208 Sensor 1 -- open then close
```
{"time" : "2018-06-09 19:37:03", "model" : "Honeywell Door/Window Sensor", "id" : 183889, "channel" : 8, "event" : 32, "state" : "closed", "heartbeat" : "no"}
{"time" : "2018-06-09 19:37:06", "model" : "Honeywell Door/Window Sensor", "id" : 183889, "channel" : 8, "event" : 0, "state" : "closed", "heartbeat" : "no"}
```
### RE-208 Sensor 2 -- open then close
```
{"time" : "2018-06-09 19:41:32", "model" : "Honeywell Door/Window Sensor", "id" : 183890, "channel" : 8, "event" : 32, "state" : "closed", "heartbeat" : "no"}
{"time" : "2018-06-09 19:41:37", "model" : "Honeywell Door/Window Sensor", "id" : 183890, "channel" : 8, "event" : 0, "state" : "closed", "heartbeat" : "no"}
```

### RE-208 -- tamper open then close
```
{"time" : "2018-06-09 19:48:48", "model" : "Honeywell Door/Window Sensor", "id" : 183888, "channel" : 8, "event" : 72, "state" : "closed", "heartbeat" : "no"}
{"time" : "2018-06-09 19:48:50", "model" : "Honeywell Door/Window Sensor", "id" : 183888, "channel" : 8, "event" : 8, "state" : "closed", "heartbeat" : "no"}
```
The same thing also happens for the 2gig sensors:

### 2gig sensor 1 -- open then close
```
{"time" : "2018-06-09 19:42:26", "model" : "Honeywell Door/Window Sensor", "id" : 912535, "channel" : 10, "event" : 160, "state" : "open", "heartbeat" : "no"}
{"time" : "2018-06-09 19:42:27", "model" : "Honeywell Door/Window Sensor", "id" : 912535, "channel" : 10, "event" : 128, "state" : "open", "heartbeat" : "no"}
```
### 2gig sensor 2 -- open then close
```
{"time" : "2018-06-09 19:43:58", "model" : "Honeywell Door/Window Sensor", "id" : 73942, "channel" : 10, "event" : 160, "state" : "open", "heartbeat" : "no"}
{"time" : "2018-06-09 19:44:03", "model" : "Honeywell Door/Window Sensor", "id" : 73942, "channel" : 10, "event" : 128, "state" : "open", "heartbeat" : "no"}
```
### 2gig sensor 1 -- tamper open then close
```
{"time" : "2018-06-09 19:45:50", "model" : "Honeywell Door/Window Sensor", "id" : 912535, "channel" : 10, "event" : 224, "state" : "open", "heartbeat" : "no"}
{"time" : "2018-06-09 19:46:06", "model" : "Honeywell Door/Window Sensor", "id" : 912535, "channel" : 10, "event" : 160, "state" : "open", "heartbeat" : "no"}
```

I did see a bunch of heartbeats ...

```
{"time" : "2018-06-09 19:16:09", "model" : "Honeywell Door/Window Sensor", "id" : 196428, "channel" : 10, "event" : 132, "state" : "open", "heartbeat" : "yes"}
{"time" : "2018-06-09 19:17:21", "model" : "Honeywell Door/Window Sensor", "id" : 671477, "channel" : 10, "event" : 164, "state" : "open", "heartbeat" : "yes"}
{"time" : "2018-06-09 19:21:15", "model" : "Honeywell Door/Window Sensor", "id" : 120340, "channel" : 10, "event" : 132, "state" : "open", "heartbeat" : "yes"}
{"time" : "2018-06-09 19:28:36", "model" : "Honeywell Door/Window Sensor", "id" : 138953, "channel" : 10, "event" : 132, "state" : "open", "heartbeat" : "yes"}
{"time" : "2018-06-09 19:28:56", "model" : "Honeywell Door/Window Sensor", "id" : 74925, "channel" : 10, "event" : 132, "state" : "open", "heartbeat" : "yes"}
```

**Comment by zuckschwerdt** [comment]
`state` and `heartbeat` are decoded for Honeywell devices. You'd need to find out what the bits in `event` mean for your 2Gig.

**Comment by mazubieta** [comment]
Is this what we need? https://github.com/fusterjj/HoneywellSecurityMQTT/blob/master/src/digitalDecoder.cpp#L78-L123

**Comment by zuckschwerdt** [comment]
I have added those bits. The alarm field is three bits however and the meaning isn't clear. I guess it's different loops. The event bits seem to be `AATABHUU` for Alarm, Tamper, Battery-low, Heartbeat, Unknown. Maybe we need to report each of the 3 alarm bits or a summary ( >0). Perhaps you can figure out what works best across all device types.

**Comment by dainman** [comment]
Hi... I was having similar issues with 2GIG device and found this PR.   After I pulled your updates I can now decode the 2GIG door sensors.  What do think is that the state and alarm bits are backwards

This is what I have currently have in place
    // decoded event bits: AATABHUU
    state = (event & 0xb0) >> 4;
    alarm = (event & 0x80) >> 7;

This seems to show open and close state correctly.  Any chance that we could get this PR merge with corrections?

**Comment by zuckschwerdt** [comment]
Thanks! All that is missing for merge is a good description of the event bits. Can you describe in more detail what you see on the individual bits?
I've rebased this PR to current master, you need to reset or remove the branch then pull.

**Comment by dainman** [comment]
To be honest all this is new to me so I not really sure how to see the individual bits on the event.  I am testing with two different sensors a Honeywell 5818MNL and a Versa-2GIG (basically a Honeywell 5800MINI clone).

From what I am seeing in the JSON output

Both devices show the correct Open/Closed state
Both device send a heartbeat message
don't have a low battery but assume that will be correct
5818MNL sends an int of 1 on open for Alarm and 0 for closed
Versa-2GIG is always 0 for Alarm
Versa-2GIG has tamper which is sends 0 when case is closed and 1 when it is open


Let me know what other testing I can try and I am happy to help

**Comment by zuckschwerdt** [comment]
If you just list the event field (8 bit hex, i.e. two characters) with the actual action we can figure out if the AATABHUU assumption fits and what the three Alarm bits and maybe the two Unknown bits are :)

**Comment by zuckschwerdt** [comment]
If you want to "see" the bits [use BitBench](http://triq.net/bitbench?c=12&c=34&c=56&f=b) and just write event codes, one per line (12, 34, 56 in that example).

**Comment by dainman** [comment]
Versa-2GIG (5800MINI Clone)
0 = Closed, No Tamper
4 = Heartbeat, Closed,  No Tamper
32 = Open, No Tamper
36 = Heartbeat, Open, No Tamper
64 = Closed, Tamper
68 = Heartbeat, Closed, Tamper
96 = Opened, Tamper
100 = Heartbeat, Opened, Tamper



5818MNL
0 = Closed
4 = Heartbeat, Closed
128 = Open
132 = Heartbeat, Open

**Comment by zuckschwerdt** [comment]
Yes, converted to hex [BitBench can show it](http://triq.net/bitbench?c=%5BVersa-2GIG%20(5800MINI%20Clone)%5D&c=%5B0%5D%200x00%20%5BClosed%2C%20No%20Tamper%5D&c=%5B4%5D%200x04%20%5BHeartbeat%2C%20Closed%2C%20No%20Tamper%5D&c=%5B32%5D%200x20%20%5BOpen%2C%20No%20Tamper%5D&c=%5B36%5D%200x24%20%5BHeartbeat%2C%20Open%2C%20No%20Tamper%5D&c=%5B64%5D%200x40%20%5BClosed%2C%20Tamper%5D&c=%5B68%5D%200x44%20%5BHeartbeat%2C%20Closed%2C%20Tamper%5D&c=%5B96%5D%200x60%20%5BOpened%2C%20Tamper%5D&c=%5B100%5D%200x64%20%5BHeartbeat%2C%20Opened%2C%20Tamper%5D&c=%5B5818MNL%5D&c=%5B0%5D%200x00%20%5BClosed%5D&c=%5B4%5D%200x04%20%5BHeartbeat%2C%20Closed%5D&c=%5B128%5D%200x80%20%5BOpen%5D&c=%5B132%5D%200x84%20%5BHeartbeat%2C%20Open%5D&f=Ab%20Ab%20Tb%20Ab%20Bb%20Hb%20Ub%20Ub).
So Heartbeat is where we expect it, Versa-2GIG shows Open as Tamper and Tamper as middle Alarm bit. 5818MNL shows open as first Alarm bit.
It's more like STA0BHUU (State, Temper, Alarm, …) here. How does the term Open apply to both devices, i.e. what kind of event do they sense. Should an Open be called Alarm?

**Comment by dainman** [comment]
as far as what it should be called I think that since it is a door sensor the Open/Closed is good.  If I modify the honeywell.c as below both sensors work to should the correct status, heartbeat, tamper (the one that has tamper)

    state = (event & 0xb0) >> 4;
    alarm = (event & 0x80) >> 7;
    tamper = (event & 0x40) >> 6;
    battery_low = (event & 0x08) >> 3;
    heartbeat = (event & 0x04) >> 2;


this is from -a
Honeywell 5818MNL
open = [00] {52} 00 02 4a 41 80 92 10
closed = [00] {52} 00 02 4a 41 00 89 10

Versa
closed, no tamper = [00] {51} 00 03 a4 30 01 8a 00
closed, tamper = [00] {50} 00 03 a4 30 80 b2 00
open, no tamper = [00] {51} 00 03 a4 30 40 89 00
open, tamper = [00] {49} 00 03 a4 30 83 a8 00


Unfortunately, I think that I am outside my skillset on this but I am happy to continue testing if needed but might need additional more instructions.  

Thanks for your help!

**Comment by merbanan** [comment]
What is the status on this?

**Comment by zuckschwerdt** [comment]
There is a conflict in the meaning of the state bits. I can't puzzle that together. Otherwise I could merge with broken state for these two devices.

**Pull request merged**
