### PR TITLE
Add documentation for influxdb sink

### PR DESCRIPTION
**Pull request by azrdev**
both variants, MQTT consumer plugin, and rtl433json_to_influx.py

### CODE REVIEW

**Comment by zuckschwerdt** [comment]
Thanks. Take a look at our [examples](https://github.com/merbanan/rtl_433/tree/master/examples). You really shouldn't use a log file to communicate. UDP with the syslog protocol will tolerate faults better. Also please try `-M newmodel`, the old keys are a mess -- you probably noticed ;)

**Comment by azrdev** [comment]
@zuckschwerdt look at the time stamps, I built this script quite a while ago, still works though.

and it's not using a file but a named pipe :)

**Comment by zuckschwerdt** [comment]
Thanks, I'll update the docs soon. We also now have a very minimal [example script](https://github.com/merbanan/rtl_433/blob/master/examples/rtl_433_influxdb_relay.py).

**Comment by zuckschwerdt** [comment]
We now have native InfluxDB support with #1192. Documentation will soon be updated to show all possibilities to interface.

**Comment by zuckschwerdt** [comment]
Documentation on some options for InfluxDB went in with dac4e63.

**Pull request closed without merging**
