### PR TITLE
Add the ability to execute a program for each decoded message

### PR DESCRIPTION
**Pull request by aabaker**
It is helpful for my use case to be able to execute a program every time a valid message is received, passing it as parameters the values in the message. The program can, for example, add the values received to a database.

This code implements this feature for Posix hosts, I don't have a Dev/test environment to attempt a WIN32 version.

### CODE REVIEW

**Comment by merbanan** [comment]
Can you show how a command line would look and the output of that ?

**Comment by aabaker** [comment]
If I launch rtl_433 with
rtl_433 -q -e echo
then when I get a message it will execute, for example
echo --time "2016-05-23 23:51:06" --model "Weather Sensor THGR122N" --id 81 --channel 1 --battery OK --temperature_C "11.70 C" --humidity "68 %"
I've included the quotes as if this was a command typed at the shell, those values get passed as a single argument with the quotes removed just as a quoted argument does from the shell

Of course running echo isn't very useful, the script I actually call is

#!/usr/bin/env python

import argparse
import sys
import rrdtool

parser = argparse.ArgumentParser(description='Add values to rrdtool databases')
parser.add_argument('--time')
parser.add_argument('--model' )
parser.add_argument('--id', required=True )
parser.add_argument('--channel', required=True )
parser.add_argument('--battery' )
parser.add_argument('--temperature_C' )
parser.add_argument('--humidity' )

args=parser.parse_args()

if (args.id == '230'):
  rrdtool.update('temp2.rrd', 'N:'+args.temperature_C.split()[0])
elif (args.id == '81'):
  rrdtool.update('temp1.rrd', 'N:'+args.temperature_C.split()[0])
  rrdtool.update('humidity.rrd', 'N:'+args.humidity.split()[0])

**Comment by panarom** [comment]
@aabaker one other possibility to consider, because it may be cleaner: use the JSON output format to standard out, then pipe to your program, which will parse the JSON on standard in
(One of the flaws with this suggestion, though, is that JSON output isn't available for every device).

**Comment by merbanan** [comment]
@aabaker I have to go with @panarom on this, use a pipe and parse the json.

**Comment by rct** [comment]
@aabaker once you are already (Python, Perl, whatever) it's pretty much straightforward to read from stdin (unbuffered / linebuffered) and do what ever you want with the data.

Currently I'm updating about a dozen RRDtool archives from a bunch of different sensors and creating daily log files that can be replayed if necessary.  I'm using Perl since I started before the JSON stuff and the regular expression bits were easier for me (old habits).   

If I rewrite in Python, I'll post it.  

There should probably be a "contrib" section of this repo for consumer scripts and stuff (or at least a markdown doc with a link to other repos.)

**Comment by aabaker** [comment]
Once I looked at the JSON output and discovered 

- it is being output as one record per line so there is no need to try to find record boundaries and
- there is an fflush() after each record is output so using pipes won't cause buffering issues

decoding it in python is trivial

``` python
#!/usr/bin/env python
import json
import sys
import rrdtool

while(True):
  line=sys.stdin.readline()
  data=json.loads(line)
  if data['id'] == 81:
    rrdtool.update('temp1.rrd', 'N:'+str(data['temperature_C']))
    rrdtool.update('humidity.rrd', 'N:'+str(data['humidity']))
  elif data['id'] == 230:
    rrdtool.update('temp2.rrd', 'N:'+str(data['temperature_C']))
```

**Pull request closed without merging**
