### PR TITLE
Add ST389 temperature sensor for ORIA WA50 Wireless Digital Freezer Thermometer

### PR DESCRIPTION
**Pull request by jpmv27**
As discussed in #2935

Let me know what you think

### CODE REVIEW

**Comment by zuckschwerdt** [comment]
Thanks! Please make only the humidity conditional. Other data might be unused but is still contained in the transmission.
Also "model" is only a kind of tag for the protocol/decoder and not a description, we should keep a single name for the protocol. (It's already messy as there are 3 nearly identical decoders for this protocol type).

**Comment by jpmv27** [comment]
Removed the extraneous changes. I'll keep those for myself only.

**Comment by zuckschwerdt** [comment]
Thanks, looks good. The addition of `, ORIA WA50 ST389 temperature sensor` also needs to be at the end of the decoder in the `.name` line. Compile and run `./maintainer_update.py` to get those updates into other files.

**Comment by jpmv27** [comment]
I ran maintainer_update.py, but it generated changes unrelated to mine, such as
```
diff --git a/conf/rtl_433.example.conf b/conf/rtl_433.example.conf
index 1e6c1b12..52c29ba0 100644
--- a/conf/rtl_433.example.conf
+++ b/conf/rtl_433.example.conf
@@ -478,11 +478,12 @@ convert si
   protocol 249 # Bresser lightning
   protocol 250 # Schou 72543 Day Rain Gauge, Motonet MTX Rain, MarQuant Rain Gauge, TFA Dostmann 30.3252.01/47.3006.01 Rain Gauge and Thermometer, ADE WS1907
   protocol 251 # Fine Offset / Ecowitt WH55 water leak sensor
-  protocol 252 # BMW Gen5 TPMS, multi-brand HUF, Continental, Schrader/Sensata
+  protocol 252 # BMW Gen4-Gen5 TPMS and Audi TPMS Pressure Alert, multi-brand HUF/Beru, Continental, Schrader/Sensata, Audi
   protocol 253 # Watts WFHT-RF Thermostat
   protocol 254 # Thermor DG950 weather station
   protocol 255 # Mueller Hot Rod water meter
   protocol 256 # ThermoPro TP28b Super Long Range Wireless Meat Thermometer for Smoker BBQ Grill
+  protocol 257 # BMW Gen3 TPMS
```
and
```
diff --git a/man/man1/rtl_433.1 b/man/man1/rtl_433.1
index 2636143a..ddf53eae 100644
--- a/man/man1/rtl_433.1
+++ b/man/man1/rtl_433.1
@@ -168,7 +168,7 @@ RTL\-SDR device driver is available.
 To set gain for RTL\-SDR use \-g <gain> to set an overall gain in dB.
 .RE
 .RS
-SoapySDR device driver is available.
+SoapySDR device driver is not available.
```
so I'm concerned about committing that

**Comment by zuckschwerdt** [comment]
Do commit the `rtl_433.example.conf`, the changes have been missed before and are good. Do not commit other unrelated changes like the man page. Thanks!

**Comment by jpmv27** [comment]
Done. Thank you for your patience.

**Pull request merged**
