### PR TITLE
Update sdr.c

### PR DESCRIPTION
**Pull request by Isa001**
Enable the internal digital AGC of the RTL2832

### CODE REVIEW

**Comment by zuckschwerdt** [comment]
Discussion in #1749

**Comment by Mindavi** [comment]
Make sure to format this appropriately.

**Comment by merbanan** [comment]
This code illustrates well how the backend code needs to work. We just need to come to a conclusion how the command line parsing should work.

**Comment by zuckschwerdt** [comment]
Thanks for debugging and prototyping this! Closing in favor of more general solution in #1788

**Pull request closed without merging**
