### PR TITLE
fsk: add Y option for selecting different fsk low pass coefficients

### PR DESCRIPTION
**Pull request by merbanan**
Prepatory work for new fsk pulse detector.

FSK demod low pass filter selection.

### CODE REVIEW

**Comment by merbanan** [comment]
@zuckschwerdt this is as clean as I could make it. The -r sample file option will not work though. I think the file name parser needs to set frequency and sample rate cfg values to get it to work the same.

**Comment by merbanan** [comment]
Anyway the code works, there are some tiny changes before I can merge. I just want overall input of the approach.

**Comment by merbanan** [comment]
With this patch several decoders should be able to activate by default.

**Comment by zuckschwerdt** [comment]
Overall looks tidy enough. The `-r` option should be fixable later.

**Comment by merbanan** [comment]
Ok, the is now fairly useful. I'll merge it now and improve it later.

**Pull request merged**
