### PR TITLE
Adding TyreGuard 400 TPMS

### PR DESCRIPTION
**Pull request by Topper69**

### CODE REVIEW

**Comment by zuckschwerdt** [comment]
Note that
- `crc8(&b[0], 10, 0x31, 0xdd) != PacketCRC)` is identical to `crc8(b, 11, 0x31, 0xdd) != 0` which is preferred.
- `temp_c = (int) b[8] - 40;` does not need the cast, it's already int (C integer promotion)
- the doc comment needs to be well-formed markdown, indent code blocks by 4 spaces, put dashes in lists.

**Comment by Topper69** [comment]
crc8 code + temp_c has been changed.
About the docs, not sure i have fixed all what you ask for :/ (not sure i have fully understood).

**Comment by zuckschwerdt** [comment]
Sorry for being unclear, the markdown should not be indented, just the code blocks:
```
/**
TPMS TyreGuard 400 from Davies Craig.

...
- Length          : 22 bytes long

Packet layout:

     1    2    3    4    5    6    7    8   9   10  11  12  13  14  15  16  17   18   19   20   21  22
     S/P  S/P  S/P  S/P  S/P  S/P  S/P  ID  ID  ID  ID  ID  ID  ID  Pr  Pr  Temp Temp Flg  Flg  CRC CRC
    
- S/P   : preamble/sync "0xfd5fd5f" << always fixed
...
```

**Comment by zuckschwerdt** [comment]
Oh and, `pressure_kpa = b[7] | ((flags & 0x10)<<4) | ((flags & 0x20)<<4) | ((flags & 0x40)<<4) ;` is `pressure_kpa = b[7] | ((flags & 0x70) << 4);` (1+2+4=7)

**Comment by Topper69** [comment]
> Oh and, `pressure_kpa = b[7] | ((flags & 0x10)<<4) | ((flags & 0x20)<<4) | ((flags & 0x40)<<4) ;` is `pressure_kpa = b[7] | ((flags & 0x70) << 4);` (1+2+4=7)

Many thanks. Updated.

**Pull request merged**
