### PR TITLE
Add SoapySDR support

### PR DESCRIPTION
**Pull request by zuckschwerdt**
Adds SoapySDR support properly.
RTL-SDR and SoapySDR drivers are compile-time selectable.
Tested with RTL-SDR, LimeSDR USB, LimeSDR mini, and HackRF.

### CODE REVIEW

**Comment by zuckschwerdt** [comment]
SoapySDR is finally ready. Everybody interested please have a look and test. SoapySDR will be merged in a few days.

**Comment by sdoempke** [comment]
Hi, it testet it with the PlutoSDR.

Its running on Ubuntu 18.04 as well as on the PlutoSDR itself (cross compiled it).
I'm using the 0.29 firmware with soapy 0.15.

On imported thing is to set the bit detection level to 100 and lower.
With auto detection nothing is detected as signals are to weak. 
In the default configuration the slow attack AGC is enabled, which maxes out the gain in my test enviroment at home.

When running on the PlutoSDR the samplerate can be set to a maximum of 500000. The cpu is to slow for higher samplesrates.

Thank you very much for your work!

-----------------
Using device Backend version: 0.15 (git tag: v0.15): ad9361-phy,model=ad9364 ad9361-phy,xo_correction=39999855 fw_version=v0.29 hw_model=Analog Devices PlutoSDR Rev.B (Z7010-AD9363) hw_model_variant=0 hw_serial=104473222a870007eaff2400da48d5104b local,kernel=4.9.0-10475-g2398d50 
Found 1 antenna(s): A_BALANCED 
Found 1 gain(s): PGA 0 - 89 (step 0) 
Found 1 frequencies: RF 
Found 1 frequency range(s): 70000000 - 6000000000 (step 0) 
Found 11 sample rate range(s): 65105 1000000 2000000 3000000 4000000 5000000 6000000 7000000 8000000 9000000 10000000 
Found 11 bandwidth range(s): 200000 - 200000 (step 0) 1000000 - 1000000 (step 0) 2000000 - 2000000 (step 0) 3000000 - 3000000 (step 0) 4000000 - 4000000 (step 0) 5000000 - 5000000 (step 0) 6000000 - 6000000 (step 0) 7000000 - 7000000 (step 0) 8000000 - 8000000 (step 0) 9000000 - 9000000 (step 0) 10000000 - 10000000 (step 0) 
Found current bandwidth 18000000
Found 3 stream format(s): CS8 CS16 CF32 
Found native stream format: CS16 (full scale: 2048.0)
[INFO] Auto setting Buffer Size: 4194304
[INFO] Auto setting Buffer Size: 65536
Sample rate set to 500000 S/s.
Bit detection level set to 100.
Tuner gain set to Auto.
Reading samples in async mode...
Tuned to 433.920MHz.

**Comment by zuckschwerdt** [comment]
@sdoempke thank you for the interesting report! Did you try various gain settings (`-g`) to see if something can be improved? The native 12 bits (CS16, full scale: 2048.0) should be well supported. There is a scale-up to 16 bits so rtl_433 should be able to see a -0 dBFS (maximum) signal if the gain is right.

**Comment by zuckschwerdt** [comment]
If I read that right, the AGC is supposed to max out the 12 bit range and that should be [scaled to 16 bit range](https://github.com/merbanan/rtl_433/blob/faa1485b3721fbaacaf2b600cf9f4eaf613f8f66/src/sdr.c#L455) but that's not what you see?
Can you record a sample (`rtl_433 driver=plutosdr -T 30 -w test-pluto.cs16`) and check the spectrogram (http://triq.net/iqs)?

**Comment by sdoempke** [comment]
@zuckschwerdt 

I made three records (-g 5, -g 70 and auto) and looked at them in the iq spectrogram.
They all look the same to me and have almost the same value region ( ~ -41 dB – ~ -1 dB). 
So i guess there something wrong with the gain setting in the soapy driver for plutosdr.

In SDR# with 5 db gain i can't see the signal of my temperature sensor, while the signal was visible in the recording with -g 5.
So think i have to take closer look at the soapy driver for the pluto.

**Comment by sdoempke** [comment]
I think i found.
The AGC mode seams to be active by default and unless SoapySDRDevice_setGainMode is called to set automatic = false the gain setting is ignored. Be it -g X oder -g PGA=X.

I add the call to SoapySDRDevice_setGainMode in soapysdr_gain_str_set before calling SoapySDRDevice_setGain. And now i can see differences in the iq spectrogram. 
With -g 5 i cant see any signal (so just like SDR#).
With -g 70 i get the same results as with the agc enabled.

But without reducing the limit (-l 100) nothing is found.

**Comment by zuckschwerdt** [comment]
I added a fix manual gain in PlutoSDR: 3e036c6
Can you confirm that works?

**Comment by sdoempke** [comment]
if i print the driver key to the console
`fprintf(stderr, "Driver=%s", driver);`
it shows
`Driver=Library version: 0.15 (git tag: v0.15)`

This is how the driverKey is implemented -> [Link](https://github.com/jocover/SoapyPlutoSDR/blob/master/PlutoSDR_Settings.cpp#L59)

Would it be any aproach to setGainMode by default for all SDR supported by Soapy?
-> Manual: SetGainMode(false)
-> Automatic: SetGainMode(true)
Unfortunatly the plutosdr driver doesn't implement hasGainMode. So checking before calling it will always return false.

**Comment by zuckschwerdt** [comment]
Oh, I didn't check the actual driver key. That should possibly be fixed at the PlutoSDR project (as well as hasGainMode).
I'd say calling setGainMode() with any setGain() looks like the right way to do it.
Let's see if https://github.com/pothosware/SoapyRTLSDR/pull/33 is accepted. That would put RTL-SDR in line with your suggestion.

**Comment by sdoempke** [comment]
Ok, i'll modify the driver and check it the modification is working.

I think i found the issue in the up-scaling.
When i replace 

```
if (dev->fullScale == 2048.0) {
   for (i = 0; i < n_read * 2; ++i)
         buffer[i] << 4;
} 
```
With

 ```
if (dev->fullScale == 2048.0) {
    for (i = 0; i < n_read * 2; ++i)
         buffer[i] = buffer[i] << 4;
}
```
Its working without any changes the limit.

**Before (with -l 100):**

```
Detected FSK package    @ 1970-01-01 23:41:51
1970-01-01 23:41:51     :       LaCrosse :      TX35DTH-IT      :       37
        Battery:         OK
        NewBattery:      0
        Temperature:     4.8 C
        Integrity:       CRC
Analyzing pulses...
Total count:   38,  width:  5225                (10.4 ms)
Pulse width distribution:
 [ 0] count:    1,  width:     0 [ 0; 0]        (   0 us)
 [ 1] count:   32,  width:    52 [52;60]        ( 104 us)
 [ 2] count:    3,  width:   104 [104;105]      ( 208 us)
 [ 3] count:    2,  width:   156 [156;157]      ( 312 us)
Gap width distribution:
 [ 0] count:    7,  width:   104 [101;105]      ( 208 us)
 [ 1] count:    2,  width:   209 [209;209]      ( 418 us)
 [ 2] count:   25,  width:    52 [51;53]        ( 104 us)
 [ 3] count:    3,  width:   156 [156;157]      ( 312 us)
Pulse period distribution:
 [ 0] count:   22,  width:   104 [101;105]      ( 208 us)
 [ 1] count:    8,  width:   221 [208;261]      ( 442 us)
 [ 2] count:    7,  width:   156 [156;157]      ( 312 us)
Level estimates [high, low]:   1000,     18
Frequency offsets [F1, F2]:    3347,  -3385     (+25.5 kHz, -25.8 kHz)
Guessing modulation: Pulse Code Modulation (Not Return to Zero)
Attempting demodulation... short_limit: 52, long_limit: 52, reset_limit: 53248, sync_width: 0
pulse_demod_pcm(): Analyzer Device
bitbuffer:: Number of rows: 1
[00] {100} 21 55 55 55 54 5b a9 32 88 90 d4 97 50
```
**After:**
```
Detected FSK package    @ 1970-01-02 00:12:16
1970-01-02 00:12:16     :       LaCrosse :      TX35DTH-IT      :       37
        Battery:         OK
        NewBattery:      0
        Temperature:     4.8 C
        Integrity:       CRC
Analyzing pulses...
Total count:   38,  width:  5229                (10.5 ms)
Pulse width distribution:
 [ 0] count:    1,  width:     0 [ 0; 0]        (   0 us)
 [ 1] count:   32,  width:    52 [52;62]        ( 104 us)
 [ 2] count:    3,  width:   104 [104;105]      ( 208 us)
 [ 3] count:    2,  width:   156 [156;157]      ( 312 us)
Gap width distribution:
 [ 0] count:    7,  width:   104 [104;105]      ( 208 us)
 [ 1] count:    2,  width:   209 [209;209]      ( 418 us)
 [ 2] count:   25,  width:    52 [52;53]        ( 104 us)
 [ 3] count:    3,  width:   156 [156;157]      ( 312 us)
Pulse period distribution:
 [ 0] count:   22,  width:   104 [104;105]      ( 208 us)
 [ 1] count:    8,  width:   221 [208;261]      ( 442 us)
 [ 2] count:    7,  width:   156 [156;157]      ( 312 us)
Level estimates [high, low]:   3202,    270
Frequency offsets [F1, F2]:    3189,  -5635     (+24.3 kHz, -43.0 kHz)
Guessing modulation: Pulse Code Modulation (Not Return to Zero)
Attempting demodulation... short_limit: 52, long_limit: 52, reset_limit: 53248, sync_width: 0
pulse_demod_pcm(): Analyzer Device
bitbuffer:: Number of rows: 1
[00] {100} 21 55 55 55 54 5b a9 32 88 90 d4 97 50

```

**Comment by zuckschwerdt** [comment]
Oh! I never noticed the broken up-scaling. Thanks!

**Comment by zuckschwerdt** [comment]
I have submitted fixes to both the driver key and missing/wrong hasGainMode().
You can review, test, and Thumbs up both PRs at
https://github.com/pothosware/SoapyPlutoSDR/pull/4
https://github.com/pothosware/SoapyPlutoSDR/pull/5

**Comment by zuckschwerdt** [comment]
Slightly off-topic: are you happy with your PlutoSDR? It looks a bargain. May be a good second or testing device.

**Comment by sdoempke** [comment]
Both pull requests are already merged.

I've compiled to current version for the SoapyPlutoSDR and your fork of rtl433 and testet it one the pluto.
Everything is working correctly. I've checked different gain settings in the spectorgram as well as going back to auto gain. 
Thanks a lot!

Regarding the PlutoSDR. I'm happy with it.
I got one of first batches and the mod enable the 2nd CPU core as well as the extended frequency range is working. (As far as i have read this also working for current batch).
I have it currently in the attic which a homemade 433mhz groundplane and a usb -> lan adapter. So i can work remotely and can run it independent.
The other good thing is that i don't have issues with usb noise as i know it with my Airspy R0 + Raspi 3.

An the limit of 4 msps on usb 2.0 or the frequency stability of 25ppm are no isses for me.

**Comment by zuckschwerdt** [comment]
SoapySDR support is now included and the CMake uses RTL-SDR or SoapySDR, both or none as available. The Makefile just uses RTL-SDR, someones needs to write Makefile support for SoapySDR if needed.
The VS2015 builds need to be updated.

**Comment by merbanan** [comment]
You mean autotools/automake?

**Comment by zuckschwerdt** [comment]
Yes, specifically the [configure.ac](https://github.com/merbanan/rtl_433/blob/master/configure.ac#L20) still only looks for LIBRTLSDR. But pkg-config support for SoapySDR.pc shouldn't be much trouble.

**Pull request merged**
