### PR TITLE
Add support for digitech weather station

### PR DESCRIPTION
**Pull request by viraptor**
Currectly works: wind, temperature, humidity
To do: rain, pressure, checksum validation

### CODE REVIEW

**Comment by merbanan** [comment]
Can you send some test signals to rtl_433_tests ?

**Comment by viraptor** [comment]
Preparing them right now

**Comment by merbanan** [comment]
The code looks good. Can you also log x amount of packets so we can take a stab at figuring out the checksum ?

**Comment by viraptor** [comment]
Do you need more than what's in https://github.com/merbanan/rtl_433/issues/166 ? (5 packets)

**Comment by viraptor** [comment]
Also, what can I do about samples which require specific detection level? Everything I have passes only on level 1000..1800.

**Comment by merbanan** [comment]
Can't have too many. Some patterns can only be figured out if you have enough samples. I would say 30 should be enough.

**Comment by merbanan** [comment]
The -l limit parameter is just lowering the bit detection threshold. If you need to lower the limit the signal is not so strong. So either keep the limit low of increase the signal somehow. Better antenna, better placement etc.

**Comment by viraptor** [comment]
I meant for the tests - right now tests are run with the default limit, so my samples won't pass. But I can't get anything better out of my setup unfortunately :(

**Comment by viraptor** [comment]
Not sure if you like the solution, but added samples in https://github.com/merbanan/rtl_433_tests/pull/36

**Comment by rct** [comment]
In terms of the level limit, the greater the distance between the dongle's center frequency and the actual device frequency the lower the signal will be.  you might want to try figuring out what your dongle's frequency error is (PPM) and then specify a --p ppm number.  I have some dongles where the error is as much as 70 ppm - so without correction it is off by 30 Khz.   Your device will likely have some offset too.  Note: you should have some offset to make sure your device isn't too close to the center DC spike.

Of course the things merbanan mentioned, antenna, placement (get the dongle away from the computer) will also play a factor.

Once you have that all figured out, you might want to revisit the limits to see if you have the right timings at reasonable signal levels.

**Comment by viraptor** [comment]
I've already done that. The -f for capture was set exactly to the frequency I got from gqrx's waterfall graph. That's also after ppm correction.

**Comment by rct** [comment]
you need at least a little offset from the center spike.

**Comment by merbanan** [comment]
Forgot to merge, sorry.

**Comment by merbanan** [comment]
Thanks for making rtl_433 better.

**Pull request merged**
