### PR TITLE
added sgooway door detector

### PR DESCRIPTION
**Pull request by rourke750**

### CODE REVIEW

**Comment by rourke750** [comment]
In reference to https://github.com/merbanan/rtl_433/issues/1701

**Comment by zuckschwerdt** [comment]
Thanks! I'd say this is a "x1527-like OTP encoder" device, but not an actual x1527. The sync pulse is missing (bits=24, but should be bits=25 for x1527).
Can you confirm it works with bits=24 but does not work with bits=25, and if so change the info?

**Comment by rourke750** [comment]
So it does work with 25 bits but I noticed it would send a bunch of requests where at 24 it only gets one.  Based on the page it says the ic code is 1527.  Is the sync bit important, should I change my config to 25 and see what happens?

**Comment by zuckschwerdt** [comment]
I see. It is x1527 then :)
The single code with 24 bits is bad/truncated, the sync is missing. All other codes are proper 25 bits.

You should use bits=25 to avoid problems and try out `,unique`(suppress duplicate row output) or `,countonly` (suppress detailed row output).

**Comment by rourke750** [comment]
Switched to 25 bits and added unique:
Looks like this
decoder {
  name=sgooway,
  modulation=OOK_PWM,
  short=280,
  long=990,
  reset=2000,
  bits=25,
  get=@0:{25}:code,
  unique
}
still seeing 20ish messages per broadcast

**Comment by zuckschwerdt** [comment]
The `get` should have a length of `{24}` only. The last bit is the sync.
The reason for so many messages could be the distance between messages, is it longer than reset?

**Comment by rourke750** [comment]
Set it to 24 bits getting significantly fewer.  All messages coming in are within 1 second.

**Pull request merged**
