### PR TITLE
Add support for Oil-SonicSmart

### PR DESCRIPTION
**Pull request by zuckschwerdt**
See #2244

Open questions:

- [ ] How long does the pairing/test mode last? (the captures are only 30 secs).
- [ ] What is the stated range of depth readings? Esp. is the maximum over 255?
- [ ] What triggered the pairing/test mode? A magent like for other sensors?
- [ ] Does the unit ID change when you rebind by holding a magnet to the sensor for long enough?
- [ ] Can you simulate alarms like Leak/theft alarm?
- [ ] Confirm the binding counter, i.e. something that's only active in test mode.
- [ ] I.e. does the counter stop when the magnet is removed?
- [ ] Is there an error flag for "no reading"?

### CODE REVIEW

**Comment by StarMonkey1** [comment]
> See #2244
> 
> Open questions:
> 
> * [ ]  How long does the pairing/test mode last? (the captures are only 30 secs).
Seems to be around 5 minutes (https://github.com/merbanan/rtl_433/blob/master/src/devices/oil_standard.c is a similar model and states 11 minutes)
> * [ ]  What is the stated range of depth readings? Esp. is the maximum over 255?
Unknown but maximum shown in the manual is 300cm, minimum 12cm, (https://www.rpm-fuels.co.uk/system/storage/download/Apollo-Smart-Product-Manual.pdf) https://github.com/merbanan/rtl_433/blob/master/src/devices/oil_standard.c says 305cm and 3cm
> * [ ]  What triggered the pairing/test mode? A magnet like for other sensors?
Magnet on a black dot on the side of the unit.
> * [ ]  Does the unit ID change when you rebind by holding a magnet to the sensor for long enough?
Unknown,  but the smart receiver doesn't need repairing after the test mode.
> * [ ]  Can you simulate alarms like Leak/theft alarm?
Possibly, its detected by speed of change of level. Without a decoder I've not been able to monitor the transmissions longer term so not sure how many times per hour/day etc. a reading is taken to then simulate a leak/theft.
> * [ ]  Confirm the binding counter, i.e. something that's only active in test mode.
> * [ ]  I.e. does the counter stop when the magnet is removed?
Magnet is only placed on the sensor for a few seconds to activate test mode and then removed.
> * [ ]  Is there an error flag for "no reading"?
Again unsure, there are several errors referred to in the manual but it's not clear on which sensor readings trigger them.

**Comment by zuckschwerdt** [comment]
Thanks! Over all very much like the "Standard" model/protocol then.
If you monitor the data over the next weeks, note that "flags" and "alarm" are just two raw bytes with no meaning so far. Perhaps you can on occasion spot pattern there?

**Comment by StarMonkey1** [comment]
> Thanks! Over all very much like the "Standard" model/protocol then. If you monitor the data over the next weeks, note that "flags" and "alarm" are just two raw bytes with no meaning so far. Perhaps you can on occasion spot pattern there?

I think the sensor is pretty much the same as the classic Apollo sensor, it might just be the receiver that's different. The Apollo kit is very badly documented so it's difficult to know.

Should I build this branch by source and run it that way or is there a branch release? Eventually I want to run this within the Home Assistant RTL add-on but can run within an Ubuntu VM for the time being for testing.

**Comment by zuckschwerdt** [comment]
In terms of features very much the same, but there is more "room" in the data fields, so e.g. flags might map differently.

If you running docker is more convenient then use the branch `feat-oilsmart` (instead of `master`).

**Comment by StarMonkey1** [comment]
Yup, I've built from the feat-oilsmart branch and I've left it running in an Ubuntu VM (rather than docker). Fingers crossed no hardware crashes overnight. I think the oil monitor only sends updates very infrequently so they're difficult to catch!

What were the specific flags in the classic monitor? I'll see if I can figure out from functions in the smart display what any additional flags might be and how I could trigger/test them.

**Comment by zuckschwerdt** [comment]
> see if I can figure out from functions in the smart display what any additional flags might be and how I could trigger/test them.

That would be great! The knowledge we have is summarized here:
https://github.com/merbanan/rtl_433/blob/46491d3b87d9f5266c3c15e46f2b3dd1e3f5851f/src/devices/oil_standard.c#L60-L84

**Comment by StarMonkey1** [comment]
Ok, so I left it collecting data overnight and while it has now identified the data and rtl_433 recognises it the data contained within must be being decoded incorrectly. rtl_433 shows:

model: oil-ultrasonic
id: bd01
flags: 17
alarm: 0c
binding_countdown: 50
depth_cm: 0

The alarm value appears to change variously to:
0e
10
12

Readings appear to be every half and hour or so.

**Comment by zuckschwerdt** [comment]
Thanks. I've updated the branch with those hints and disabled the binding/depth switch (same value anyway)

**Comment by StarMonkey1** [comment]
We've used oil since yesterdays comment (smart display shows less in litres) but the depth_cm is still reading 51 so I don't think it's decoding the correct part of the data. I'll attempt to get the sensor out today to see if that makes a difference.

**Comment by zuckschwerdt** [comment]
> I'll attempt to get the sensor out today to see if that makes a difference.

Can you simply compare the reading you got before and after the change?

We only need/can compare these three `flags: 17 alarm: 36 depth_cm: 51`

The first two bytes will have a bit (MSB) for >255 cm, and may also have bit(s) for sub-cm reading. 2 bits for 1/4 cm readings maybe.

**Comment by StarMonkey1** [comment]
> > I'll attempt to get the sensor out today to see if that makes a difference.
> 
> Can you simply compare the reading you got before and after the change?
> 
> We only need/can compare these three `flags: 17 alarm: 36 depth_cm: 51`
> 
> The first two bytes will have a bit (MSB) for >255 cm, and may also have bit(s) for sub-cm reading. 2 bits for 1/4 cm readings maybe.

Sorry, I'm not sure I understand what you mean. Which readings do you think I should compare?

**Comment by zuckschwerdt** [comment]
Yesterday it was `flags: 17 alarm: 36 depth_cm: 51` what is it today? `flags: xx alarm: yy depth_cm: 51`

**Comment by StarMonkey1** [comment]
depth_cm: 52

flags are 17 and alarm 30 or 32.

Anything else I should be doing/testing at the moment?

**Comment by zuckschwerdt** [comment]
We can copy your table to [this BitBench](https://triq.net/bitbench#c=5558%20bd01%2017%2036%2033%5B2022-12-19%2011%3A51%3A18%5D&c=5558%20bd01%2017%2036%2033%5B2022-12-19%2012%3A25%3A28%5D&c=5558%20bd01%2017%2036%2033%5B2022-12-19%2012%3A59%3A38%5D&c=5558%20bd01%2017%2036%2033%5B2022-12-19%2013%3A33%3A48%5D&c=5558%20bd01%2017%2036%2033%5B2022-12-19%2014%3A07%3A58%5D&c=5558%20bd01%2017%2036%2033%5B2022-12-19%2014%3A42%3A07%5D&c=5558%20bd01%2017%2036%2033%5B2022-12-19%2015%3A16%3A17%5D&c=5558%20bd01%2017%2036%2033%5B2022-12-19%2015%3A50%3A27%5D&c=5558%20bd01%2017%2036%2033%5B2022-12-19%2016%3A24%3A37%5D&c=5558%20bd01%2017%2036%2033%5B2022-12-19%2017%3A32%3A57%5D&c=5558%20bd01%2017%2038%2033%5B2022-12-19%2018%3A07%3A07%5D&c=5558%20bd01%2017%2038%2033%5B2022-12-19%2018%3A41%3A17%5D&c=5558%20bd01%2017%2038%2033%5B2022-12-19%2019%3A15%3A27%5D&c=5558%20bd01%2017%203a%2033%5B2022-12-19%2019%3A49%3A37%5D&c=5558%20bd01%2017%203a%2033%5B2022-12-19%2020%3A23%3A47%5D&c=5558%20bd01%2017%203a%2033%5B2022-12-19%2020%3A57%3A57%5D&c=5558%20bd01%2017%203a%2033%5B2022-12-19%2021%3A32%3A07%5D&c=5558%20bd01%2017%203a%2033%5B2022-12-19%2022%3A06%3A17%5D&c=5558%20bd01%2017%203a%2033%5B2022-12-19%2022%3A40%3A28%5D&c=5558%20bd01%2017%203a%2033%5B2022-12-19%2023%3A14%3A38%5D&c=5558%20bd01%2017%203a%2033%5B2022-12-19%2023%3A48%3A48%5D&c=5558%20bd01%2017%2038%2033%5B2022-12-20%2000%3A22%3A58%5D&c=5558%20bd01%2017%2038%2033%5B2022-12-20%2000%3A57%3A08%5D&c=5558%20bd01%2017%2038%2033%5B2022-12-20%2001%3A31%3A18%5D&c=5558%20bd01%2017%2038%2033%5B2022-12-20%2002%3A05%3A29%5D&c=5558%20bd01%2017%2038%2033%5B2022-12-20%2002%3A39%3A39%5D&c=5558%20bd01%2017%203a%2033%5B2022-12-20%2003%3A13%3A49%5D&c=5558%20bd01%2017%203a%2033%5B2022-12-20%2003%3A47%3A59%5D&c=5558%20bd01%2017%203a%2033%5B2022-12-20%2004%3A22%3A09%5D&c=5558%20bd01%2017%203a%2033%5B2022-12-20%2004%3A56%3A19%5D&c=5558%20bd01%2017%2036%2033%5B2022-12-20%2005%3A30%3A29%5D&c=5558%20bd01%2017%2034%2033%5B2022-12-20%2006%3A04%3A39%5D&c=5558%20bd01%2017%2032%2033%5B2022-12-20%2006%3A38%3A49%5D&c=5558%20bd01%2017%2030%2033%5B2022-12-20%2007%3A12%3A58%5D&c=5558%20bd01%2017%202e%2033%5B2022-12-20%2007%3A47%3A08%5D&c=5558%20bd01%2017%202c%2033%5B2022-12-20%2008%3A21%3A17%5D&c=5558%20bd01%2017%202c%2033%5B2022-12-20%2008%3A55%3A26%5D&c=5558%20bd01%2017%202a%2033%5B2022-12-20%2009%3A29%3A35%5D&c=5558%20bd01%2017%2032%2033%5B2022-12-20%2010%3A03%3A44%5D&c=&c=5558%20bd01%2017%2030%2034%5B2022-12-20%2010%3A03%3A44%5D&c=5558%20bd01%2017%2032%2034%5B2022-12-20%2010%3A03%3A44%5D&f=PRE%3F8h8h%20ID%3F8h8h%208h%204b%204b%20CM%3A8d%20CRC8h&cw=4).

The bits just before the "cm" field seem to roughly increase, e.g.
2022-12-19 17:32:57 to 2022-12-19 18:07:07
and 2022-12-19 19:15:27 to 2022-12-19 19:49:37
but then much jitter and suddenly 51cm jumps to 52cm. I would have expected the field to be close to `1111` before that, not `1001`.
Not clear how to confirm anything. Likely best to just watch for a longer period and try to match up with the display unit?

**Comment by StarMonkey1** [comment]
This is looking good, I've got data since my last post and everything seems pretty stable.
To bottom out the depth I stuck a pole to the base of the tank and measured from top of tank to oil level, the reading said 73cm and my pole measured at 75cm (and there was a lot of roughness with my measurements). I think this confirms the depth reading is correct.

The flags data seems to be very stable, the alarm data seems to regularly change but I'm not sure what that's related to.

**Comment by zuckschwerdt** [comment]
OK, thanks. I guess "flags" then includes alarm and "alarm" is really a counter or temperature or such.
Maybe I'll just add a note and we'll leave it with depth only.

**Comment by StarMonkey1** [comment]
I guess if it merges and more people come across it we may come across other events. We've not had a refill yet for example, I guess those things can always be added as time goes on.

**Comment by zuckschwerdt** [comment]
Merging this now. If you ever get the chance to observe a distance going above 255 cm then please post the output (e.g at 250, 255, 256, 260). Also if you detect a pattern in the "unknown" fields :)

**Pull request merged**
