### PR TITLE
Add basic logger

### PR DESCRIPTION
**Pull request by zuckschwerdt**
Adds basic structured logging.
- allows (e.g. HTTP output) to capture log messages
- allows library use and different apps with custom log handling
- allows coloring of logs (`key: value`), highlighting of errors, ...
- `fprintf`'s are re-defined to use logging for now, until calls are converted

### CODE REVIEW

**Comment by gvanem** [comment]
This is a good idea. I've for some time liked to have a console-log like I've done in my [ADSB-decoder](https://github.com/gvanem/Dump1090):
dump1090-win

I.e. not a scrolling text-window, but *one* line per unique detected device. Not sure how to detect such uniqueness.

**Comment by zuckschwerdt** [comment]
Great idea! The HTTP output app already does something like this. Using e.g. ncurses we could bring that to the console: a section with unique devices and last reading (csv table like), and another section with running log output.

The current setup is to funnel some messages to the data output, which should be replaced with structured logging for a clear distinction: device readings, log messages.

**Comment by gvanem** [comment]
>  Using e.g. ncurses we could bring that to the console: 

Some more modern than that? *notcurses* look awesome:  https://youtu.be/mOmMcFXdd6k?t=115

**Comment by zuckschwerdt** [comment]
Closing in favor of #2254

**Pull request closed without merging**
