### PR TITLE
minor: Improve Govee parity

### PR DESCRIPTION
**Pull request by aav7fl**
Improve the Govee parity improvement based on new data from: https://github.com/merbanan/rtl_433/pull/1810#issuecomment-924279355

I believe new data changes our parity. With examples provided by @billgrundmann it becomes more obvious that bytes[2-4] _do_ matter where as my own data didn't show this.

<details>
<summary>
Binary values
</summary>

```
y01101111 00111010 11111010 11111010 11111000 10101111
y01101110 00011001 11111010 11111010 11111000 10101111
y01011100 01100110 11111010 11111010 11111000 10111101
y01101101 00011110 11111010 11111010 11111000 10100111
y01100111 11111001 11111010 11111010 11111000 10100001
y01101110 00101101 11111010 11111010 11111000 10100001
y01011100 00000111 11111010 11111010 11111000 10110011
y01101110 01000010 11111010 11111010 11111000 10110011
y01101110 00111010 11111010 11111010 11111000 10101101
y00100011 00000011 11111100 01001101 11111100 10110111
y00100011 00000011 11111100 01000111 11111100 10100011
y00011001 01010111 11111100 01001110 11111100 10100001
y00110001 00010010 11111100 01000110 11111100 10100111
y00110001 00010010 11111101 11111101 11111100 10100101
y00110001 00010010 11111010 11111010 11111000 10101101
y01010110 00010100 11111010 11111010 11111000 10100011
```

</details>

<details>
<summary>
RevSum Input
</summary>

```
0x6f, 0x3a, 0xfa, 0xfa, 0xf8, 0x07
0x6e, 0x19, 0xfa, 0xfa, 0xf8, 0x07
0x5c, 0x66, 0xfa, 0xfa, 0xf8, 0x0e
0x6d, 0x1e, 0xfa, 0xfa, 0xf8, 0x03
0x67, 0xf9, 0xfa, 0xfa, 0xf8, 0x00
0x6e, 0x2d, 0xfa, 0xfa, 0xf8, 0x00
0x5c, 0x07, 0xfa, 0xfa, 0xf8, 0x09
0x6e, 0x42, 0xfa, 0xfa, 0xf8, 0x09
0x6e, 0x3a, 0xfa, 0xfa, 0xf8, 0x06
0x23, 0x03, 0xfc, 0x4d, 0xfc, 0x0b
0x23, 0x03, 0xfc, 0x47, 0xfc, 0x01
0x19, 0x57, 0xfc, 0x4e, 0xfc, 0x00
0x31, 0x12, 0xfc, 0x46, 0xfc, 0x03
0x31, 0x12, 0xfd, 0xfd, 0xfc, 0x02
0x31, 0x12, 0xfa, 0xfa, 0xf8, 0x06
0x56, 0x14, 0xfa, 0xfa, 0xf8, 0x01
```

</details>

Putting that through RevSum returns:

```
BYTE_REFLECT Reflecting...
Complete message...
Found: crc8(&b[0], 5, 0x10, 0x00) ^ b[5] == 0; // (100.0%)
INVERT BYTE_REFLECT Inverting...
Complete message...
Found: crc8(&b[0], 5, 0x10, 0xff) ^ b[5] == 0; // (100.0%)
```

It sounds like there might be an update to the data.

I have applied the first result in this PR.

### CODE REVIEW

**Comment by zuckschwerdt** [comment]
To make it obvious that this is nibble-wide xor, the check should be
```
    int chk = xor_bytes(b, 5);
    chk     = (chk >> 4) ^ (chk & 0xf);
```

**Comment by aav7fl** [comment]
> To make it obvious that this is nibble-wide xor, the check should be
> 
> ```
>     int chk = xor_bytes(b, 5);
>     chk     = (chk >> 4) ^ (chk & 0xf);
> ```

I'm not sure I understand what's happening here entirely.

Forgive me for being verbose here. I want to make I understand why things are happening and what their purpose is.

Things that I've learned so far:
- A nibble is 4 bits.
- `int chk = xor_bytes(b, 5);` is calling [this function](https://github.com/merbanan/rtl_433/blob/be704c93b20ad57043a5d3db23bc6e97b061d34b/include/util.h#L174-L179). 

1. Since the function returns `uint8_t `,  should it be `uint8_t chk` instead? Or are we changing precision?
2. That `xor_bytes(b, 5);` is that just xor'ing the first 5 bytes together of the data payload [based on this implementation](https://github.com/merbanan/rtl_433/blob/dc1577bd3fea05f3962b5e2358b5b5932dd2a34f/src/util.c#L328-L335). But why are we doing that here?
3. `(chk >> 4)` Why are we shifting it over by 4 (bytes?) 
4. `(chk & 0xf)` This clearly zeros out everything but the lower-nibble
5. `(chk >> 4) ^ (chk & 0xf)` Lastly, why are we xor'ing the two values again? Is it because it's now inverted from the original `xor_bytes`?
6. Are you saying to replace the `crc8le(&b[0], 5, 0x10, 0x00)` with the `nibble-wide xor` you provided?

So:

```c
int chk = xor_bytes(b, 5);
chk     = (chk >> 4) ^ (chk & 0xf);
if (chk != parity) {
```

**Comment by zuckschwerdt** [comment]
1. we are not using `uint8_t` but plain `int` because C's "integer promotion" will use `int` anyway, we just remove conversions.
2. we want a nibble-wide xor of all bits, first make a byte-wide xor
3. move the upper nibble down
4. remove the upper nibble, just keep the lower one
5. xor the upper nibble with the lower nibble, now we have a nibble-wide xor of 10 nibbles (5 bytes)
6. yes ;) it's the same thing but faster and easier to understand, there are no polynomials and shifting involved.

**Comment by merbanan** [comment]
((0x12^0x34) >> 4) ^ (0x12^0x34)&0xF == 0x1^0x2^0x3^0x4

We need 4 bit operations but no type so we do 8bit operations instead.

Basically we use this relation 0x10^0x30^0x02^0x04 == 0x12^0x34 and then in the end we repack the bits. We simdify 4bit operations with 8 bit types.

```
int chk = xor_bytes(b, 5);
chk     = (chk >> 4) ^ (chk & 0xf);
```

This code looks sane. It is a parity calculation but instead of iteration over one bit at a time we take every fourth bit.

**Comment by merbanan** [comment]
Things make perfect sense now. Lets hope it works for all messages.

**Pull request merged**
