### PR TITLE
Adding support for TFA 30.3221.02 Temperature/Humidity sensor

### PR DESCRIPTION
**Pull request by Fakstate**
I'm adding the decoder for the outdoor temperature/humidity sensor TFA 30.3221.02.

### CODE REVIEW

**Comment by zuckschwerdt** [comment]
Looks good for your first venture into C ;)
I see that you have 8 unidentified bits at the end. Possibly a checksum. Can you capture and post a good nunber of different bitbuffer lines here? E.g. add `bitbuffer_print(bitbuffer);` after `bitbuffer_invert(bitbuffer);` -- collect, sort, and post maybe 30 codes here.

**Comment by Fakstate** [comment]
Thank you ! :)

To clarify the protocol a little, the sensor sends 2 x 4 rows quickly, the first 40 bits of the rows are the same each time, the last bit changes according to the rows but do the same pattern (0001 1010). An example :

```
[00] {41} 6e 12 d6 2c fe 00 : 01101110 00010010 11010110 00101100 11111110 0
[01] {41} 6e 12 d6 2c fe 00 : 01101110 00010010 11010110 00101100 11111110 0
[02] {41} 6e 12 d6 2c fe 00 : 01101110 00010010 11010110 00101100 11111110 0
[03] {41} 6e 12 d6 2c fe 80 : 01101110 00010010 11010110 00101100 11111110 1

[00] {41} 6e 12 d6 2c fe 80 : 01101110 00010010 11010110 00101100 11111110 1
[01] {41} 6e 12 d6 2c fe 00 : 01101110 00010010 11010110 00101100 11111110 0
[02] {41} 6e 12 d6 2c fe 80 : 01101110 00010010 11010110 00101100 11111110 1
[03] {41} 6e 12 d6 2c fe 00 : 01101110 00010010 11010110 00101100 11111110 0
```

Here are the 30 different codes :

```
6e 12 f0 1f bd 00
6e 12 ef 20 83 00
6e 12 ee 20 c5 00
6e 12 ed 20 0f 00
6e 12 ec 20 49 00
6e 12 ec 21 bd 00
6e 12 eb 21 5e 00
6e 12 ea 21 18 00
6e 12 e9 21 d2 00
6e 12 e8 21 94 00
6e 12 e7 21 25 00
6e 12 e6 22 4e 00
6e 12 e5 22 84 00
6e 12 e4 22 c2 00
6e 12 e3 22 21 00
6e 12 e3 23 d5 00
6e 12 e2 23 93 00
6e 12 e1 23 59 00
6e 12 e0 24 b1 00
6e 12 df 24 dd 00
6e 12 df 25 29 00
6e 12 de 26 42 00
6e 12 dd 26 88 00
6e 12 dc 27 3a 00
6e 12 db 27 d9 00
6e 12 db 28 40 00
6e 12 da 28 06 00
6e 12 d9 29 38 00
6e 12 d8 29 7e 00
6e 12 d8 2a 53 00
6e 12 d7 2a e2 00
```
I hope that's what you asked !

**Comment by zuckschwerdt** [comment]
Yes, exactly. A quick check shows that it could be a LFSR of Rev-Galois with gen 31 and init f4.
I.e. something like `lfsr_digest8(bytes, 5, 0x31, 0xf4) == 0` should always be true.
This particular function won't work as it takes the bits in the wrong order. I'll have to add another function.

In the meantime: can you take out the battery to generate an new ID and record a few codes with a different ID? That way we can confirm that LFSR.

**Comment by Fakstate** [comment]
Yes of course ! Here are the codes, I took 10 if you need more tell me.

```
a1 13 0d 24 5e 00
16 13 0c 24 74 00
89 13 0c 24 de 00
65 13 0c 25 81 00
b4 13 0c 25 5c 00
```

**Comment by merbanan** [comment]
@Fakstate do you have some sample signals?

**Comment by Fakstate** [comment]
@merbanan Yeah sure, I can put them in the rtl_433 test repository if you want.

**Comment by merbanan** [comment]
Yes, that is the preferred way.

**Comment by hvbommel** [comment]
I intergrated this change into Domoticz and tested it (-R 157). It works great, I am seeing correct temperature and humidity values.

**Comment by zuckschwerdt** [comment]
Strangely, this seems to be a LaCrosse TX141TH, see #1652

**Pull request merged**
