### PR TITLE
Fix fileformat.c

### PR DESCRIPTION
**Pull request by winterrace**
Currently, rtl_433 can not be compiled any more by using MS VisualStudio 2015 and 2017 (tested both).
These 2 changes are required in fileformat.c to make it compile again.

Because:
- strings.h is not part of standard C. For MS compilers, I defined stncasecmp as _strnicmp having the same syntax.
- variable length arrays are not yet supported by MS compilers. I wrote a malloc/free variant which is only used when using a MS compiler.

### CODE REVIEW

**Comment by merbanan** [comment]
VLA's are evil, replace it with a fixed large size buffer. Don't riddle the code with ifdefs.

**Comment by winterrace** [comment]
Even better, thank you.

**Comment by winterrace** [comment]
As requested, I removed the ifdefs within the code by fixing the array to 512 bytes (should be enough).

**Comment by winterrace** [comment]
By the way, I suppose this routine will yield undesired behavior when windows style paths are used (e.g. C:\path\filename.am.s16) because of the colon.
Could we use another separator here, e.g. |? Further alternatives (characters which are forbidden in file names) would be *, ? or < / >.
Shall I open a new issue?

**Comment by zuckschwerdt** [comment]
Oh, that colon was a dumb choice then, indeed. I would like to enter it without the need of shell escapes. Any other ideas, esp. not `; ! * ? < > $ |`? Maybe tilde, plus, or hash – though I don't seem to be the best judge here ;)

**Comment by merbanan** [comment]
OCTOTHORPE

**Comment by merbanan** [comment]
but really ~ is fine

**Comment by winterrace** [comment]
Though, in principle, hash or tilde could be part of valid file names, I could also live with one of these.
I don't see any significant use cases that we block this way...

**Comment by zuckschwerdt** [comment]
Just throwing another idea in the ring, double colon `::`…

**Comment by winterrace** [comment]
What about this PR's state? Is the current fix for the "won't compile" problem OK?
Should I change something like reducing the 512 byte buffer a bit further?

And who will address the separator problem?

**Comment by zuckschwerdt** [comment]
I pushed a small fix (no backslash after colon allowed) and will get on this again later.

**Comment by zuckschwerdt** [comment]
Can you test again? Should be properly fixed now. A colon followed by a backslash is now disregarded.

**Pull request merged**
