### PR TITLE
Add Fine Offset WH32B support

### PR DESCRIPTION
**Pull request by zuckschwerdt**
See #971.

### CODE REVIEW

**Comment by merbanan** [comment]
All good. The type could be a define as used in other places of the file. (And maybe rename it to model for consistency.)

One wonder how much perversion they are going to do their protocol.

Regarding the missing xor-sum. That could be used to validate the model/type (again). Not sure if it is wise to do that, I just wanted it mentioned.

**Comment by zuckschwerdt** [comment]
Agreed.
Fine Offest needs to be split OOK vs FSK. The FSK needs a different loop to find the sync word anyway.
Thought that about the XOR too, but there is no length indication an thus we might get 1/256 false classifications.

**Comment by cpaul1715** [comment]
I just downloaded, compiled and tested the new wh32b support.  I am getting two alternating messages with different IDs--one has correct data (ID 239) and the other (ID 7) has incorrect data.  Any ideas what may be wrong?  What additional data do I need to provide to assist resolving this issue?

Command line was simply
$ rtl_433 -f 915M -R 78

time      : 2019-04-09 11:54:13
model     : Fineoffset-WH32B                       ID        : 7
Temperature: 49.8 C      Humidity  : 96 %          Pressure  : 1133.7 hPa    Battery   : OK            Integrity : CHECKSUM
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2019-04-09 11:54:19
model     : Fineoffset-WH32B                       ID        : 239
Temperature: 20.8 C      Humidity  : 45 %          Pressure  : 990.1 hPa     Battery   : OK            Integrity : CHECKSUM
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2019-04-09 11:55:14
model     : Fineoffset-WH32B                       ID        : 7
Temperature: 49.8 C      Humidity  : 97 %          Pressure  : 1145.3 hPa    Battery   : OK            Integrity : CHECKSUM
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2019-04-09 11:55:19
model     : Fineoffset-WH32B                       ID        : 239
Temperature: 20.9 C      Humidity  : 45 %          Pressure  : 990.1 hPa     Battery   : OK            Integrity : CHECKSUM
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

**Comment by merbanan** [comment]
Record some sample signals so we can investigate.

**Comment by slvrscoobie** [comment]
How do I record samples. (I think I actually did this not long ago, with cubicsdr) I’ve got the same issue. I’ve got a mix of 8 wh31 and a wh32b and the new update (compiled days before the wh32b was released) worked fine with the wh31, I got channel id and correct readings. But now I get two. One correct and one incorrect that weewx ignores. I’d like to solve this so I can get the correct data and pull the data from my wh32 and get rid of my wh25 (or relocate it)

**Comment by merbanan** [comment]
@slvrscoobie Intructions for recording samples are found here:

https://github.com/merbanan/rtl_433#supporting-additional-devices-and-test-data

**Pull request merged**
