### PR TITLE
Adding BTHGN129 osv2.2 Temp, Hum and Pressure sensor & WGR800 OSV3 Senso...

### PR DESCRIPTION
**Pull request by deennoo**
...r

Adding WGR800 Wind Gauge : 100% working, lot of work is done by : magellannh
BTHGN129 is the same as BTHR968

### CODE REVIEW

**Comment by merbanan** [comment]
Can you rebase and resubmit, I will merge after that.

**Comment by deennoo** [comment]
What you mean by rebase ? Sorry i'm not english And github native speaker

**Comment by merbanan** [comment]
http://gitready.com/intermediate/2009/01/31/intro-to-rebase.html

Does that help ?

**Comment by helgew** [comment]
@deennoo: Thank you for the added support for the BTHGN129!

Are you sure the BTHGN129 uses the same encoding as the BTHR968? [This code](https://github.com/contactless/domoticz/search?utf8=%E2%9C%93&q=sTypeTHB1) treats it the same as the BTHR918, but I cannot find where the actual data is coming from.

The reason I am asking is that the BTHGN129 has a 5-channel setting that is not captured by your code and that rtl_433 with your changes produces a pressure reading higher than metar for this sensor, which I just purchased. I do not have a display unit, so I cannot know what the decoded value should be, but right now, it is reading 1061 mbar when metar reports 1017 mbar.

**Comment by deennoo** [comment]
I saw that problème ! For pressure i'm working on it

For the channel, i'm working on it to.

You can help me if you want.

**Comment by merbanan** [comment]
Any updates on this ?

**Comment by merbanan** [comment]
Reopen when revisiting.

**Pull request closed without merging**
