### PR TITLE
GT_WT_02: fix gap length threshold as in latest data file

### PR DESCRIPTION
**Pull request by ortylp**
See #117 

The test file provided in test repository seems not be the correct one?!??!?

### CODE REVIEW

**Comment by merbanan** [comment]
There are other transmitters sending all the time. Could be that.

**Comment by ortylp** [comment]
But the bit sequence is OK for old and new recording.  Even the checksum is correct.

**Comment by merbanan** [comment]
Thanks.

**Comment by merbanan** [comment]
Can you remove the old sample and send the new ones ?

**Pull request merged**
