### PR TITLE
Add support for Oregon Scientific BHTR918

### PR DESCRIPTION
**Pull request by billatq**
Tested with a sensor I have locally.

Data here: https://github.com/merbanan/rtl_433_tests/pull/398

### CODE REVIEW

**Comment by zuckschwerdt** [comment]
Thanks! Can you check that all indents are 4 spaces (8 for continuation)?
Also wrap the `data_make` block with
`/* clang-format off */`
`/* clang-format on */`

E.g.
```
    else if (sensor_id == ID_BHTR918) {
        // Similar to the BHTR968, but smaller message and slightly different pressure offset
        if (validate_os_v2_message(decoder, msg, 84, msg_bits, 19) != 0)
            return 0;
        float temp_c = get_os_temperature(msg);
        float pressure = ((msg[7] & 0x0f) | (msg[8] & 0xf0)) + 795;
        /* clang-format off */
        data = data_make(
                "brand",            "",                             DATA_STRING, "OS",
```
...

**Comment by billatq** [comment]
> Thanks! Can you check that all indents are 4 spaces (8 for continuation)?
> Also wrap the `data_make` block with
> `/* clang-format off */`
> `/* clang-format on */`
> 
> E.g.
> 
> ```
>     else if (sensor_id == ID_BHTR918) {
>         // Similar to the BHTR968, but smaller message and slightly different pressure offset
>         if (validate_os_v2_message(decoder, msg, 84, msg_bits, 19) != 0)
>             return 0;
>         float temp_c = get_os_temperature(msg);
>         float pressure = ((msg[7] & 0x0f) | (msg[8] & 0xf0)) + 795;
>         /* clang-format off */
>         data = data_make(
>                 "brand",            "",                             DATA_STRING, "OS",
> ```
> 
> ...

Updated

**Comment by zuckschwerdt** [comment]
Sorry, I missed this: the code should look like the other devices (maybe you copied an old version?).
- no "brand" key,
- "battery_ok" key

compare to https://github.com/merbanan/rtl_433/blob/master/src/devices/oregon_scientific.c#L318-L326

**Comment by billatq** [comment]
> Sorry, I missed this: the code should look like the other devices (maybe you copied an old version?).
> 
>     * no "brand" key,
> 
>     * "battery_ok" key
> 
> 
> compare to https://github.com/merbanan/rtl_433/blob/master/src/devices/oregon_scientific.c#L318-L326

Also fixed.

**Comment by billatq** [comment]
Noticed that there is a typo in the model name carried over from a typo in the BHTR968. Went ahead and fixed for this one since it's new.

**Pull request merged**
