### PR TITLE
src/devices/acurite.c - fix confusing indentation (compiler warning)

### PR DESCRIPTION
**Pull request by afk11**

### CODE REVIEW

**Comment by zuckschwerdt** [comment]
Thanks. But it's actually everything from line 841 `for (uint16_t brow = 0; brow < bitbuf->num_rows; ++brow) {` that needs one indent (4 spaces) more :)

**Comment by afk11** [comment]
Cool, I noticed that, but wanted to keep the diff minimal at first. I'll resubmit, thanks!

**Comment by zuckschwerdt** [comment]
Yes keeping diffs readable and short is a goal. Except when it's a style/formatting update only.

**Comment by zuckschwerdt** [comment]
Just add another commit on top or force push and keep this PR.

**Comment by zuckschwerdt** [comment]
Great! Thanks!

**Pull request merged**
