### PR TITLE
Create rtl_433.1 manual page

### PR DESCRIPTION
**Pull request by alexmyczko**
this is called a man page, putting it into `/usr/share/man/man1/`, `man rtl_433` will show it nicely. you might want to move it into a sub folder, and improve the contents with the output of the `help2man --no-discard-stderr rtl_433` command.

### CODE REVIEW

**Comment by zuckschwerdt** [comment]
Do you also want hook this up to the Makefile and CMake to get installed? Otherwise I'll take a look at that later.

**Comment by alexmyczko** [comment]
Probably that makes sense but only for Linux. You need to check where macOS and FreeBSD want the file. Windows, no idea... as you wish, it only makes sense to keep it, if someone fills up details about the parameters and config file, otherwise not so much (so if nobody wants to edit it, just drop/remove the PR :)

**Comment by zuckschwerdt** [comment]
I guess we wouldn't want to edit roff text by hand. Maybe Asciidoc(tor) or Pandoc could be used (as a maintainer tool, not a dependency). Input would be mostly markdown then.

**Comment by zuckschwerdt** [comment]
I just had a go with asciidoctor. Good results with a simple syntax. I'll merge this, change to asciidoc and hook up in the install scripts in a few days.

**Comment by alexmyczko** [comment]
And tag it a new release?

**Comment by zuckschwerdt** [comment]
That's overdue, yes.

**Comment by alexmyczko** [comment]
19.08 or 19.09?

**Comment by merbanan** [comment]
19.08 should be ok. I have nothing new to add. And among the PR's there is nothing that seems really complete for merging that we could wait for. @zuckschwerdt do you have anything to add before a release?

**Comment by zuckschwerdt** [comment]
I don't see anything big waiting. I'll add a man page (asciidoc format works well) and then we'll slap the release tag on it next week.

**Comment by petterreinholdtsen** [comment]
For the record, FreeBSD keep manual pages in /usr/share/man/man1/ too.  I believe MacOSX do too, but could not verify it right now.

**Comment by klohner** [comment]
For Windows documentation, maybe create [CHM Files From AsciiDoc](http://germaniumhq.com/2018/09/29/2018-09-29-Creating-Chm-Files-From-AsciiDoc/)?

**Pull request merged**
